### ISSUE TITLE
statusline: Use full-word mode indicators

### ISSUE THREAD

**Issue by gregorni** [helix-editor/helix#10130]
Currently, the default mode indicators for normal, insert and selection mode are (in order): `NOR`, `INS`, and `SEL`. While these _work_ for displaying the current mode, it would be more obvious to use clearer mode indicators by default.

In the [Configuration](https://docs.helix-editor.com/configuration.html#editorstatusline-section) section of the docs, the example sets the indicators to `NORMAL`, `INSERT` and `SELECT`, which is also what I've seen a lot of people online use. The longer indicators don't use terribly much extra screen space, but provide a lot more clarity. 

I suggest making them the default instead of the 3-letter indicators.

**Comment by archseer** [comment]
This is a preference. I designed the editor to use the least amount of space in order to work on smaller terminal sizes. Three letters seemed like a reasonable tradeoff between full names and single letter/symbol indicators (which is what I had originally) and can make a significant difference on the file path length/additional statusline components being able to render.
