### ISSUE TITLE
wrong `mim` behaviour ?

### ISSUE THREAD

**Issue by O136** [helix-editor/helix#10254]
### Summary

`mim` for the following case does nothing
![image](https://github.com/helix-editor/helix/assets/16740762/99c2ae97-67e9-4755-b115-a22cb487d93a)

but `mim` for this case:
![image](https://github.com/helix-editor/helix/assets/16740762/eab3e322-3d6e-4a9d-81c6-a25b725dfe39)

selects everything inside the `[]` bracket pair instead of the `""` pair.
![image](https://github.com/helix-editor/helix/assets/16740762/b0375969-93c3-4036-b3a0-ef0b58808557)

After more testing `mim` works fine for pairs like `{}`,`[]`,`()` but not for `''` (single quote pair) ,`""` (double quote pair), `~~`(tilde), ``` `` ```(back tick pair).

Using explicitly the pair character like `mi"` works as expected though.

### Platform

ubuntu 22.04

### Terminal Emulator

alacritty 0.13.2 (bb8ea18)

### Installation Method

apt

### Helix Version

helix 24.3 (2cadec0)

**Comment by pascalkuthe** [comment]
its intentioal because you are basically always between two quotes (since its not possible to figure out where `inside` and `outside` is for a quote). This can be solved by using treesitter (see https://github.com/helix-editor/helix/pull/8294) but not for plaintext files. We already have an issue about this linked in that pr so I will close this in favor of that
