### ISSUE TITLE
Python syntax highlighting missing some cases

### ISSUE THREAD

**Issue by 22ispencer** [helix-editor/helix#10585]
### Summary

I don't know if its possible or not but it appears that there are some cases in which python keywords are not highlighted. In my project i have multiple chained `"string" not in data` conditions and the `not in` is appearing as plain text, the same as a variable. I als o did a ternary to check if a value was `None` and that also was missing highlighting on `is not`. I've attached a screenshot to show what I'm referencing.

When reproducing it appears that `is not` is highlighted until the `:` is added at the end

![image](https://github.com/helix-editor/helix/assets/70439368/c0cbf6cb-28f7-4a0a-8110-327056088557)

### Reproduction Steps

1. `hx example.py`
2. type 
```python
data = ["hello", "world"]

if "goodbye" not in data:
    print("oh no!")
```
3. observe syntax highlighting

### Helix log

log file was too big (647 KB)

### Platform

Windows/Linux (WSL 2)

### Terminal Emulator

Windows Terminal

### Installation Method

pacman

### Helix Version

24.3

**Comment by 22ispencer** [comment]
[python_syntax.log](https://github.com/helix-editor/helix/files/15097133/python_syntax.log)

**Comment by benmuth** [comment]
I'm also having a Python syntax issue. I suspect it's a problem with the tree-sitter grammar, but I'll mention it here anyway.
Quotation marks around strings are broken. There's no matching cursor highlight, and the primary cursor is instead highlighted as if it's the matching cursor. Also, I can't do "Goto matching bracket". You can see in the recording that matching parens work as expected, but quotes don't. 
[![asciicast](https://asciinema.org/a/svwWxTTyPtH0RzQh6XdpusXf1.svg)](https://asciinema.org/a/svwWxTTyPtH0RzQh6XdpusXf1)

If this is an unrelated bug with Helix, I can open a separate issue.

**Comment by the10thWiz** [comment]
I'm pretty sure this is a different issue, and it seems even weirder after trying some things. My first thought was that the issue is related to fstring support, but I tried all the python string variants I could think of, and none of them worked properly. However, triple quoted strings displayed weird behavior - they do allow jumps, just only from the beginning to the end of one of the triple quotes.

    """   """
    ^ ^

The two highlighted locations are where you can jump between with goto_matching_bracket.
