### ISSUE TITLE
Enabled whitespace rendering adds extra chars into urls

### ISSUE THREAD

**Issue by l4l** [helix-editor/helix#10685]
### Summary

With enabled `editor.whitespace.render = "all"`, whitespace special chars are added to URL link.

### Reproduction Steps

I tried this:

1. run `hx`
2. set config value: `:set-option whitespace.render = "all"`
3. Add some text with http link (with language that support opening URLs), e.g for rust:

```rust
// http://example.com
//
```

4. Click on URL
5. Instead of `http://example.com` it opens `http://example.com⏎`

### Platform

Linux

### Terminal Emulator

alacritty 0.13.2 (bb8ea18e)

### Installation Method

pacman

### Helix Version

helix 24.3

**Comment by pascalkuthe** [comment]
I wouldn't classify this as a bug. We don't support any kind of "clicking" on URLs. all that `markup.link.url` does is style the highlighted text (depending on your theme but usually as somkind of blue with underline).

The fact that you can click on a link is entirely orthogonal and something that terminal some terminal emulators do by parsing the output and let you click anything that looks like a link to them.

You can click on any link in alacrity finds in our rendered output no matter whether its rendered as one by helix or not. There are many more situations where this can cause issues.

In theory we could improve support by using osc-8 but that is not possible since crossterm doesn't support that (https://github.com/crossterm-rs/crossterm/issues/602) and it wouldn't work with sotfwrapped URLs (and also not all for all URLs) so I just don't think that is worth the effort since `gf` supports opening URLs. In fact these kind of problems is why URL support was added to `gf` in the first place
