### ISSUE TITLE
`m` should work with the nearest surround pair even if the cursor is not exactly on a surround character

### ISSUE THREAD

**Issue by archseer** [helix-editor/helix#1072]
Leftover from https://github.com/helix-editor/helix/pull/961

**Comment by icholy** [comment]
An alternative would be to leave `m` as-is and add a `]*` where `*` is any character acting as a pair. So `]"` would select the next string.

**Comment by the-mikedavis** [comment]
I would prefer it work at least _like_ `m` because `m` can distinguish between around (`ma`) and inside (`mi`). Although having control over whether we seek the next `]` or previous `[` could be useful. I think we should choose one (probably "next") as a default behavior for `m` when not surrounded though for simplicity of use, even if it's a duplicate keybinding.

**Comment by icholy** [comment]
What about allowing `[` or `]` as a prefix for any `m` commands?
