### ISSUE TITLE
Using tree-sitter queries for language indents instead of TOML

### ISSUE THREAD

**Issue by kevinsjoberg** [helix-editor/helix#114]
[neovim](https://neovim.io) solves indentation using indent queries, see [Rust's indents.scm](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/rust/indents.scm) for an example. Given we're already leveraging [tree-sitter](https://tree-sitter.github.io/tree-sitter/) for syntax highlighting, wouldn't it make sense to use it for indentation as well?

A big benefit of doing so, would be the ability to re-use already written `indents.scm` queries written by the [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) project.

**Comment by archseer** [comment]
I initially tried doing that, but there's some tradeoffs:

We need to traverse the nodes from the innermost one up to the root and check whether each node is considered an indentation level. tree-sitter queries can take a range to scan, but since we go all the way up to root that usually means querying the whole document.

We're only able to get an iterator over all the matches on the [QueryCursor](https://docs.rs/tree-sitter/0.19.5/tree_sitter/struct.QueryCursor.html) so we can't traverse the tree directly in the same way we can just do it manually. [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/b5d603a876fe8c89e96a9cac2dac2dd375479dac/lua/nvim-treesitter/indent.lua#L28-L30) circumvents this by holding a map of node ids, with `true` if the node matched. However, this will include all the nodes in the document, and there might be hundreds of them! Usually we only need to traverse a couple.

I think the behavior also might not fully line up with nvim-treesitter's implementation, so while their queries are a good start they might require some tweaking.

I tried looking at the parsed [Query](https://docs.rs/tree-sitter/0.19.5/tree_sitter/struct.Query.html) itself to see whether we could pull the scopes out, but that wasn't possible.

I considered using the `.scm` syntax and just implementing a dumb parser that looks for a `[ ... ] @indent`, but I figured it would be confusing if users tried adding more complex queries and it broke.

**Comment by pickfire** [comment]
> We need to traverse the nodes from the innermost one up to the root and check whether each node is considered an indentation level. tree-sitter queries can take a range to scan, but since we go all the way up to root that usually means querying the whole document.

What are the performance implication of that. How large of a code file will it encountered an issue? Maybe it is insignificant, how much memory does it take?

**Comment by archseer** [comment]
If doing this on a large file, there will be _a lot_ of nodes. That's why `tree-sitter` exposes the iterator, so it's not rendered into memory at once. We could do some measurements though.

**Comment by pickfire** [comment]
Yeah, then we use the iterator. Will that be an issue?

**Comment by kevinsjoberg** [comment]
I think it's worth experimenting with at least. It's a major advantage being able to use the already written `indents.scm`. Perhaps some benchmarks would be in order? 🙂

**Comment by cessen** [comment]
A cheaper way to detect indentation than traversing tree-sitter is to write a bit of language-agnostic heuristic code.  In Led I do this:
https://github.com/cessen/led/blob/27572c8838a1c664ee378a19358604063881cc1d/src/editor/mod.rs#L164-L241

The basic idea is to track *differences* in leading whitespace between adjacent lines, and build a histogram of the increases (not decreases).  And you essentially just pick the most numerous item from the histogram as your indentation.

My implementation is pretty naive, and there's still a lot that can be improved about it (e.g. skipping blank lines, maybe slightly favoring more common indentations, etc.).  But it works reliably even as-is, and I've basically had zero issues with it.

At the very least, something like this as a fallback for languages that don't have a tree-sitter implementation would be nice.

**Comment by pickfire** [comment]
In kakoune https://github.com/mawww/kakoune/blob/master/rc/filetype/rust.kak#L118 is done, although it can handle most cases, there are a lot of cases still it cannot be handled, especially when the long lines are wrapped. I think a tree-sitter based approach could solve this issue.

**Comment by archseer** [comment]
Yeah I think a general purpose fallback would be useful. I've left a placeholder in the code:

https://github.com/helix-editor/helix/blob/c754df12b38595b29575e7b58911386a16ac9951/helix-core/src/indent.rs#L144-L147

**Comment by cessen** [comment]
@archseer 
> Yeah I think a general purpose fallback would be useful. I've left a placeholder in the code:

Awesome!  Mind if I take a crack at implementing that bit?  Since I already implemented it in Led, it should be pretty quick.

**Comment by cessen** [comment]
Oh, looking at the actual code, that's not what I thought it was.  I'm talking about detecting the indentation style of files on load (e.g. tabs vs spaces, and if spaces how many), which then get stored as a (user-modifiable) setting in the buffer.

Does Helix have anything like that, or is something like that planned?

**Comment by VarLad** [comment]
Any update on this?

This would be really convenient, since a lot of languages would get indent and highlight features

**Comment by archseer** [comment]
@VarLad

We already use tree-sitter queries for highlights (check `runtime/queries`) locals and injections, this issue is specifically about the indents being toml instead of scm.

I explained my reasoning above: https://github.com/helix-editor/helix/issues/114#issuecomment-855179867

Even if the queries were in .scm format they'd still be a separate set of queries from highlights.scm because they query for slightly different sets of nodes.

**Comment by kirawi** [comment]
> A cheaper way to detect indentation than traversing tree-sitter is to write a bit of language-agnostic heuristic code. In Led I do this: https://github.com/cessen/led/blob/27572c8838a1c664ee378a19358604063881cc1d/src/editor/mod.rs#L164-L241
> 
> The basic idea is to track _differences_ in leading whitespace between adjacent lines, and build a histogram of the increases (not decreases). And you essentially just pick the most numerous item from the histogram as your indentation.
> 
> My implementation is pretty naive, and there's still a lot that can be improved about it (e.g. skipping blank lines, maybe slightly favoring more common indentations, etc.). But it works reliably even as-is, and I've basically had zero issues with it.
> 
> At the very least, something like this as a fallback for languages that don't have a tree-sitter implementation would be nice.

This could probably be converted into a separate issue.

**Comment by kevinsjoberg** [comment]
@archseer I believe this can be closed, right? I don't think we will pursue this further.
