### ISSUE TITLE
clipboard provider wl-copy failed

### ISSUE THREAD

**Issue by rahji** [helix-editor/helix#11574]
### Summary

When I select some text with the mouse, I get the error `clipboard provider wl-copy failed`. I am on Windows 11, WSL2, Windows Terminal. `wl-copy` exists [only] in `/usr/bin` and works fine from the shell prompt. I swear this used to work. 🤔 Highlighting using the keyboard and doing `[space] y` *does* yank to the clipboard, at which point I can paste the yanked text in Windows.

### Reproduction Steps

Highlight text with the mouse. It immediately tries to copy to the clipboard but fails.

### Helix log

I removed the log file, edited my markdown file, yanked a line, yanked a line with space & y, then highlighted the line with my mouse. After all that, the log file contains only this line.

```
2024-08-25T12:01:47.698 helix_lsp::transport [ERROR] marksman err <- "[12:01:47 INF] <LSP Entry> Starting Marksman LSP server: {}\n"

```

### Platform

Windows WSL2

### Terminal Emulator

Windows Terminal 1.18.3181.0

### Installation Method

maybe built from source?

### Helix Version

helix 24.3 (2cadec0b)

**Comment by mandx** [comment]
Could you try running Helix with `hx -vv`? The `-vv` flag will increase the verbosity of the log file.

Something like this happened to me this morning as well, however in my case it turned out to be an environmental issue; I looked around in Helix' commit history, but recently nothing related to the clipboard has changed, and then I found out that my Ubuntu box was logging me in using XOrg instead of Wayland. It started working again when I logged out and made sure I log back in using the Wayland session.
