### ISSUE TITLE
Document the different diagnostic levels

### ISSUE THREAD

**Issue by jerabaul29** [helix-editor/helix#11592]
In https://github.com/helix-editor/helix/blob/master/book/src/editor.md , I could not find a documentation for the valid diagnostic levels; for example, in section

https://github.com/helix-editor/helix/blob/af7a1fd20c0a2915e0dae1b5bea7cb6bde6c2746/book/src/editor.md?plain=1#L399-L435

it is not clear to me, reading just this section, what values are ok to use for e.g. `cursor-line` .

**Comment by the-mikedavis** [comment]
I think we can add a paragraph below the table in this section that says that the allowed values are `"hint"`, `"info"`, `"warning"` and `"error"`. I think it would be ok to reference some other config option for `config.toml` but linking to the `languages.toml` config could be confusing. Also that section in `languages.md` is incorrect about the levels: it should be lowercase "hint"/"info"/etc. instead of "Hint"/"Info"/etc.
