### ISSUE TITLE
highlight TODO, FIXME and XXX in comments

### ISSUE THREAD

**Issue by bestouff** [helix-editor/helix#1164]
`(n)vim` highlights these keywords in comments: TODO, FIXME and XXX. It's quite useful for spotting places to work on in source code.
![image](https://user-images.githubusercontent.com/1163188/143419421-fd1e05dc-4bd1-4c47-a35f-ffa04f947b6b.png)

**Comment by sudormrfbin** [comment]
The PR to nvim-treesitter for supporting this same feature (https://github.com/nvim-treesitter/nvim-treesitter/pull/893) and `tree-sitter-comment` which backs the PR and acts as an injection to provide highlights (https://github.com/stsewd/tree-sitter-comment).

**Comment by pickfire** [comment]
I tried taking a look at this since I thought it was easy.

It works for some languages (scq, python) but didn't work for rust. But it only selects until the first word so you get a weird highlight.

![Screenshot_20211126_080051](https://user-images.githubusercontent.com/4687791/143508970-9d4dd292-d2bb-4805-8b1f-e78c2513dbbe.png)

I believe it requires some changes in helix-core syntax to allow the use of injection as an overlay so that the original parts are still highlighted with comment as a fallback, currently it seemed to only highlight the first word as comment which is the matched regex for tree-sitter-comment.

**Comment by bestouff** [comment]
This is not quite the same. In `vim` the "grammar" is simpler; AFAIK it's just those 3 words, with no parenthesis or colon afterwards.

**Comment by pickfire** [comment]
I think it's only useful in comments, what is your use case?

**Comment by bestouff** [comment]
Same same (have a look at my screenshot). I was just saying in (n)vim it's just "FIXME" not "FIXME:" or "FIXME(user):".

**Comment by sudormrfbin** [comment]
Neovim uses the same tree-sitter grammar, so it's actually supported:

![Screenshot_2021-11-28_12-14-13](https://user-images.githubusercontent.com/23398472/143732497-dbeb20b3-f0b0-4d18-a833-00539f6b961e.png)

**Comment by bestouff** [comment]
TIL, thanks

**Comment by bestouff** [comment]
Thanks all !
