### ISSUE TITLE
Pair colourization fails with ' and "

### ISSUE THREAD

**Issue by Rational-Curiosity** [helix-editor/helix#1168]
### Reproduction steps
```
"aaa ' bb ' cc" <- colorized character
          ^
        cursor
```
     
### Environment

- Platform: Linux
- Helix version: v0.5.0-145-g72f606e

<details><summary>~/.cache/helix/helix.log</summary>
no logs
</details>

**Comment by sudormrfbin** [comment]
Bracket matching (which includes `'` and `"` support already) works by checking if the edges of the tree-sitter node it's currently on has matching pairs. Since `"..."` is itself a node and anything inside it is a plain string, tree-sitter simply doesn't recognize the `'` inside to be of any special importance.

**Comment by dead10ck** [comment]
Indeed, highlighting the inner single quotes would be the wrong thing to do here, since they are just part of the contents of a string.

**Comment by pickfire** [comment]
The current behavior isn't really a bug but more of a feature. Everything inside a string should be a string and I don't see why we want to special case it unless it's injection like html within rust. I don't think we can solve this with tree-sitter alone since tree-sitter doesn't differentiate ' within ".

**Comment by archseer** [comment]
Closed since it's working as intended
