### ISSUE TITLE
Support CRLF

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#118]
It seems like it currently only supports LF. This leads to incorrect rendering and handling of CRLF text. I will be too busy to implement this functionality, sadly.

**Comment by archseer** [comment]
For editing we'd need to do something similar to Xi and [detect the proper line ending](https://github.com/xi-editor/xi-editor/blob/52bf34368e52369106d8eca6096a4839f7629e1e/rust/core-lib/src/line_ending.rs). This should happen at document load time which sets the Lf/CrLF flag on `Document`, then insertion code needs to use the appropriate `\r\n` or `\n` instead of having that hardcoded.

**Comment by archseer** [comment]
\cc @janhrastnik do you want to take this?

**Comment by archseer** [comment]
Refs #68

**Comment by janhrastnik** [comment]
> 
> 
> \cc @janhrastnik do you want to take this?

Sure, I'll give it a try.

**Comment by archseer** [comment]
For rendering: can just probably skip `\r` as zero width in a conditional here: https://github.com/helix-editor/helix/blob/5463a436a8d5647b90c7bfc54f7fc714465384fa/helix-term/src/ui/editor.rs#L180

**Comment by cessen** [comment]
My implementation of line-ending auto-detect in Led is pretty straightforward: https://github.com/cessen/led/blob/27572c8838a1c664ee378a19358604063881cc1d/src/editor/mod.rs#L88-L162

(Note that `self.buffer.text` is a `Rope` in that code.)

It just checks the line endings of the first 100 lines of the file, and selects the one that's most frequent.  And it gets the line endings by grapheme, so CRLF is accounted for.  So far I haven't encountered any issues with it, and if anything it's overkill since mixed line endings are extremely rare--you could probably just check the first line ending of the file and it would be fine.

**Comment by cessen** [comment]
> For rendering: can just probably skip `\r` as zero width in a conditional here:

Unless I'm misunderstanding the code, I think that's incorrect.

What you probably want to do is replace the `if grapheme == "\n" {` with something like `if is_line_ending(grapheme) {`, where `is_line_ending()` takes a `&str` and returns true if the grapheme is a line ending.  And for implementing `is_line_ending()`: since you know it's a valid grapheme, as long as the last char in the grapheme is a line ending, you don't need to check the second-to-last because that could only be CR from CRLF anyway.

In Led, I generally found it useful to build up a small set of utility functions like `is_line_ending()` that can be used in various places.  Here are my set:
https://github.com/cessen/led/blob/bfeaee602c1ff3e3a31a6fa1ab3ce77b1546ade1/src/string_utils.rs

(Incidentally, I have no idea why I named `str_is_whitespace()` like I did.  Probably should be `str_starts_with_whitespace()`, ha ha.  Or maybe I assumed the input there was a grapheme as well.)

**Comment by janhrastnik** [comment]
> 
> 
> My implementation of line-ending auto-detect in Led is pretty straightforward: https://github.com/cessen/led/blob/27572c8838a1c664ee378a19358604063881cc1d/src/editor/mod.rs#L88-L162
> 
> (Note that `self.buffer.text` is a `Rope` in that code.)
> 
> It just checks the line endings of the first 100 lines of the file, and selects the one that's most frequent. And it gets the line endings by grapheme, so CRLF is accounted for. So far I haven't encountered any issues with it, and if anything it's overkill since mixed line endings are extremely rare--you could probably just check the first line ending of the file and it would be fine.

Thank you, this was very insightful. I didn't even know there were so many different line endings. I've opened #224 that uses a modified version of your implementation. I'm only checking the first line for now. I doubt we have to go further than that.
