### ISSUE TITLE
Surround with multiple seletions does not work

### ISSUE THREAD

**Issue by Chandrian** [helix-editor/helix#1181]
Following the documentation and trying out the following does not work:

    % to select the whole file
    s to split the selections on a search term
    Input use and hit Enter
    mr([ to replace the parens with square brackets

Example text used in helix:
```
It can also act on multiple seletions (yay!). For example, to change every occurance of (use) to [use]:
```

It does work if there's only one selection though.

**Comment by sudormrfbin** [comment]
This is by design; it doesn't work because the surround characters around `use` are different here, `()` and `[]`. Running `mr([` will look for a `()` pair around cursors, and if it doesn't find it around _all_ cursors, no action is taken. In contrast, try the same after changing `[use]` to `(use)` (so that all occurrences of `use` have a `()` pair around them) and it will work correctly.

**Comment by Chandrian** [comment]
Thank you for the explanation! It does feels strange in the case I would like to change all the () to [] for example, having some [] already. I would suggest making it clearer in the Tutor if possible.
