### ISSUE TITLE
Read (:r) command does not properly expand ~ to mean "user's home directory"

### ISSUE THREAD

**Issue by larsks** [helix-editor/helix#12255]
### Summary

If you try to read in a file like this:

```
:r ~/some/file
```

This will result in the error:

```
path is not a file: "~/some/file"
```

Even though (a) the file exists, and (b) the path autocompletes successfully.

### Reproduction Steps

(I think the summary covers this)

### Helix log

(nothing is logged in helix.log in reponse to this failure)

### Platform

Linux

### Terminal Emulator

ptyxis

### Installation Method

source

### Helix Version

24.07-328-ge14c346e

**Comment by Aaalibaba42** [comment]
The issue is in [this line](https://github.com/helix-editor/helix/blob/master/helix-term/src/commands/typed.rs#L2510). The `PathBuf::from` function (and other methods in the std::path module) don't automatically expand the tilde to the user's home directory since it's a shell feature, and not a universal thing. The common solution is to manually expand the tilde, if present.

I'd be down to do it tomorrow, I've already got a dirty thing working. I haven't yet contributed so not sure of the protocol of it all.
