### ISSUE TITLE
Add back `goto_file_end` to the keymap

### ISSUE THREAD

**Issue by NNBnh** [helix-editor/helix#1335]
Helix currently have:

Key | Description | Command
-- | -- | --
<kbd>g</kbd> | Go to line number `<n>` else start of file | `goto_file_start`
<kbd>e</kbd> | Go to the end of the file | `goto_last_line`

But `goto_last_line` just go to the first character of the last line, not to the very end of the file. So compare to Kakoune, Helix is lacking the `goto_file_end` key.

This is a very convenient action that I miss from Kakoune, please consider add this action to Helix.

Here is [Kakoune's approach](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#goto-commands):

> ### Goto commands
>
> g, k
> go to the first line
>
> j
> go to the last line
>
> e
> go to last char of last line

**Comment by python128** [comment]
Added a key!

**Comment by sudormrfbin** [comment]
`goto_file_end` already exists and was bound to `ge` by default but it was changed in https://github.com/helix-editor/helix/issues/529 (see the issue for the reason and related discussion). I think the problem comes from desiring two different things in two different modes:

- In normal mode you probably want to jump to the beginning of last line
- In select mode you probably want to select till the last _character_ to do an operation.

Vim doesn't have this problem since `G` simply goes to the beginning of the last line, but something like `dG` deletes everything from the cursor to (including) the last line.

**Comment by NNBnh** [comment]
Great, I hope we could bind this action back to the current keymap.

**Comment by python128** [comment]
You can just add the following to config.toml:
```toml
[keys.normal]
"g" { "e" = ["goto_last_line", "goto_line_end"] }
```

**Comment by Omnikar** [comment]
> `goto_file_end` already exists and was bound to `ge` by default but it was changed in #529 (see the issue for the reason and related discussion). I think the problem comes from desiring two different things in two different modes:
> 
>     * In normal mode you probably want to jump to the beginning of last line.
> 
>     * In select mode you probably want to select till the last _character_ to do an operation.

Since things can be bound in normal and select mode, couldn't we achieve this behaviour by binding `ge` to `goto_last_line` in normal and `goto_file_end` in select? This is already achievable via configuration:
```toml
[keys.normal]
"g" = { "e" = "goto_last_line" }
[keys.select]
"g" = { "e" = "goto_file_end" }
```

**Comment by sudormrfbin** [comment]
I personally like that change, but it does make the two modes unsymmetric.

**Comment by python128** [comment]
How about we make a discussion for people who want to share their config.toml?

It would be helpful to see what ideas are implemented by the users..
