### ISSUE TITLE
append on empty line is wrong

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#1377]
to reproduce: 
1) move a cursor to empty line
2) press <kbd>a</kbd>
3) observe cursor on the **next** line
![image](https://user-images.githubusercontent.com/24528839/147394687-3bde2b1b-62d7-4217-8727-83ee8747e5c2.png)
background goes back to normal after you press <kbd>Enter</kbd>

**Comment by matoous** [comment]
This is intended behavior. In helix your cursor can be placed on the new line character which is happening in this case and after pressing `a` for append you are appending _after_ the EOL thus on new line. I brought up similar question a few days ago in the matrix chat, you can find it there for more context. I was also confused by this behavior but it makes sense in the overall design of Helix. On the other hand, I still dislike it because I usually edit text by appending `a` and it requires mental focus to switch to `i` when at the end of line. Personally I would prefer for `a` to _not_ open a new line.

The background is cursor highlight, nothing wrong there I think.

**Comment by adsick** [comment]
> The background is cursor highlight, nothing wrong there I think.
yea, but I don't get why there is so called "highlight" (because when i insert with <kbd>i</kbd> the background is clean as it should be)

**Comment by heliostatic** [comment]
I just ran into this today via `paste` onto a blank line. Very unintuitive, and inconsistent from a user perspective (even users building their terminal text editors nightly ;)

Example with a new file where I find it unintuitive:

https://user-images.githubusercontent.com/70898/151057366-55791e16-5a4d-42e9-b2a3-b01cf5a93c99.mp4

**Comment by norman784** [comment]
I also find annoying the append behaviour, in my case I'm used to create a new line explicitly if I want it with `o`. If this is the intended behaviour, at least we need an option to configure so we can say that append shouldn't create a new line.

**Comment by d12bb** [comment]
Same applies to `a`dding when cursor is at end of line:

```
some text█
some other text
# -> press `a`
some text
|some other text
```

**Comment by kennyishihara** [comment]
> > The background is cursor highlight, nothing wrong there I think.
> 
> yea, but I don't get why there is so called "highlight" (because when i insert with i the background is clean as it should be)

I also find the highlighting annoying after `a`ppend after a word. For me, it is more intuitive that the highlighting goes away when entering insert mode with `a`, just like how it is with `i`.

**Comment by wmstack** [comment]
The highlighting *doesn't* go away either after going into insert mode OR append mode. 
Before append/insert:
![image](https://user-images.githubusercontent.com/58462210/169152121-c287579f-aa61-4f2c-9eb9-ba1fe68c8206.png)
After append:
![image](https://user-images.githubusercontent.com/58462210/169152220-7348719a-0482-455f-a62d-d6040dbe0c97.png)
After insert:
![image](https://user-images.githubusercontent.com/58462210/169152317-0f8a9f09-5a11-45a1-9393-8c643d8f9f2e.png)

As you can see, the selection is still there. Definitely surprising behaviour. One more thing I want to mention. Suppose you say well, "let me collapse the selection before `append`, that should fix it right". Well, no!

After collapsing selection
![image](https://user-images.githubusercontent.com/58462210/169152598-2f3b4336-3adf-4d39-a96b-d6c194222c37.png)

Appending after collapsing the selection!
![image](https://user-images.githubusercontent.com/58462210/169152663-6e0c84f4-8232-4754-a8be-4d727d0cfe75.png)
Still doesn't get rid of the highlight.

**Comment by adsick** [comment]
will it ever be fixed?

**Comment by the-mikedavis** [comment]
As matoous says, this is intentional behavior. You're on a line-ending character so append will insert text after the line-ending - on the next line. The behavior you're looking for is most closely emulated by `A` which inserts before the line-ending character.

Whether your cursor is on a line-ending or not is more clear if you enable visible whitespace. You can do so just for newlines:

```toml
# ~/.config/helix/config.toml
[editor]
whitespace.render.newline = "all"
```

**Comment by Tarbetu** [comment]
This is cool, but this prevents me to get into Helix/Kakoune. Is there will be any setting for this behaviour?

**Comment by giganteous** [comment]
Hello all,

I'm running into this issue too because of unintuitive behaviour. I'm new to the editor as well, so I might be the stubborn one.

If i: 
* have some empty and some nonempty lines,
* add cursors on every line
* go to the end of the line (gl)
* append text (a),

... what then happens is that some text is added to the end of the current line (before newline) while on the empty lines, the text is inserted before the next line. It's not consistent, or "gl" (goto line end) is not working as I'd be understanding.

I don't want to sound unthankful, helix' editing is a very consistent experience! thanks!

**Comment by Diegovsky** [comment]
sorry to bump and old closed thread, but I wanted to ask nonetheless: would you be willing to review/accept a PR which implements behaviour such that pressing 'a' on a newline works like in vim?

Of course: this behaviour would be behind a configuration flag.
