### ISSUE TITLE
Incorrect auto pair at line ending

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#1436]
Auto paring of quotes and braces appears to break when the cursor is at the end of a line. 

The exact behaviour is not clear to me but here are some notes using braces as an example:
- the issue only occurs if the cursor is at the line ending
- if I open a new document and insert `(`, the cursor is not inside the braces
  - the result is `()▏` instead of `(▏)`
  - the braces also get added to the selection
- if I exit and re-enter insert mode the braces get completed normally but the closing brace is added to the selection

https://user-images.githubusercontent.com/3957610/148052787-729e3328-2daf-4b67-bcc9-ffaa05507977.mp4

I guess this has something to do with the line endings breaking but I don't know enough about helix' internals to be sure.

(On a side note, if I set the line endings to `lf` and then back to `crlf` helix now reports the line ending as `carriage return` instead of `crlf`.)

### Environment

- Platform: Win10 x64
- Helix version: `v0.5.0-342-gbd0d20a` compiled from source, also present in 0.6.0 github release

**Comment by CptPotato** [comment]
Looks like this behaviour started with #1254

**Comment by archseer** [comment]
\cc @dead10ck

**Comment by dead10ck** [comment]
Very strange, this must be a platform specific issue. Does this still happen if you set line endings to just lf?

**Comment by CptPotato** [comment]
> Very strange, this must be a platform specific issue. Does this still happen if you set line endings to just lf?

Yes, setting line endings to `lf` has the same effect. I'll try to reproduce it on my linux machine later.

**Comment by dead10ck** [comment]
Interesting, and setting to crlf on Linux did not reproduce for me. I'll dig into this later tonight.

**Comment by dead10ck** [comment]
@CptPotato in the meantime, would you be able to generate some debug logs for me? Could you clear any current logs you might have and then:

1. run `hx -vvv`
2. press i to enter insert mode
3. Press ( to trigger a pair
4. Press esc and `:qa!`

Then save this log by itself, clear the standard log file again and do:

1. Run `hx -vvv`
2. Press i to enter insert mode and insert a single space, then esc
3. Move cursor one to the left so it sits on the whitespace
4. Hit a to append
5. Hit ( to trigger a pair
6. Esc and `:qa!`

Then save this log by itself.

These logs will help me dig into it. Thanks!

**Comment by dead10ck** [comment]
Ah, I see the problem. It's here:

https://github.com/helix-editor/helix/blob/bd0d20a2b34f3cccd7f3ea1e988bf4b68e75d6b4/helix-core/src/auto_pairs.rs#L75-L91

We check if the selection is a single-width cursor by checking if the length of the range is 1; for CRLF, it's actually 2. So it thinks there is a multi-character selection when there is not. Strangely, for me, I did not run into the cursor advancing past the end of the paren, but I did see the selection ending up incorrect.

I think what we need to do is check if the number of *graphemes* in the range is 1 to get the correct behavior. I'll try to fix this soon.

Additionally, I noticed from @CptPotato 's logs that the range was actually in the forward direction, when it should have been backward for an insert. I confirmed that when you first open helix and immediately go to insert mode, the range is [0, 1). If you then delete anything you enter and go to insert mode again, in the same empty document, it's [1, 0) as it should be. I would expect this to lead to the behavior of extending the selection, since it's both a 2-code point line ending *and* in the forward direction. This seems like an unrelated bug.
