### ISSUE TITLE
Opening non existing file adds an extra new line at the end

### ISSUE THREAD

**Issue by wojciechkepka** [helix-editor/helix#145]
When I initially submitted #45 the rope required a new line to initialize the document properly. I just tested and empty files now contain two `\n` characters so doing just `Rope::new()` should be enough to initialize an empty document. I'm not entirely sure yet what caused this change.

**Comment by kirawi** [comment]
It's likely because of #121. I corrected the line counting there so it didn't depend on there being a `\n` character. Originally, there wouldn't be any line counting if there was an empty `Rope`, for example.  However, I think this is correct behaviour and I would advise against removing the `\n` for now as it would cause Helix to break. I'm going to follow it up with #98 to completely resolve the bug.

**Comment by kirawi** [comment]
I think this issue can be closed now.
