### ISSUE TITLE
Open URL under cursor

### ISSUE THREAD

**Issue by matoous** [helix-editor/helix#1472]
#### Describe your feature request

Add functionality similar to vim's `gx` that opens URL under cursor. I am still unsure whether this should be included with Helix or better left for a plugin (cc @archseer)?

This can be further extended to open files, commits, etc.

**Comment by archseer** [comment]
I think we should support the hyperlink spec which makes terminal links clickable: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

crossterm doesn't seem to support this, but termwiz does ([I've been hoping to switch over](https://github.com/helix-editor/helix/tree/termwiz) since it also supports bracketed paste and better render diffing): https://docs.rs/termwiz/latest/termwiz/hyperlink/index.html

Command-wise, we already support opening the file under cursor via `gf`: https://github.com/helix-editor/helix/pull/1102

So something like `gx` could be doable if we amend the detection a bit. We'd shell out to `$BROWSER`

**Comment by d12bb** [comment]
> So something like `gx` could be doable if we amend the detection a bit. We'd shell out to `$BROWSER`

Imho better than using `$BROWSER` for `gx`, which often isn't set, would be using the `open` (macOS) or `xdg-open` (Linux) commands. These are 1. using the user's default browser set in his/her desktop environment, and 2. apply to more than just websites, one could also open files, or different URL protocols (`ftp:`, `magnet:` etc). Only thing left to Helix internal would be finding begin and end of the path or URL string.

**Comment by ubitux** [comment]
> > So something like `gx` could be doable if we amend the detection a bit. We'd shell out to `$BROWSER`
> 
> Imho better than using `$BROWSER` for `gx`, which often isn't set, would be using the `open` (macOS) or `xdg-open` (Linux) commands. These are 1. using the user's default browser set in his/her desktop environment, and 2. apply to more than just websites, one could also open files, or different URL protocols (`ftp:`, `mailto:` etc). Only thing left to Helix internal would be finding begin and end of the path or URL string.

Note that the protocol might not be specified and would imply `file://` (think `![img](path/to/image)` in markdown)

**Comment by edrex** [comment]
As it stands this issue is about two subtly-different things, both of which seem worth doing: 
1. implement an internal open-url-under-cursor mechanism.
2. implement the hyperlink spec for detected URLs to support clickable terminal links

Since 2 depends on moving to / deciding about termwiz, and given 1 would make 2 much easier, maybe we should do an internal implementation first?

These are especially important now that virtual text/soft wrapping [has landed](https://github.com/helix-editor/helix/commit/4dcf1fe66ba30a78edc054780d9b65c2f826530f), which will break terminal-based regex URL detection when enabled.

**Comment by edrex** [comment]
Both implementations could benefit from LSP features such as [Document Link](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentLink).

**Comment by thisizkp** [comment]
There seems to be couple of PRs in flight for this with almost most of the required work already done. Is there anything pending that is required or waiting for (If so, would love to help/contribute) the PR to be merged?

**Comment by sdoerner** [comment]
Not sure if I'm doing something wrong, but "gf" only seems to work right locally. Trying it on an ssh connection seems to get Helix into a very weird and non-reactive state where I have to kill the process.
Anyone else experiencing this?

Tested on Alacritty with Helix 24.7.
