### ISSUE TITLE
Regression; can't visit last line of a file if it doesn't end with a newline

### ISSUE THREAD

**Issue by kevinsjoberg** [helix-editor/helix#152]
If the file doesn't end with a newline, you can't visit the last line.

**Steps to reproduce**
- `printf "abc\ndef" >| test.txt`
- `hx test.txt`

**Environment**
- helix 0.0.10
- macOS 11.13.3

**Comment by archseer** [comment]
Caused by some of the panic fixes, generally [text should always end with a newline](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) which is why we make new documents with a newline already present. I think the behavior of most editors is thar they will notice the missing newline and implicitly append it?

**Comment by kevinsjoberg** [comment]
@archseer 100% agree that files in general should end with a newline, but there will be situations where this isn't the case and I think we need to support that.

Some likely scenarios:

- Auto-generated files
- Files written by people in a text editor that doesn't automatically insert a final new line

**Comment by kirawi** [comment]
> Caused by some of the panic fixes, generally [text should always end with a newline](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) which is why we make new documents with a newline already present. I think the behavior of most editors is thar they will notice the missing newline and implicitly append it?

Considering I've never heard of this, this is my face right now: 
![image](https://user-images.githubusercontent.com/67773714/121029070-4b665c80-c776-11eb-9dfb-ae71bcc80f3e.png)
