### ISSUE TITLE
:wq silently exits without an error if target file is not writable

### ISSUE THREAD

**Issue by Pistahh** [helix-editor/helix#1575]
### Reproduction steps
:wq should fail and indicate if it couldn't save the file but it doesn't, it just exits.

1. edit a file that you have no permissions to, e.g. /etc/hosts as non-root
2. Try to save it and exit with `:wq`
3. watch as hx exits without any indication that it couldn't save the changes
4. inspect /etc/hosts that it indeed wasn't changed

 

### Environment

- Platform: Linux
- Terminal emulator: gnome terminal
- Helix version: v0.5.0-186-g371c84f

**Comment by dead10ck** [comment]
I started trying to look into this one. At first glance, it seems like this should exit with an error before quitting. However, if we look at `write_impl`, we can see that it looks like it just adds an async job and returns immediately, which would explain why it just proceeds to quit, and doesn't really care if the write succeeds or not:

https://github.com/helix-editor/helix/blob/333c2949c2b036f8aafa77be2286eb3c135ea269/helix-term/src/commands.rs#L2087-L2094

I thought it would make sense to wait on the job in between calling write and calling quit, so looking at the `Jobs` type, it looks like there is a function for waiting on all the pending jobs:

https://github.com/helix-editor/helix/blob/333c2949c2b036f8aafa77be2286eb3c135ea269/helix-term/src/job.rs#L95-L99

However, as we can see, this doesn't care about the result of the jobs either. Would it make sense to have this function return a Result that's an error if any of the pending jobs error, and Ok otherwise?

**Comment by DannyJJK** [comment]
I'd love to try this using Helix as my main editor, but this single issue makes me nervous to use it. There's various reasons a file could fail to write that are not just permissions based, I wouldn't want to think I'd saved a file successfully to find that no changes have been made. Has there been any further progress on this?

**Comment by dead10ck** [comment]
I agree, this seems rather important from a reliability perspective. I'll take a crack at the approach I mentioned above.
