### ISSUE TITLE
Fix command alias for `:buffer_close`

### ISSUE THREAD

**Issue by NNBnh** [helix-editor/helix#1594]
This is one of the convenient thing I miss from Kakoune. We could alias to `:bc`

:D

Related? #1593

**Comment by Omnikar** [comment]
`:bclose` and `:bc` aliases already exist and have existed since the addition of `:buffer-close`.

https://github.com/helix-editor/helix/blob/333c2949c2b036f8aafa77be2286eb3c135ea269/helix-term/src/commands.rs#L2837-L2843

**Comment by NNBnh** [comment]
Then this must be a bug wright? I'm using Helix 0.6 on NixOS and don't see these aliases at all...

[![asciicast](https://asciinema.org/a/464795.svg)](https://asciinema.org/a/464795)

**Comment by the-mikedavis** [comment]
I think aliases do not show up in the command picker. For me, typing `:bc<enter>` closes the buffer, but `bc` doesn't show up in the command picker.

**Comment by archseer** [comment]
This seems to have been lost because the code was split into a TYPABLE_COMMAND_LIST and a TYPABLE_COMMAND_MAP. `_MAP` contains the aliases but list doesn't: https://github.com/helix-editor/helix/blob/333c2949c2b036f8aafa77be2286eb3c135ea269/helix-term/src/commands.rs#L3140-L3149

https://github.com/helix-editor/helix/blob/333c2949c2b036f8aafa77be2286eb3c135ea269/helix-term/src/commands.rs#L3166-L3174

could probably edit that to use `TYPABLE_COMMAND_MAP.keys()` instead
