### ISSUE TITLE
autopair: delete pair on backspace

### ISSUE THREAD

**Issue by tgirod** [helix-editor/helix#1673]
When in insert mode, autopair gets triggered when a pairable character is entered. But if I press a pairable character by mistake and delete it using backspace, the closing pair is not deleted.

I think it would make more sense to automatically delete the closing character in that situation.

**Comment by sudormrfbin** [comment]
There's an open PR: https://github.com/helix-editor/helix/pull/1379.

**Comment by tgirod** [comment]
good to know, thanks!

**Comment by MonAaraj** [comment]
This should not be closed, should it? Since the issue hasn't been solved yet. It's good to keep it open for people who run into this issue and see no open issues for it, then attempting to make one for it (like me just now). Sorry for the off-topic comment. And also, +1, I guess, since I am commenting on this anyways.
