### ISSUE TITLE
Multiple Cursors Tutorial

### ISSUE THREAD

**Issue by VasilyFomin** [helix-editor/helix#1780]
### Reproduction steps
Launch helix tutorial:
```
hx --tutor
```
 

### Environment

- Platform: macOS
- Terminal emulator: iTerm
- Helix version: latest from Homebrew

Tutorial says:
> Type C to duplicate the cursor
> Type , to remove the second cursor 

Pressing `,` deletes the first cursor, actually it deletes all of cursors, except for the last one. Not sure what should be the proper behavior here (probably remove all cursors, except the first one), but if I do `x` and then `s` to select multiple words on the line pressing `,` removes all cursors except the first one.

**Comment by Omnikar** [comment]
Removing all extra cursors is the intended behaviour of `,`. Which cursors get removed and which remains is determined by which of your cursors is the "primary" cursor. Some of the default themes come with theming for the primary cursor that's different from the rest of the cursors so that you can actually see which is the primary cursor, but not all the themes do. You can add your own colour for the primary cursor/its selection by adding colours for `ui.cursor.primary` and/or `ui.selection.primary` in your theme file.
