### ISSUE TITLE
Autocomplete for directory members

### ISSUE THREAD

**Issue by nekodjin** [helix-editor/helix#1801]
Let's say I have a project with the following structure:
```
Cargo.toml
src
 | main.rs
 | thing_a.rs
 | thing_b.rs
LICENSE
README.md
```

If I've got neovim open, and I begin typing the command `:e s` and hit tab, it will autocomplete to `:e src/`. Since what I entered was unambiguous (id est there are no other alternatives to cycle through), I can then hit tab again to cycle through `:e src/main.rs`, `:e src/thing_a.rs`, and `:e src/thing_b.rs`. Such functionality seems to be lacking in Helix, and I'd rather like it.

**Comment by nekodjin** [comment]
More specifically, if I fully type out `:o src/` in Helix, then yes, I can cycle through `src/{main,thing_a,thing_b}.rs`. But if I've autocompleted from `:o s` to get to `:o src/`, there's no way for me to do the same thing, unless I for example type some extraneous letter and delete it, so that Helix is convinced I've typed out `:o src/` all by myself.

**Comment by zen3ger** [comment]
While looking into this, I've found that this behavior is actually covered in more general way. 

If the selected completion ends with a path separator then pressing enter will give you the completion for the directory content. I think this is sensible since `:open` won't open directories unlike nvim's `:edit`.

Anyhow, if people think it would be still nice to have it, I have both nvim-like and kak-like directory-tab completion patches.
- nvim-like : double tab required to advance and list directory content (`:o s` + <kbd>Tab</kbd> + <kbd>Tab</kbd>)
- kak-like : on single completion match tab instantly lists directory content (`:o s` + <kbd>Tab</kbd>)

I personally like the kak-like single-tab drill-down approach:
![hx-directory-completion](https://user-images.githubusercontent.com/5622624/160710716-7de6ce76-f7e1-4126-9b6c-fbda7c06e2ca.gif)

**Comment by zen3ger** [comment]
Also, I ended up in situations with directory tab-completion that I went too far when there's a lot of empty directories and I need to create a new file... In e.g. doom-emacs and kakoune <kbd>Ctrl</kbd>+<kbd>w</kbd> will only delete the path back until the path separator on the prompt so it's fast to climb back, but helix wipes the entire path. 

Would it be valuable to add e.g. <kbd>Ctrl</kbd>+<kbd>Tab</kbd> to wipe a path segment from the completion or maybe update <kbd>Ctrl</kbd>+<kbd>w</kbd> handling instead?

**Comment by sudormrfbin** [comment]
`ctrl+w` to delete upto path segment seems like a good idea, I've been tripped up by it occasionally in the past.
