### ISSUE TITLE
nickel: language support (lsp, tree-siiter)

### ISSUE THREAD

**Issue by colemickens** [helix-editor/helix#1809]
#### Describe your feature request

Hi! Nickel is starting to gain some attention. It would be neat to have support for it in Helix. I haven't looked into this a ton yet, but nickel ships with it's own LSP server, but I opened an issue about a tree-sitter grammar: https://github.com/tweag/nickel/issues/656

I'm not sure if it's possible or makes sense to add support with a tree-sitter grammar?

**Comment by the-mikedavis** [comment]
Nickel looks pretty cool. They might be able to draw some inspiration from [tree-sitter-nix](https://github.com/cstrahan/tree-sitter-nix) given the similarities in syntax.

Iirc there was some discussion a while back about adding an alternative for syntax highlights that would be simpler to write than a tree-sitter grammar, but in the end I think we prefer to support only tree-sitter since it is possible to build other features on top of it (indents, textobjects, `Alt+j/k/h/l` motions, eventually folds), and tree-sitter is quite performant compared to some regex-based systems.
