### ISSUE TITLE
Generate tree-sitter parsers if they don't exist in git repo

### ISSUE THREAD

**Issue by slinlee** [helix-editor/helix#1859]
> The problem is that the grammar .gitignores the src/ directory (see [here](https://github.com/JoranHonig/tree-sitter-solidity/blob/5585e0739a248137d9561d835a915efb2db5ac3d/.gitignore#L7)). Helix's build process for grammars currently requires the generated `src/` directory which is all the C/C++ files you need to compile the parser.

_Originally posted by @the-mikedavis in https://github.com/helix-editor/helix/issues/1853#issuecomment-1074553414_

**Comment by the-mikedavis** [comment]
https://github.com/tree-sitter/tree-sitter/issues/1641 has some info on how nvim-treesitter deals with grammars. They have a system simliar to ours where the repositories are cloned and in some cases, the `src` files get generated by calling out to `tree-sitter` and sometimes even `npm`. I've been thiking about how to solve some of those issues and I think a central registry which packages the generated `src` directories is a reasonable increment, so that's what I've been tinkering with in [helix-editor/tspm](https://github.com/helix-editor/tspm). The idea there is that you can package the grammars into a minimal and reproducible tarball with a uniform structure, so all of the packaging concerns like getting dependencies (submodules, npm, etc.), generating the `src` files and specifying the ABI live in TSPM instead of editors / tree-sitter consumers. Then consumers download and extract the tarball and compile the C files.

That doesn't solve all of the issues there (in particular around safety), but I think it's a good middle-ground between the current state and the ideal eventual state (see the "Native Library, WASM parsers" part of https://github.com/tree-sitter/tree-sitter/issues/930).

**Comment by the-mikedavis** [comment]
We could do this either by embedding tree-sitter-cli or shelling out to it. I think both options are less favorable to me than #1970, though, so closing out in favor of that.
