### ISSUE TITLE
I get no syntax highlighting

### ISSUE THREAD

**Issue by lucypero** [helix-editor/helix#2123]
I ran all these commands

```
git clone https://github.com/helix-editor/helix
cd helix
cargo install --path helix-term
hx --grammar fetch
hx --grammar build
```

I tried a C++ and a Rust project. The LSP's work well. But I get no syntax highlighting. It's all white. What should I do?

**Comment by lucypero** [comment]
everything is an 'X' on the "highlight" column on `hx --health`

**Comment by the-mikedavis** [comment]
Did you link the runtime directory?

https://github.com/helix-editor/helix/blob/450f348925ff1a2a39b73481f61af6fc7e57ebef/README.md?plain=1#L48-L50

**Comment by lucypero** [comment]
> Did you link the runtime directory?
> 
> https://github.com/helix-editor/helix/blob/450f348925ff1a2a39b73481f61af6fc7e57ebef/README.md?plain=1#L48-L50

oh. my mistake. it works now. Thank you.

**Comment by cdecompilador** [comment]
Creating a new runtime directory and doing the `hx --grammar fetch`, `hx --grammar build` does not seem to work for me, is it mandatory to link?

**Comment by the-mikedavis** [comment]
If you create a new directory it won't have the query files from `runtime/queries` which are also needed for syntax highlighting. Copying the `runtime/` directory here to `~/.config/helix/runtime` and then running `hx --grammar fetch` and `hx --grammar build` should work but a link is preferred because it allows you to keep the runtime files up to date if you update the clone

**Comment by cdecompilador** [comment]
Yeah I was missing the `runtime/queries`, thanks
