### ISSUE TITLE
Use theme but custom the font size

### ISSUE THREAD

**Issue by qiankunxienb** [helix-editor/helix#2275]
#### Describe your feature request

I have used the theme "bogster", but the font size is too small. How can I make font bigger but still use this theme?

**Comment by the-mikedavis** [comment]
The terminal you're using will control your font size rather than Helix. For example in Kitty this can be controlled with the [`font_size` setting](https://sw.kovidgoyal.net/kitty/conf/?highlight=font%20size#fonts) or changed dynamically with <kbd>Ctrl</kbd><kbd>+</kbd> / <kbd>Ctrl</kbd><kbd>-</kbd>

**Comment by qiankunxienb** [comment]
thanks.
