### ISSUE TITLE
Auto close matching pair feature causes corruption with nested quotes (edge case)

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2400]
### Summary

When multiple cursors are active around a string with nested quotes and you change the quote characters, the auto-close matching pair feature results in corrupted code.

### Reproduction Steps

```
const a = 'hello "there"'
```

1. Select opening single quote <kbd>/</kbd><kbd>'</kbd> <kbd>return</kbd>
2. Extend selection <kbd>v</kbd>
3. Select next single quote <kbd>n</kbd>
4. Change the quotes <kbd>c</kbd>
5. Enter backtick <kbd>`</kbd>

## What should happen

The two single quotes should be replaced by backticks:

```
const a = `hello "there"`
```

## What actually happens

The two quotes are replaced by backticks __and an additional backtick is added to the end__:

```
const a = `hello "there"``
```

### Helix log

n/a

### Platform

Linux

### Terminal Emulator

GNOME Terminal

### Helix Version

helix 22.05-dev (3a398eec)

**Comment by archseer** [comment]
@dead10ck maybe? I think it falls under auto-pairs

**Comment by dead10ck** [comment]
Sorry to be this person, but... this doesn't seem like a bug to me? You have a case where there are two independent cursors in insert mode, so each are going to insert their own auto pairs. The first cursor does not in this case because it happens to precede an alpha character.

I think what you want here is <code>mc'\`</code> or even just <code>r\`</code>

**Comment by archseer** [comment]
Ah yep,  `` r` `` is what I'd suggest
