### ISSUE TITLE
No new dependencies detected (rust-analyzer)

### ISSUE THREAD

**Issue by axdank** [helix-editor/helix#2479]
**I don't know how exactly to define the title.**
When I open a rust workspace, everything goes fine, libraries and all are loaded, but when I add a new dependency inside Cargo.toml of a crate and try to use it in some file, it is not found or not available, I think that when I modify the Cargo.toml file, rust-analyzer does not verify the change and downloads the missing dependencies, the only way to make it appear is closing and reopening helix. In the case of vscode, as an example, when you add a new dependency, rust-analyzer verifies it and lets you use it in any file.

**In helix:**
![image](https://user-images.githubusercontent.com/55039048/168498079-c0c82bfc-81c1-455e-8cff-950399de747a.png)
![image](https://user-images.githubusercontent.com/55039048/168498099-df717c15-6cb4-4cc4-8af1-2856f93cc759.png)

**In vscode:**
![image](https://user-images.githubusercontent.com/55039048/168498236-5c93d86d-24d9-40ad-9f68-c5e2bfda8f99.png)
![image](https://user-images.githubusercontent.com/55039048/168498217-4a1a18f5-03c5-4082-bd26-c2cf4e75588d.png)
![image](https://user-images.githubusercontent.com/55039048/168498260-c19be712-3181-473e-9aa5-0fc2b72c5e77.png)

**Comment by pickfire** [comment]
Not very familiar with the lsp side but I think maybe we are missing some events to send to language server? So I just mark this as enhancement.

**Comment by kyrime** [comment]
I've looked into this a bit and it seems the LSP spec expects the client (us) to support its [DidChangeWatchedFiles](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles) notification, and rust-analyzer expects to receive these file-watching notifications from us to inform it when `Cargo.toml` changes. The LSP spec states that it is allowed for servers to implement file-watching themselves, but not recommended for various reasons it lists.

rust-analyzer's `rust-analyzer.files.watcher` option allows changing the file-watching implementation from `client` -- relying on events from us -- to an internal `notify` implementation, but this does not appear to have the desired functionality. At least, I've tried changing this setting to `notify` in both helix and VSCode: helix continues to not detect dependency changes and VSCode ceases detecting dependency changes. So that seems to be a no-go, unless I'm missing something.

Seems we'll need to drag in a dependency like [`notify`](https://docs.rs/notify/latest/notify/) to support the `DidChangeWatchedFiles` notification. Not sure if we already have something for file-watching. Does that sound acceptable, and would that be the preferred dependency to use?

**Comment by the-mikedavis** [comment]
There is some prior work for file watching for the purposes of reloading https://github.com/helix-editor/helix/pull/588 which pulls in the notify crate. That PR is using the v5 branch: https://github.com/helix-editor/helix/pull/588#discussion_r691701379

**Comment by kyrime** [comment]
Good to know!

I see that PR's been inactive for quite a while, and given that it does have file-watching functionality already, I'm not sure what the right thing to do would be. PR with similar watcher code, or something else?

**Comment by the-mikedavis** [comment]
Yeah, I think you could either use it as a guide or even rebase the branch if the conflicts aren't too bad and work off of it if you'd like. I'm not sure what needs to be done on that to be mergeable but since it's been inactive for a while, a PR that supersedes it would definitely be welcome. Or you could just take the parts that would be needed for this feature if you're mostly interested on working on this issue rather than https://github.com/helix-editor/helix/issues/1125

**Comment by paholg** [comment]
I think file watching is not needed for this; I suspect there is a bug in completions only. Maybe a cache that needs to be busted?

If I have the files

`src/main.rs`:
```rust
use serde::Serialize;
fn main() {}
```
`Cargo.toml`:
```toml
[package]
name = "foo"
version = "0.1.0"

[dependencies]
```

Then helix will show an error; a `cargo add serde` and then `:w` in the editor, and it will no longer show an error for the import, but will not autocomplete `use serde::` or such.
