### ISSUE TITLE
Greater than 99999 line file doesn't resize line number width

### ISSUE THREAD

**Issue by dalanmiller** [helix-editor/helix#2583]
### Summary

When viewing a file that has more than 99,999 lines, anything more than the left five digits is squelched.

E.g. my `/etc/hosts` file.
<img width="336" alt="Screen Shot 2022-05-27 at 11 19 55 pm" src="https://user-images.githubusercontent.com/863286/170707280-d546035c-a4e8-4111-b2fe-3259601284c6.png">
 
This gets quite confusing when viewing lines much higher:

<img width="260" alt="Screen Shot 2022-05-27 at 9 35 48 pm" src="https://user-images.githubusercontent.com/863286/170708183-92181b4c-9580-4e02-87e1-fa12fd47d0c5.png">

### Reproduction Steps

Download this file:

[100001.txt](https://github.com/helix-editor/helix/files/8786922/100001.txt)

`:100001` and observe the line numbers being truncated. 

### Helix log

Probably not necessary? I didn't see any issues related.

### Platform

macOS

### Terminal Emulator

iterm2

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by the-mikedavis** [comment]
The line number gutter has a fixed, constant width currently: https://github.com/helix-editor/helix/blob/efae76160d19ebba2bba31ecd5c104374c7b4483/helix-view/src/view.rs#L104

Some ways to go about fixing this:

* make the fixed-width configurable instead of a constant
* make the width dynamic based on the line numbers within view or the maximum line number of the buffer

**Comment by EpocSquadron** [comment]
I vote for the second, within buffer. Would save some space in smaller files. However I wonder if we keep the limit but cut off the beginning digits with an ellipsis character to avoid going nuts with space usage in massive files.

**Comment by archseer** [comment]
Resolved by https://github.com/helix-editor/helix/issues/2583
