### ISSUE TITLE
enter <a> in normal mode will make the character in the cursor and the later input highlighted

### ISSUE THREAD

**Issue by hzb-ykpcx** [helix-editor/helix#2673]
enter <a> will highlight the character in the cursor and the later input like they are selected.

**Comment by n0s4** [comment]
I believe this is expected behaviour since you are appending to the selection, just moving to the right and inserting with `i` does not highlight.

**Comment by hzb-ykpcx** [comment]
> I believe this is expected behaviour since you are appending to the selection, just moving to the right and inserting with `i` does not highlight.

It seems to me that <a> is just another insert operation and there should be no highlight or selection afterwards. Also,  if the highlight is expected, I guess enter <A> should highlight the while line to keep consistency, which is not the case.

**Comment by the-mikedavis** [comment]
This is expected behavior. Appending (`a`) extends the selection. It's useful when working with multiple selections.

`A` currently behaves as `glli`. It behaves the same in Kakoune but it might be more intuitive if it were to append at line end like `gla`. Including the part of the line jumped over to get to the end in the selection might be a good select-mdoe behavior for `A`.

**Comment by eailfly** [comment]
I'm confuse about this too.
From my thought, `i` and `a` should behavior just same except different direction, if we say the `a` extends the selection and useful for multiple selections, isn't that `i` should be same too? after all, people don't just 'append' selection, they insert before selection sometimes too.

**Comment by 6lj6** [comment]
> but it might be more intuitive if it were to append at line end like `gla`

Yeah, why not correct it!
