### ISSUE TITLE
Insert parentheses on function autocompletion.

### ISSUE THREAD

**Issue by n0s4** [helix-editor/helix#2678]
Helix seems to have a rough idea of the kind of item you're autocompleting, looking at the annotations at the right of the menu, so why can't it autocomplete parentheses for functions? I don't mean autofilling parameters, although that could be introduced after snippet support.

I know some languages (e.g Haskell) don't need/accept parentheses around parameters but maybe the LS be queried for that? Worst case scenario we could set it as configurable for now but I think most people would benefit from it.

**Comment by the-mikedavis** [comment]
Since it's language specific whether parentheses are contextually valid, necessary or the right character for a function, this behavior would have to live in any language's language server. A Language server could choose to provide the extra parentheses but I don't think it's a good idea because it can affect how a client might trigger features like auto-pairs or signature-help. I think it's best to solve this with snippet support which won't suffer from at least the auto-pairs problem.

**Comment by pascalkuthe** [comment]
Most lsps sends paranthesis as snippets which we support now. Doing this ourself doesn't make sense since we dont have the necessary language söecific information so closing as complete.
