### ISSUE TITLE
3J doesn't join all 3 lines as tutor says

### ISSUE THREAD

**Issue by DuckDuckWhale** [helix-editor/helix#2679]
### Summary

`3J` works the same as `J`.

### Reproduction Steps

I tried this:

1. `hx --tutor`
2. Press `627gg3J`

I expected this to happen:

Either the tutor don't say to use `3J` (because it's not selection & action any more) or all 3 lines are joined.

Instead, this happened:

The tutor says to use `3J` and only one line is joined.

### Platform

Ubuntu 22.04

### Terminal Emulator

GNOME Terminal 3.44.0 for GNOME 42

### Helix Version

22.05-33-g0035c29f

**Comment by the-mikedavis** [comment]
I think this should just be fixed in the tutor. The current behavior of `J` with a count matches kakoune's `A-j`, plus `3xJ` is fits the select-then-act paradigm better than `3J`

Would you like to submit a PR to update the tutor? https://github.com/helix-editor/helix/blob/0035c29fc16f6c795257e241fddd9f2178bc4b4c/runtime/tutor.txt#L624

**Comment by DuckDuckWhale** [comment]
Seem to be fixed in #2716
