### ISSUE TITLE
Command line argument to open split

### ISSUE THREAD

**Issue by kaleidawave** [helix-editor/helix#2709]
#### Describe your feature request

Currently running `hx file1.txt file2.txt` will open helix with file1.txt present and file2.txt in the buffers

It would be cool if there was a command line option passed in as `--split` which would open the files in a split view. 

One difficulty would be the direction to split. Should helix pick a *layout* or should the user specify how the views should be split?

**Comment by snowmang1** [comment]
I would like to work on this but I am unsure of where to begin. I have been looking around in the helix-term dir where the call to "hsplit" is made on line 467 and trying to trace back to what is actually going on. I have become lost and possibly have an incorrect understanding of what is actually happening under the hood of helix.

**Comment by plexom** [comment]
What about passing in either `--vsplit` or `--hsplit` as an argument, in order to tell the program in what way to open the listed files? So, if the user were to pass in `--vsplit`, for instance, all listed files would be opened vertically next to each other. Of course we would have to handle the case that the user passes in both arguments at the same time, but that wouldn't be too difficult.

**Comment by kaleidawave** [comment]
Yes this sounds good. And `--vsplit` and `--hsplit` would be mutually exclusive

**Comment by pascalkuthe** [comment]
Closed by  #2773
