### ISSUE TITLE
Suggestion: use `<space>` to scroll in view mode

### ISSUE THREAD

**Issue by benjaminrich** [helix-editor/helix#2721]
One thing that's always bugged me is that while `h`, `j`, `k`, `l` are so ergonomic, `<c-f>`, `<c-b>` and `<c-d>`, `<c-u>` are just the opposite; they feel characteristically "un-modal", and I've never understood why I should want to use them.

It's pretty ubiquitous in pagers, viewers and even web browsers to use `<space>` and `<s-space>` to scroll forwards and backwards page-wise, and this is very comfortable. Now, obviously `<space>` has a different usage in normal mode, but in view mode (and in particular 'sticky' view mode) it could be used for scrolling. That would give you the best of both worlds, it seems.

**Comment by the-mikedavis** [comment]
I think this is a good idea. If you'd like to submit a PR, the default keymap for `Z` lives here: https://github.com/helix-editor/helix/blob/0b8a00ac967f4fd0608d83e2804bb6b1a8bf9c5d/helix-term/src/keymap/default.rs#L274-L285

You could bind `space` to `page_down` or maybe `half_page_down` might be smoother. I'm not sure it's possible to bind `S-space` because of either terminal or crossterm limitations. Using the `event-read` example from crossterm:

```
Event: Key(KeyEvent { code: Char(' '), modifiers: NONE })
Event: Key(KeyEvent { code: Char(' '), modifiers: NONE })
```

both space and shift+space register as just space.

**Comment by benjaminrich** [comment]
I will try. Please give me a bit of time, as I have not contributed before. Thanks.

**Comment by benjaminrich** [comment]
Sorry for the naive question, because I am not a real dev and have never worked with rust before, but if I make a change to the code base and want to test it, what do I do? I mean, what are the commands to compile and run my modified version of the code?

**Comment by the-mikedavis** [comment]
Finally a key combination that works on Windows and not Linux 😄

For me the shift modified isn't being recognized on either Kitty or WezTerm

**Comment by benjaminrich** [comment]
Yes. It would be quite a useful key combination, but you cannot rely on it.
