### ISSUE TITLE
Typo in the tutor?

### ISSUE THREAD

**Issue by BearOve** [helix-editor/helix#2725]
### Summary

In the chapter 3 recap in the tutor it says `Type C to copy the selection on the line below and Alt-C for above.`

This does not sound correct to me. Which selection is it talking about? Would it be more correct to say `Type C to duplicate the cursor to the line below and Alt-C for above.`?

I would fix this myself, but just in case it actually isn't a typo I created this issue instead.

### Reproduction Steps

hx --tutor

### Platform

All

### Terminal Emulator

All

### Helix Version

22.05-46-ge0532771

**Comment by n0s4** [comment]
> Which selection is it talking about?

I think "selection" is more appropriate than "cursor" since the selection may be more than one character wide. In Helix the cursor is really just a 1 char selection.

The part I'd say is incorrect is the "line below/above" since it doesn't always copy to the next line if the selection cannot fit in it. My suggestion would be something like:

> Type C to copy the selection below and A-c to copy above.

We could also add a note about it copying to the next line *"that is long enough to fit it"*.

**Comment by BearOve** [comment]
I think I start to grasp the sentence now. "selection" is what is under the current cursor, while I misunderstood it to talk about below and above.

How about

> Type C to copy the current selection to below and A-C to copy it above.
>
> Note: The cursor is a one character selection
> Note: The operation will pick the first line that is long enough to fit the selection.

At least this would have made me personally understand it like I do now 🙂

**Comment by BearOve** [comment]
I know, but somehow I forgot, so it might be worth repeating every now and again 😉.

I will re-read the entire section with new eyes and see if I can integrate this later. On my phone now.
