### ISSUE TITLE
JSON format is not working for buffer which havn't saved

### ISSUE THREAD

**Issue by kkzhang** [helix-editor/helix#2764]
### Summary

If .json file is opend, then :fmt works. But when hx is run without file, :fmt is not working.
(btw: hx --health shows that json lsp is installed)

### Reproduction Steps

 

I tried this:

1. `hx`
2. `:lang json`
3. input `{"test":1}`
4. `:fmt`

I expected this to happen:

```json
{
  "test": 1
}
```

Instead, this happened:

nothing happend.

### Helix log

no log produced.

### Platform

Windows

### Terminal Emulator

what is this?

### Helix Version

helix 22.05 (27609f50)

**Comment by the-mikedavis** [comment]
We don't spawn language servers for scratch buffers: https://github.com/helix-editor/helix/blob/d7bd4416754fb4e3051c3ceedd5fd525b0361ef8/helix-view/src/editor.rs#L584-L585

IIRC because language servers expect any buffers to be backed by a URI and scratch buffers are only in-memory until saved.

As a workaround for this case, you can `hx f.json`, add the json, then `:fmt`.
