### ISSUE TITLE
Publish to Scoop & Chocolatey

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#277]
- [x] [Scoop](https://github.com/lukesampson/scoop)
[Main Bucket](https://github.com/ScoopInstaller/Main)

- [x] [Chocolatey](https://chocolatey.org/)
[Packages](https://community.chocolatey.org/packages)

~- [ ] [winget](https://github.com/microsoft/winget-cli)
[Packages](https://github.com/microsoft/winget-pkgs)~ (At this time installers must either be MSIX, MSI or .exe application installers.)

**Comment by archseer** [comment]
@jrhawley sorry to ping you like this, but I've noticed you have a [Scoop definition for Helix](https://github.com/jrhawley/scoop-bucket/blob/main/helix.json) :) Would you be willing to upstream it to the main bucket?

**Comment by jrhawley** [comment]
Hey @archseer, I'd be happy to help. I adapted my manifest from my personal Scoop bucket and formatted it to fit the main bucket's format. I've submitted a pull request, so hopefully we'll hear back soon about whether it can be merged.

**Comment by kirawi** [comment]
I'll be trying to get it onto winget and chocolatey in the next few days.

**Comment by archseer** [comment]
@jrhawley Thanks for submitting the Scoop definition, much appreciated! 🎉 (Let us know if you have any feedback on helix, I know there's still some CRLF bugs lurking)

**Comment by jharrilim** [comment]
Heya, I saw the help wanted tag on this so I gave it a shot. Here's the repo that I've created that has the chocolatey package:
https://github.com/jharrilim/chocolatey-packages

And it is currently under review here on chocolatey:
https://community.chocolatey.org/packages/helix/0.6.0

Admittedly, this is my first time ever actually dealing with Chocolatey and AppVeyor, so I'm not entirely sure what to expect during the package review process. I did give it a run locally though and things seemed to work out! The CI did not run a build for 0.6.0 because I had already pushed one up by running the `update_all.ps1` script.

I'm not sure if others will be able to run this _yet_ since the package is pending review, but `choco install helix --version=0.6.0` installs correctly, and `choco uninstall helix` uninstalls correctly too.

Here's a little screenshot for some hype:

![image](https://user-images.githubusercontent.com/19535809/156905445-cb4f0afd-7ed2-468e-bbc2-aeb3af82ff6d.png)

**Comment by kirawi** [comment]
It looks like chocolatey reviewed with some comments: https://community.chocolatey.org/packages/helix/0.6.0

> A couple of things we need you to confirm and/or update before we can approve this package.
>
> 1. Can you confirm that you are the author of the software this package is created for?
If not, please update the authors field to be the authors of the software, and the owners field to be either your username or name.
> 2. You use the url argument, but you do not set anything in the checksum argument. Please update the checksum argument to have the correct checksum, and add a checksumType with the correct algorithm.

**Comment by kirawi** [comment]
Chocolatey approved it, so it just needs to be updated;
