### ISSUE TITLE
Traditional regex syntax highlighting for fallback

### ISSUE THREAD

**Issue by namespace-miata** [helix-editor/helix#2799]
There are certain langauges that dont have a language server or tree sitter, and might not really benefit a ton to have one. I good example is .conf files that are really just key-value. For these cases, I think it would be helpful to have a fallback system for just simple text edits. For me this would make helix a daily driver. My idea was to use a viml parser to somehow extract the highlighting from vim syntax files, but maybe there are certain design or philosophy reasons not to do that. In my eyes the advantage to that is no one needs to write and maintain these syntax files for what is really a backup anyhow. With vim's syntax files there would be probably the biggest collection of these files with no work writing them needed. As for the feature itself, I would be willing to work on it myself but I might need some hand holding because I am a newbie at rust and not sure what section of helix and what apis would be needed for this feature.

**Comment by the-mikedavis** [comment]
I can't gauge exactly how much work it would take to add a regex-based fallback but I don't think it's trivial at all. I would say it isn't worth it to add a regex fallback for a few reasons:

* tree-sitter provides more than just syntax-highlighting: textobjects, pair matching, syntax-tree based motions, and maybe in the future folds and tags
* tree-sitter tends to outperform regex syntax highlighting by a wide margin because of incremental parsing
* the simpler the syntax, the easier it is to write a grammar: a key-value grammar like what you describe wouldn't be more than a handful a lines

**Comment by namespace-miata** [comment]
I can understand those advantages, but how can we approach some of the more obscure filetypes? Writing 600+ treesitter queries to rival vim's library just doesn't seem practical (not that my idea is necessarily more practical)

**Comment by archseer** [comment]
Vim's library is nothing compared to tmBundle grammars used by lots of editors though. We most certainly won't support vim grammars, it would mean both comprehending vimscript and vim's custom/non-standard regexes.

There were previous discussions about supporting tmBundles via syntect but I'd rather contribute to the tree-sitter ecosystem and define a proper grammar. It's marginally more time than a regex grammar and it will give you a lot better integration since most helix features leverage tree-sitter.

**Comment by namespace-miata** [comment]
Ok so I would then ask if you could point me in the right direction for how to write grammars. I tried looking at Kakoune and Vim's syntax files because there was one or two I wanted to add to kakoune, but I found it ultimately not very clear, so if you or someone else could show me where to get started (and I know, RTFM) then maybe I'll try to start tackling the highlighting related issues.

**Comment by the-mikedavis** [comment]
Tree-sitter itself has some nice docs: https://tree-sitter.github.io/tree-sitter/creating-parsers

This gist is also good: https://gist.github.com/Aerijo/df27228d70c633e088b0591b8857eeef

**Comment by namespace-miata** [comment]
Alright, I'll look at those and close this issue for now
