### ISSUE TITLE
`xvk` is inconsistent with `xjk`

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#2822]
### Summary

`xvj` selects the **entire** first line, puts in visual mode(I know same can
be done with `xx`) but `xvk` doesn't select the entire first line, instead just selects the first character
on that line and then starts selecting entire lines upwards.

TLDR;
`xvk` is inconsistent with `xjk`

### Platform

linux

### Terminal Emulator

alacritty

### Helix Version

helix 22.05-dev (595213ca)

**Comment by EpocSquadron** [comment]
I think this is consistent with how j and k work outside of visual mode. You may be interested in adding the `extend_line_above` action to your keybind. It's not bound by default. See #2117

**Comment by the-mikedavis** [comment]
This is the intended behavior of `extend_line_up` (`vk`) and `extend_line_down` (`vj`). It's based on the head and anchor of the selection. (`#[|]#` denotes a selection with `|` being the head (cursor)).

```
foo
b#[|a]#r
baz
```

`x` moves to

```
foo
#[bar|]#
baz
```

(note the head is on the newline and the anchor is before `b`). `vj` retains the anchor and extends the head a line down:

```
foo
#[bar
baz|]#
```

Consistently, `vk` **retains the anchor** and extends the head up a line:

```
foo#[|
]#bar
baz
```

In order to have them behave as you expect, you need to swap the head and anchor of your selection with `A-;` (<kbd>Alt</kbd><kbd>;</kbd>).
