### ISSUE TITLE
Unexpected behavior because of newline characters being selectable

### ISSUE THREAD

**Issue by Nughm3** [helix-editor/helix#2956]
### Summary

This is a small nitpick I have with Helix, coming from Neovim. Helix counts the last newline character `\n` as a selectable character.

Helix:
![image](https://user-images.githubusercontent.com/83223650/177134267-a5fe8c18-26e2-4692-9a9a-796ba1af22e3.png)

Neovim:
![image](https://user-images.githubusercontent.com/83223650/177134315-3f91ae4a-6f3a-412a-a7f3-b763cf9adbf4.png)

As seen above, the last character you can select in Neovim is the semicolon, but in Helix you can select the newline. This causes some keys, such as `a` or `xc` to work differently than I would expect. **See "reproduction steps" below.**

I recognize that this issue is a bit opinionated. If this is behavior is intentional, I'd like to know why. Thanks!

### Case 1
![image](https://user-images.githubusercontent.com/83223650/177134267-a5fe8c18-26e2-4692-9a9a-796ba1af22e3.png)
After pressing `a`, Helix recognizes that the next character after `\n` is the `}` on the next line, and inserts there instead.
![image](https://user-images.githubusercontent.com/83223650/177135036-e722e09c-562b-449f-979b-bac084bc0eb1.png)
Normally, I would intend to append text at the end of line 2 instead of inserting at the start of line 3. This always annoys me, as I would have to go back up or just use `A` instead, whereas in other editors like Neovim I'm used to it appending text at the end of the line.

### Case 2
I often find myself having to change the whole line. In Vim this would be `cc`, and in Helix it intuitively should be `xc`. 
![image](https://user-images.githubusercontent.com/83223650/177135975-3d4642e9-9a1e-4ec9-98b9-1834938fa629.png)
However, `x` selects the whole line *including* the newline character, so when I press `c` it deletes that too and shoves the next line onto the current one:
![image](https://user-images.githubusercontent.com/83223650/177136136-762353ef-f589-45aa-be0b-f782700e4a6d.png)

By the way, `gl` *doesn't* select the newline, which is inconsistent with `x`. (Correction: see 2nd comment - there's a reason for the inconsistency)

### Suggestions:
- Don't let the user select `\n`
- Change `a` to stop at line boundaries
- Change `x` to be like `ghvgl` (go to line start, select mode, go to line end not including `\n`)

### Platform

Linux (Arch x86-64)

### Terminal Emulator

wezterm 20220624-141144-bd1b7c5d

### Helix Version

22.05

**Comment by poliorcetics** [comment]
I have the same problem with the kitty terminal emulator, it notably affects how URLs are recognized and copied/pasted:

![Screenshot 2022-07-04 at 13 09 18](https://user-images.githubusercontent.com/7951708/177142991-177eede8-49ed-44ca-9ade-8b54f4ca31fb.png)

**Comment by Nughm3** [comment]
> One issue with this is that for some commands it's necessary for `x`/`X` to select the new-line character as well (like `xd` for example).

That makes sense - in that case vim/nvim probably are not a reasonable comparison due to their different editing model. `dd` in vim will remove the newline but `cc` won't. I'll just use `x_c`.

For `a`, would it be reasonable to confine it to line boundaries?

**Comment by archseer** [comment]
There's some considerations around case 2 to add a C type binding that would change a single line. For now the easiest is `t<Enter>c` which will select until newline then change

**Comment by Nughm3** [comment]
Thanks for clearing that up. I'll close the issue.

**Comment by linde12** [comment]
Man, i wish `xc` would just be more natural - there is really little point to it deleting the newline, and makes xc kind of useless since you always have to do `x_c` or `ghvglc`, `ght<ret>` or similar workarounds to actually _change_ the line (not _remove_ the line it and go into insert mode on the line below)

Sure, one can bind it, but if i wanted keybinds i would use vscode or some other non-modal editor instead. Unfortunately this is one of the primary reasons im sticking to nvim and i am _sad_ about it since i really love how simple it is to configure helix. Hoping you will reconsider one day - i want to like this editor, i really do!

**Comment by tsujp** [comment]
> Man, i wish `xc` would just be more natural - there is really little point to it deleting the newline, and makes xc kind of useless since you always have to do `x_c` or `ghvglc`, `ght<ret>` or similar workarounds to actually _change_ the line (not _remove_ the line it and go into insert mode on the line below)
> 
> Sure, one can bind it, but if i wanted keybinds i would use vscode or some other non-modal editor instead. Unfortunately this is one of the primary reasons im sticking to nvim and i am _sad_ about it since i really love how simple it is to configure helix. Hoping you will reconsider one day - i want to like this editor, i really do!

Having read this thread after finding it due the exact same gripe... I now disagree. If the intention is to make behaviour consistent then I'd rather have the consistent behaviour because that affords less internal logic in Helix to deal with the edge cases created by inconsistent behaviour.

Yes adding a keybinding can suck but `x_c` is already a lot shorter than `ghvglc` (and `x_c` is still quite easy to type) but also the increase in configuration complexity is next to nothing compared to Emacs, (N)Vim, VSCode etc. My Emacs configuration for _less_ functionality than Helix provides out of the box is hundreds of lines of elisp over multiple files; for (N)Vim it's the same in either Lua or VimScript; and for VSCode it's a large JSON object with multiple 3rd party (sometimes abandoned) plugins. My Helix configuration is a dozen lines of TOML.

I was in the camp of "I want this behaviour changed" 10 minutes ago but now I don't.

1. The _intentional_ design of this behaviour keeps Helix's internals simpler; less complexity there = easier maintenance and more predictable behaviour (i.e. less potential for bugs).
2. The small "penalty" of a custom keybinding is nothing when you consider the configuration _simplicity_ in Helix compared to the configuration _complexity_ (and the mental burden, debugging burden etc) of other popular editors with modal capabilities.

**Comment by ethanmsl** [comment]
@tsujp 
The behavior is _consistent_ in the domain of character representations in text.  
The behavior is _inconsistent_ in the domain of human activity.

Pretty much every program that works with texts gives newline representations (the many that there are) special treatment.  Because they are an implementation detail separate from the dynamics of the text as it is intended to be interacted with.

Having also come from the fragile and often laborious Neovim ecosystem what I am also finding frustrating about Helix is that it is very interested in consistency on the mechanical-editor action level, and not on the level of actual use.  Which is to say that Helix demands you be very aware of it's select state and location -- forcing a much more implementation-based interaction.  I'm finding that it 'gets in the way' much more often than it assists, where it differs from vim.

(Heavy remapping helps, but it seems inherent in the model -- as it's designed to be mechanically consistent and not allow conditional actions based on edgecase scenarios.)

**Comment by sommerper** [comment]
@mesmere following functionality of `xc`, shouldn't `xd` then leave a blank line?

**Comment by termie** [comment]
Heya, have been using helix as my only editor now for a couple months (coming from vim), and this (1) _still_ trips me up. I don't think anybody's expectation when starting to "append" at the end of a line is that they'd begin on the next line.

Code is 2-dimensional, the "x-coordinate" you are at likely has some importance whether that be due to formatting and alignment, or simply because lines have more meaning than simply to visually distinguish words. Prose, on the other hand, is 1-dimensional and newlines are just spacing characters in a stream.

I understand the arguments for internal consistency, but at the end of the day we're using a code editor, not a prose editor, and both this issue and what https://github.com/helix-editor/helix/pull/4204 is addressing (hitting right at the end of a line and moving to the beginning of the next line) are things you usually don't want to do when editing code.

**Comment by Alphenex** [comment]
The behaviours will probably not be changed but like others I am not able to get used to these niche behaviours. I have been using Helix for a month and I got used to the controls pretty quickly but no matter how hard I try, I just can't get used to these behaviours. Literally any other editor doesn't do this and it trips me up whenever something gets pasted weirdly or I am suddenly in the next line when trying to append or when selecting lines with "x".
