### ISSUE TITLE
Syntax highlighting conflict of `fn` keyword in rust

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#2986]
### Summary

As of recently the `fn` keyword in rust sometimes has wrong colors.

This probably has a similar cause as #1597 (the third issue highlighted).
The two theme keys that match the `fn` keyword seem to be `keyword` and `function`.

### Reproduction Steps

Edit a basic rust file like this and reload the theme a few times:

```rs
fn main() {}
```

### Platform

Windows

### Terminal Emulator

wezterm (nightly)

### Helix Version

helix 22.05 (1378b911)

**Comment by archseer** [comment]
Probably from https://github.com/helix-editor/helix/pull/2910/commits/521547e0a144b3a194428baac48bc6040da146df

This seems to be a small enough reproduction case that we can analyze since I've seen some non-deterministic highlighting conflicts before. Likely the layer sorting in syntax.rs?

\cc @the-mikedavis
