### ISSUE TITLE
Change cursor shape while in insert

### ISSUE THREAD

**Issue by samholmes** [helix-editor/helix#3010]
I'd like to see the cursor change to a pipe or line when in insert mode, rather a box cursor. This makes more sense and is subtle, but effective indication that insert mode is active.

**Comment by the-mikedavis** [comment]
This can be configured in your `config.toml` file: https://github.com/helix-editor/helix/wiki/FAQ#change-cursor-shape-on-mode-change-bar-cursor-on-insert-mode-block-on-normal-mode-etc

**Comment by samholmes** [comment]
> This can be configured in your `config.toml` file: https://github.com/helix-editor/helix/wiki/FAQ#change-cursor-shape-on-mode-change-bar-cursor-on-insert-mode-block-on-normal-mode-etc

I just found this after writing the issue. So now the issue to request this to be the default behavior.

**Comment by the-mikedavis** [comment]
The cursor is block by default because the cursor is the primary selection which has a width of at least one. The bar cursor misrepresents this.

**Comment by samholmes** [comment]
> The cursor is block by default because the cursor is the primary selection which has a width of at least one. The bar cursor misrepresents this.

But this isn't the case for insert mode. The bar cursor is best for insert mode. The block cursor is best for normal and other modes.

**Comment by sudormrfbin** [comment]
There is the technical limitation of not being able to render multiple bar cursors in a terminal, so the best we can do is render the bar cursor for only the primary cursor. This looks a bit off putting so we decided on block cursors for all modes by default for consistency.

**Comment by the-mikedavis** [comment]
> this isn't the case for insert mode

No, it's true of all modes: you cannot have a 0-width selection.

**Comment by samholmes** [comment]
@the-mikedavis Oh that's weird. Well in that case, maybe underscore is the correct default. But on the other hand...

Insert mode is not like insert mode on modern editors like vscode. Since Helix is a post-modern editor it should inherit some the behavior of modern editors. Here's how we fix it:

1. The selected char is _before_ the bar. For example, `x` is selected `ex|celent`.
2. `backspace` key will delete the current selection while in insert mode (like `d` would while in normal mode)
3. `fn+backspace` or `delete` will delete the character in front of the selection if only one-char is selected, otherwise it will delete the selection just like `d`.
4. Holding shift while clicking around and or pressing the error keys would be adding to the selection.

By making the bar follow the selection, we fix this discrepancy and make this post-modern editor more modern. 😉 

# Additional suggestions:
1. `cmd+z` and `cmd+shift+z` are undo and redo in insert mode.
2. `cmd+u` and `cmd+shift+u` are undo and redo selection while in insert mode.

Essentially, insert mode should be closer to vscode or sublime text's default mode in many ways. This way you get a lot of that familiarity and flexibility to edit while in insert mode.

**Comment by samholmes** [comment]
I figured out how `i` and `a` will work with the new and improved insert mode. Assume the text file is `expert` and `e[x]pert` denotes `x` is selection in normal mode, `e[x]|pert` is `x` selected in insert mode, and `e[xp]|ert` is `xp` selected in insert mode.

```
e[x]pert
```

Pressing `i` results:

```
[e]|xpert
```

While `a` would result:

```
e[x]|pert
```

Because the pipe is always visually at the end of a selected character with my proposal, this means `i` and `a` have different behavior when going from normal to insert with a selection. The `|` will always follow the primary selected character in the selection, or cursor (don't know the official term for that, but I see it's a concept):

```
hello [world]
```

**`i`** will increase the selection one character to the left and place the cursor on that character.
```
hello[ |world]
```

**`a`** will place the cursor on the last character in the selection
```
hello [world]|
```

**Comment by the-mikedavis** [comment]
Non-zero-width selections are by design. Because of helix's select-then-act paradigm, if zero-width selections were allowed, most actions would be useless by default (`d`, `y`, `c`, `r`). Helix derives the select-then-act paradigm from Kakoune which has [nice docs](https://kakoune.org/why-kakoune/why-kakoune.html#_improving_on_the_editing_model) on select-then-act.

The current selection mechanism is also by design: selections have anchors and heads - extending leaves the anchor unchanged and moves the head.

> Since Helix is a post-modern editor it should inherit some the behavior of modern editors

_post-modern_ is meant to be a cheeky tag-line; it's not meant to imply what features helix should or shouldn't have. Helix aims to have [its own take](https://github.com/helix-editor/helix/blob/0cb0c306183be94b9d42c3fae22b805850f87584/docs/vision.md?plain=1#L11) on behavior and when it comes to insertion, that means focusing on being [modal and select-then-act](https://github.com/helix-editor/helix/blob/0cb0c306183be94b9d42c3fae22b805850f87584/docs/vision.md?plain=1#L17-L18).

Also to pull [from the vision doc](https://github.com/helix-editor/helix/blob/0cb0c306183be94b9d42c3fae22b805850f87584/docs/vision.md?plain=1#L22):

> Although the defaults should be good, not everyone will agree on what "good" is.

The default behavior here is arguable but intentional. We don't intend to change it for now.

**Comment by archseer** [comment]
@89z "Helix cursor is bad and they refuse to fix it"

Our cursor matches the default vim one (always 1-width, always bar). If you want to change cursor shapes, there's a config option too [https://github.com/helix-editor/helix/wiki/FAQ#change-cursor...](https://github.com/helix-editor/helix/wiki/FAQ#change-cursor-shape-on-mode-change-bar-cursor-on-insert-mode-block-on-normal-mode-etc)

kirawi closed this as not planned but it really should have been closed as resolved.

**Comment by archseer** [comment]
s/bar/block/. Helix in normal mode uses a box.

**Comment by archseer** [comment]
See for yourself: ![helix](https://user-images.githubusercontent.com/1372918/198206853-235e0478-0f04-4e8c-8a91-25b446f77b75.jpg)

So I'm still not clear on what we refuse to fix.

**Comment by 89z** [comment]
@archseer just look at the title. Helix uses a box in insert mode, instead of a line like Vim. Yeah you might be able to configure it, but I don't think Ive seen a justification yet *why you should have to*.

when you are in insert mode, its import to know *where the next character is going to be inserted*. If you have a line between characters, then the answer to that question is very clear. If you have a box covering one character, then the new character could be inserted before or after the box.

This is similar to Vim in normal mode, where you can move a box over a character, and press `p` or `P` to paste before or after the box. However insert mode doesn't have the luxury of being able to choose before or after the cursor, it can only do after. But if a box is used, and you move the cursor to the middle of a word, its ambiguous where the next character will be entered, as an application could choose to enter it before or after the highlighted character.

For an example of "the right way", just try to add a comment on this page, and see how GitHub presents the cursor, *as a line*, not a box.

**Comment by archseer** [comment]
Supporting different cursor shapes is an extension that's not supported by all terminals, hence it's opt-in. We could provide a fallback if we did proper feature detection like we do for undercurl.

**Comment by the-mikedavis** [comment]
> The above comment is not true. In Windows Notepad, or the GitHub comment editor, or any number of other tools, you very much can have a "0-width selection", its called _no selection_. If I don't select anything, then thats zero width.

I think we're talking about different things. I'm talking strictly about Helix and implementation-wise, zero-width selections are not allowed (there are edge-cases in the implementation like the EOF but those are still rendered as 1-width). You always have a selection - even when inserting text - and the block represents that accurately. There's a concept for a "cursor" which is defined as the left-side position of the block. That's where text goes when you enter insert mode with `i` and type, and that more-or-less maps to what you're describing in other editors.

> Also I don't understand why selection is being discussed with Insert mode at all. Insert mode isn't used with selection, Visual mode is.

In other editors sure, but in Helix selections survive insert mode since it's useful with multiple selections: https://asciinema.org/a/BiG3ba1RPAkMVI1H4eo7an9eq or see https://github.com/helix-editor/helix/discussions/3388#discussioncomment-3378959

You'll have to try it to see for yourself since asciinema doesn't support rendering the bar cursor but the bar ends up having shortcomings in all but the trivial case (inserting with just the 1-width cursor selection):

* We can't render secondary selections with the bar (terminal limitation)
* If you have a selection with a width > 1, inserting and appending look strange at best and are inaccurately representing your selection at worst

**Comment by ksandvik** [comment]
I changed the cursors based on mode and I think let end users decide what they prefer.
