### ISSUE TITLE
`x` on blank line selects including the following line

### ISSUE THREAD

**Issue by d12bb** [helix-editor/helix#3077]
### Summary

Having the cursor on an empty line and pressing `x`, the newline character plus the following line is selected.

### Reproduction Steps

[![asciicast](https://asciinema.org/a/508746.svg)](https://asciinema.org/a/508746)

I tried this:

1. `hx test.go`
2. Move cursor to a blank line
3. Press `x` or `xd`

I expected this to happen:
The line the cursor is on is selected/deleted.

Instead, this happened:
The line the cursor is on *and the following line* (so two lines) are selected/deleted.

### Platform

macOS 12.4

### Terminal Emulator

Kitty 0.25.2

### Helix Version

22.05-243-g8681fb6

**Comment by archseer** [comment]
This is explained in https://github.com/helix-editor/helix/issues/362 under example 2. On an empty line there is no way to tell if you're trying to select the current line, or if you're extending onto the next one because the current line is already fully selected.

**Comment by d12bb** [comment]
Ah sorry, didn't find those on my search for `newline`. But skimming that, shouldn't this be resolved by #376?

Anyway, swapping `x` and `X` should do the trick for me, thanks.

**Comment by the-mikedavis** [comment]
> All code has been adjusted so that it still presents an on-char indexing model to the user, but internally everything works in terms of gap indexing.

(from #376)

We still use on-char indexing for selections/cursors so you can't select between the new-line and anything else. I believe the intention is to keep the current on-char indexing since a selection with 0-width makes many commands (`r`, `d`, `y`, `c`) useless by default. Gap-indexing is an under-the-hood implementation detail.

It's easier to understand the current behavior if you enable visible whitespace, even if you only enable newline characters https://docs.helix-editor.com/master/configuration.html#editorwhitespace-section

I'll close this as not-planned since it's the intended behavior but I also recommend to swap `x` and `X` either in your config or in your muscle-memory for 'delete the current line'

**Comment by ukiahsmith** [comment]
I ran into this today and found it very jarring. It took me out of the flow of editing and made me have to think and consider the context of my cursor before using `xd` to delete a line.

A special case should be made for when `x` is used on a blank line, without affecting how `r`, `d`, `y`, or `c` work. Which would enable a smoother editing experience. Keeping this as is for the sake of command consistency is unwise. The editor I use should enable me in the editing flow, not trip me up.

**Comment by tjkirch** [comment]
> It's easier to understand the current behavior if you enable visible whitespace, even if you only enable newline characters https://docs.helix-editor.com/master/configuration.html#editorwhitespace-section

I was super confused by this behavior as well, as a new user, and I didn't find the visible whitespace helpful because there's no option to enable it conditionally, e.g. #2719 / #4306, or only showing newlines when the line consists *solely* of a newline.  The "all" options make whitespace super distracting.

**Comment by pozix604** [comment]
For posterity, I also think this behavior is unintuitive.

`X` doesn't work in place of `x` because when I want to delete two lines with delete the next two lines, I want to type "xxd" and oops, three lines are now gone.

Bottom line, with existing behavior, you now need to be aware if the current line is blank (and that it is not a line with spaces and/or tabs) and adjust accordingly.

`V` in vim does this better.

**Comment by danrot** [comment]
I also ran into this issues, which is especially weird when using relative line numbers. If I want to delete multiple lines I can use `<count>dd` in vim, and I know exactly what number to type based on the relative line number. I can do the same thing with `<count>xd` in helix, but because of this behavior I cannot rely on the relative line numbers, I also have to check if the line I am currently on is an empty line or contains some rows. 

> Technically, this is not a bug, though I agree that it's a bit unexpected.
> 
> The cursor is a one character wide selection, so if you're on an empty line the "whole line" is already selected. x will then extend to the next line.
> 
> You can use Xd (that is upper case X) to only select the one line and delete it.
> 
> I ran into a similar thing and personally just swapped `x` and `X` in my key bindings. (see #835)

I don't see that as a valid replacement, since typing `<count>Xd` does not work, it will just delete one line.

I think that's a pity, because in general I really like helix, but this is kind of a show stopper for me. It would also be fine for me if I had to change something in the configuration to get my desired behavior, but it doesn't sound to me like that's going to happen...

**Comment by CptPotato** [comment]
> I can do the same thing with `<count>xd` in helix, but because of this behavior I cannot rely on the relative line numbers, I also have to check if the line I am currently on is an empty line or contains some rows.

This wasn't always the case actually, `<n>x` used to select n lines. It must have been introduced at some point to be consistent with `x`.

I'm not sure if there's a clean solution here, but I think you can use `v<n>jXd` as another method.

**Comment by danrot** [comment]
@CptPotato Yeah, it's just that I find this behavior odd in both cases 🙈 

I was aware of the fact that there might be certain workarounds, but I am using this functionality a lot, so it makes a big difference to me if I have to press 3 or 5 keys in order to achieve it.

**Comment by kingofpayne** [comment]
Same experience here. Coming from vim, tried `dd` to delete a line, found it is `xd` in helix. Accepted my fate and used `xd` until I encountered an empty line. Discovered i shall type `Xd` which I believe is not an acceptable solution just to remove a single line.
