### ISSUE TITLE
Tmux messing with highlighting

### ISSUE THREAD

**Issue by ElSargo** [helix-editor/helix#3099]
### Summary

When I run helix inside a tmux session all my comments get highlighted grey.
![image](https://user-images.githubusercontent.com/103979764/179597008-e9cc509d-9571-4b6f-b4de-e52ae12717e8.png)
Then outside a tumx session the issue is gone...
![image](https://user-images.githubusercontent.com/103979764/179599902-ebe1d5c8-9160-40bd-b994-25872322dab2.png)

### Reproduction Steps

Install tmux using: sudo apt get tmux
Install helix with :
brew tap helix-editor/helix
brew install helix

open a supported file and make a comment
(this also happens in .toml files ect)

I have tried uninstalling both helix and tmux and removing all config files but I can't seem to find the cause of the issue

### Helix log

***log is empty***

### Platform

Linux ubuntu

### Terminal Emulator

gnome40 terminal

### Helix Version

helix 22.05 (27609f50)

**Comment by sudormrfbin** [comment]
It might be caused by your terminal not supporting italics (or tmux not picking up support for it from your terminal) since the comments are italicized. Could you try two other themes with and without italics and see what happens?

**Comment by christianfosli** [comment]
See https://github.com/tmux/tmux/wiki/FAQ#i-dont-see-italics-or-italics-and-reverse-are-the-wrong-way-round

It works for me with 

```
set -g default-terminal "tmux-256color"
```

in my tmux.conf

**Comment by ElSargo** [comment]
That fixed it, thanks!

**Comment by hackaugusto** [comment]
Dropping a comment for Mac users arriving here through google:

- As of Monterey 12.6:
  - Mac is distributed with:
```shell
> ncurses5.4-config --version
5.7.20081102
```

  - this version does not have tmux in its terminfo db:

```shell
> infocmp tmux
infocmp: couldn't open terminfo file (null).
```

- Since tmux `2.2` it supports italics, but the `$TERM` must be set to a variant matching the glob `tmux*` [ref](https://github.com/tmux/tmux/wiki/FAQ#i-dont-see-italics-or-italics-and-reverse-are-the-wrong-way-round)
  - This is the default as of `3.3a` [ref](https://github.com/tmux/tmux/issues/3218), which breaks everything on mac, so one must either generate the db by hand or set the term back to a variant of `screen*`
- The above means that tmux on macos does not support italics out-of-the-box, and can be tested with the following command:

```sh
> echo -e "\e[3mitalic\e[0m"
```

On iterm2 or alacritty this will render:

<img width="273" alt="Screenshot 2022-10-14 at 20 08 12" src="https://user-images.githubusercontent.com/310139/195912861-8248997d-b425-4462-827a-5cf761095fd4.png">

but in tmux, inside any of these virtual terminals:

<img width="273" alt="Screenshot 2022-10-14 at 20 09 02" src="https://user-images.githubusercontent.com/310139/195912972-06add3db-602e-4490-a597-ca3f2742b365.png">

this means that helix wont look right, like the screenshots on from OP or this:

inside tmux:

<img width="1832" alt="Screenshot 2022-10-14 at 17 44 04" src="https://user-images.githubusercontent.com/310139/195913147-bb7d3237-1594-4205-877f-d818ac59f973.png">

with only alacritty:

<img width="1840" alt="Screenshot 2022-10-12 at 18 30 04" src="https://user-images.githubusercontent.com/310139/195913219-64660952-982f-4999-b1de-b3f4df08b94c.png">

**Comment by Swoorup** [comment]
> Dropping a comment for Mac users arriving here through google:
> 
> * As of Monterey 12.6:
>   
>   * Mac is distributed with:
> 
> ```shell
> > ncurses5.4-config --version
> 5.7.20081102
> ```
> 
> * this version does not have tmux in its terminfo db:
> 
> ```shell
> > infocmp tmux
> infocmp: couldn't open terminfo file (null).

`set -g default-terminal "tmux"` fixed it for me,

**Comment by SorenHolstHansen** [comment]
Tried both of your solutions, but none of them fixed it for me. Couldn't even follow the solution you linked to @hackaugusto because i got
```
> /usr/local/opt/ncurses/bin/infocmp -x tmux-256color > ~/tmux-256color.src
zsh: no such file or directory: /usr/local/opt/ncurses/bin/infocmp
```
Do you have an idea why It doesn't work for me?

**Comment by jerinjoy** [comment]
I followed the instructions in:
https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/

to set up the terminfo for tmux:

```
❯ exa -lh --git --sort=newest /Users/joy/.local/share/terminfo/74/tmux-256color
Permissions Size User Date Modified Name
.rw-r--r--@ 3.3k joy   7 Apr 22:29  /Users/joy/.local/share/terminfo/74/tmux-256color
```

and set "tmux" as my terminal. hx displays the colors correctly but I still get errors running some applications:

```
❯ git diff
WARNING: terminal is not fully functional
Press RETURN to continue
```

**Comment by Sackbuoy** [comment]
> See https://github.com/tmux/tmux/wiki/FAQ#i-dont-see-italics-or-italics-and-reverse-are-the-wrong-way-round
> 
> It works for me with
> 
> ```
> set -g default-terminal "tmux-256color"
> ```
> 
> in my tmux.conf

Setting this caused [Backspace Bad Behavior](https://github.com/tmux/tmux/issues/321) for me, 
So I recommend setting 
```
set -g default-terminal "xterm-256color"
```
instead

**Comment by muminoff** [comment]
This one worked for me.

Replace `set -g default-terminal "xterm-256color"` with following:
```
set-option -sa terminal-overrides ",xterm*:Tc"
```
Restart tmux.

**Comment by webdev23** [comment]
I had trouble loading Helix custom themes inside tmux/byobu, and the fix for me was to add exactly the following in `~/.byobu/tmux.conf`:

```
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
```
