### ISSUE TITLE
Add support for nim-lang

### ISSUE THREAD

**Issue by Zaplae** [helix-editor/helix#3117]
Nim is a statically typed compiled systems programming language. 
It combines successful concepts from mature languages like Python, Ada and Modula. 

lsp: https://github.com/nim-lang/langserver
treesitter: https://github.com/aMOPel/tree-sitter-nim

**Comment by YesDrX** [comment]
[[language]]
name = "nim"
scope = "source.nim"
injection-regex = "nim"
file-types = ["nim","nims"]
shebangs = ["nim"]
roots = []
comment-token = "#"
language-server = { command = "nimlsp" }
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "nim"
source = { git = "https://github.com/aMOPel/tree-sitter-nim", rev = "3727117e9a793610138ab0eabd75bef04c86299f" }

**Comment by theherk** [comment]
Since one of the goals of the author of the grammar is to write the queries for [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries), I'm just going to watch closely until then. The queries written by the author of the grammar will probably better than my attempt. So we should crib those, then modify as required.

watch for progress:

- aMOPel/tree-sitter-nim
- [the non-existent nim directory in nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/nim)
- nvim-treesitter/nvim-treesitter#3011
- nvim-treesitter/nvim-treesitter#2282

That is of course in lieu of somebody else writing the queries in the meantime, which would be awesome.

**Comment by theHamsta** [comment]
I just tried to add the nim parser to nvim-treesitter, but it SEGFAULTED during my editing session which in probably a no-go for editor integration.

**Comment by theHamsta** [comment]
The SEGFAULT has been fixed. WIP for highlighting here https://github.com/nvim-treesitter/nvim-treesitter/pull/3320 , Please note that the parser is not intended for usage yet, but it will probably be some day.

**Comment by geohuz** [comment]
wondering when nim support will be ready for helix?

**Comment by sharpcdf** [comment]
Same here, but it looks like the pr for nvim-treesitter was closed a while back

**Comment by mitjafelicijan** [comment]
Any news about this?

**Comment by theHamsta** [comment]
https://github.com/aMOPel/tree-sitter-nim still claims to be "not ready for use" but is also "welcome to contributions". Maybe interested people could have a look at the parser to see what is still missing to make it ready to use.

Also highlights at https://github.com/nvim-treesitter/nvim-treesitter/pull/3320 are incomplete, but maybe a good start for alpha testers to see what's missing in the queries and the parser.

**Comment by aMOPel** [comment]
Update on this: 

https://github.com/alaviss/tree-sitter-nim

Is now in a very usable state and does far better than my parser.
I have written a bunch of [queries](https://github.com/aMOPel/nvim-treesitter-nim) for nvim already.

Feel free to adapt them to helix.

**Comment by bdjnk** [comment]
To keep this issue up to date, note that initial language support was added in #6123.

Support could be improved, as aMOPel says, along the lines of [this Neovim PR from last month](https://github.com/nvim-treesitter/nvim-treesitter/pull/5556).

**Comment by omentic** [comment]
This issue can be closed. There are some issues with the language server, but they're on the Nim side of things.

I'll be updating the queries to be based on alaviss's (more complete) grammar shortly.
