### ISSUE TITLE
Implement a File Watcher

### ISSUE THREAD

**Issue by brxken128** [helix-editor/helix#3171]
I am aware that this is a duplicate, and I apologise for this.

I saw the open PR regarding this feature, #2653, and I was wondering if there's anything we can do to get this implemented? From what I can see, it's a pretty sought-after feature and I wouldn't mind helping out where possible.

The PR looks stale and the user hasn't been active, would it be best to start fresh? I'm sure we can get something suitable from what that user started.

**Comment by brxken128** [comment]
From what I can see, things look fine aside from the scattered `TODO` items, many of which are questions.

**Comment by the-mikedavis** [comment]
In general the [Matrix Space](https://matrix.to/#/#helix-community:matrix.org) is a better format for this kind of development discussion.

#2653 is a bit held up since it's in need of review / guidance - it may not be stale on the author's end. You can contribute to their branch on their fork if you'd like to pull it over the finish line and have a good idea of how to go about it, or discuss directly on the PR if the author is still active. You can also pick up their branch and modify it as needed and open a PR to supersede #2653. I would make sure to at least give the original author co-author attribution on commits you re-use/modify though.
