### ISSUE TITLE
Close hover documentation when cursor leaves the symbol

### ISSUE THREAD

**Issue by teenjuna** [helix-editor/helix#326]
Currently when we press `K` to open documentation for the symbol under the cursor and then move the cursor somewhere else, the documentation doesn't disappear and follows the cursor:

https://user-images.githubusercontent.com/53595243/122671566-8abe8f80-d1f1-11eb-9ee1-38d7fcf79224.mov

I find this somewhat counter-intuitive. I expect it to disappear as soon as the cursor leaves the symbol. Is it intentional or should we try to fix this?

### Environment

- Platform: macOS
- Helix version: v0.2.1-49-g2cbec2b

**Comment by archseer** [comment]
Would like to fix this but I might want to add a proper hook system first so these things can be properly abstracted.

**Comment by archseer** [comment]
Quick workaround would probably be Event::Ignored also taking a callback so we could catch the key in handle_event, ignore it, but still trigger a close.

**Comment by jens1205** [comment]
With hx v0.4.1 on Mac, the hover is not following the cursor any more - but it does not close either. So I can open a lot of hover documentation for different items the same time.

But nothing closes if I move the cursor away, what is what I expect. So how is the documentation closed?

**Comment by archseer** [comment]
`Esc`

**Comment by jens1205** [comment]
Indeed, this works. I haven't noticed, because I first tried to close / toggle the hover documentation again with K. But this apparently leads to another instance of the hover window to be placed "on top" of the other. And after pressing twice `K`, you have to press twice `Esc`.

Even more strange is the behaviour if you enter into insert mode while having one or more hover windows open. Now `Esc` does not switch to normal mode, but instead you first have to close all hover windows before you can leave insert mode.

I don't think this beaviour is wanted. Either the hover window should be closed upon cursor movement. Or the window should be toggable via `K`.

**Comment by kirawi** [comment]
Nevermind, it's not a duplicate/
