### ISSUE TITLE
Remove duplicate entries from theme picker

### ISSUE THREAD

**Issue by ChrHorn** [helix-editor/helix#3354]
It is possible to overwrite the runtime themes that come with Helix by putting a theme with the same name in the `.config/helix/themes` directory. This creates duplicate entries in the theme picker that both point to the same theme:

![image](https://user-images.githubusercontent.com/17070041/183368088-2e0fe443-2dc9-4943-a2ec-20f96ba9a84e.png)

Best solution would be just to remove the duplicate entries.

**Comment by pythoneer** [comment]
I generally agree, but is it that more complicated to maybe have it like
```
bogster             bogster(user)
```
To have them both and mark the user theme?

**Comment by the-mikedavis** [comment]
That might be a problem for choosing a theme in your `config.toml`: do you write `theme = "bogster(user)"`? It could work but it doesn't seem very elegant.

It looks like both "bogster"s activate same theme (the user one) because of the theme loading rules. I think the simplest way to make this less confusing would be to deduplicate the theme completion but in the long-run we may want to support multiple themes with the same name for the sake of https://github.com/helix-editor/helix/pull/3067
