### ISSUE TITLE
Wrong indenting in some languages

### ISSUE THREAD

**Issue by yusdacra** [helix-editor/helix#339]
`helix` indenting behaves weird in a Nix file. The asciicast below showcases this behaviour. I would have expected `helix` to indent like the `indent-style 1` behaviour with `indent-style 2`, since I expect it to indent 2 spaces with `indent-style 2`. That behaviour however does not happen with `indent-style 2`, and instead happens with `indent-style 1`. This seems to not happen in more simpler (?) files.

### Reproduction steps

0. download [this file](https://raw.githubusercontent.com/yusdacra/nix-cargo-integration/master/lib.nix)
1. do what the asciicast does

[![asciicast](https://asciinema.org/a/5sgsEDtRdJporvNSUcJf1q1oR.svg)](https://asciinema.org/a/5sgsEDtRdJporvNSUcJf1q1oR)

### Environment

- Platform: Linux
- Helix version: v0.2.1-80-gd39a764

<details><summary>~/.cache/helix/helix.log</summary>

```
nothing
```

</details>

**Comment by nrdxp** [comment]
I noticed this as well when I first submitted the nix support. Originally I had some outdents registered as well, but it behaved even more poorly than it currently does. I think the underlying algorithm needs fixing, since nothing I tried got it working the way I would expect. We [decided](https://github.com/helix-editor/helix/pull/203#issuecomment-858601805) to go ahead and merge it that way, and fix it later, so I'm glad you opened this up (probably should have done it myself :sweat_smile:)

**Comment by cessen** [comment]
Just want to note that I haven't forgotten about this!  Assuming nothing else comes up that's more urgent, this is next on my Helix todo list.

**Comment by cessen** [comment]
Okay, so it turns out this nothing like I thought it was.  I was assuming it had something to do with the indentation work I did, but it looks like it's actually related to tree-sitter.  I have zero experience with tree-sitter, so I think it would take me a long time to ramp up and work this one out.

Unassigning myself (sorry!), since someone else is probably much better suited to tracking this down and fixing quickly.

**Comment by cessen** [comment]
Just a note that I run into this regularly even in Rust files.  So it doesn't seem to be `nix` specific.

**Comment by yusdacra** [comment]
> Just a note that I run into this regularly even in Rust files.  So it doesn't seem to be `nix` specific.

Yeah, I noticed that too. Should we open another issue for that or rename this issue?

**Comment by cessen** [comment]
Probably just rename this issue.

**Comment by archseer** [comment]
I took a look at the nix expressions, the problem seems to be the inconsistency in Nix indentation:

```nix
{ sources }:
let
  lib = ...
in
```

The scopes inside the let is `function` `let`, so it results in two indentation levels. Which makes sense in cases like these:
```nix
  makeOutput = { common, renameOutputs ? { } }:
    let
      inherit (common) cargoToml cargoPkg packageMetadata system memberName root lib;
```

that also contains a bind scope (`a = ...`) so maybe the rule should be no indentation on `function`, but indent on `bind`.

You can test this out by changing the `indents.toml` to:

```toml
indent = [
 # "function",
 "bind",
 "assert",
 "with",
 "let",
 "if",

 "attrset",
 "list",
 "indented_string",
 "parenthesized",
]

outdent = [
  "}",
  "]",
]
```

(I also added `with` to indents)

**Comment by archseer** [comment]
I pushed these changes in e2c3547f266448e8b74f0f492a8f50c18fb12e0c

**Comment by pascalkuthe** [comment]
This issue seems unactionable to me. It looks like some tree-sitter indent queries need to be improved.
There should be specific issue for the specific problems in each separate language tough that describes the exact problem as this issue originally did for nix.

As the original problem, described here was fixed I am closing this issue for now.
