### ISSUE TITLE
Make newly pasted text selected

### ISSUE THREAD

**Issue by hzb-ykpcx** [helix-editor/helix#3401]
I think it's better when you delete/yank some paragraphs and paste it, the newly pasted text is selected, for reasons below:

we often need to modify the pasted code immediately, and it's quite annoying to select it again. For example, helix , for now, can't automatically indent the pasted code correctly, it only holds the original indent. So probably we should indent manually by shortcut. Honestly, I often use helix for acm training, that's the issue I meet every day. And I think this feature along with the automatic indent for pasted code are quite useful.

**Comment by the-mikedavis** [comment]
The workaround I use for this currently is to use R or Space-R rather than P or Space-P.

I think this could work well as the default behavior though, especially in combination with #1596 so that you could jump back to the pre-paste selection if it was important. Even without #1596, you could collapse the selection to get close to where you were, or use the jumplist.

**Comment by hzb-ykpcx** [comment]
Yes, I do believe make it a default behavior can save a lot effort.

**Comment by the-mikedavis** [comment]
Kakoune recently adopted this behavior (in the development branch but not yet released):

* `p` and `P`: https://github.com/mawww/kakoune/commit/266d1c37d0d970a7eff747f5e6a5773a3cea39d8
* `!` and `A-!`: https://github.com/mawww/kakoune/commit/85b78dda2e29d70b620836b04224b104426bdbae
