### ISSUE TITLE
Indent and dedent don't match

### ISSUE THREAD

**Issue by Zoybean** [helix-editor/helix#3406]
### Summary

In a file with mixed indent amounts, and a language set (I tried with bash an rust, I'm not sure what the exact conditions are), indent amounts do not match dedent amounts.

### Reproduction Steps

 

With the following file open:

```
test
 file
  with
   mixed
    indents
new line
```

1. `:set-language bash`
2. `ge`
3. `<`
4. `>>`
5. `:set-language rust`
6. `<`
7. `>>>>`

I expected this to happen:

At steps 4 and 7, the indent amount matches the dedent amount in the preceding step

Instead, this happened:

At step 3. the dedent amount is 2 spaces. At step 4, the indent amount is 1 space.
At step 6, the dedent amount is 4 spaces. At step 7, the indent amount is 1 space.

### Helix log

n/a

### Platform

Windows (WSL: ubuntu)

### Terminal Emulator

Windows Terminal Version: 1.14.1962.0

### Helix Version

22.05-367-g63ec1095

**Comment by AceofSpades5757** [comment]
I've had this issue as well, with different languages. Most notably on a pull request branch that's working on Python indentation. So I suspect it's an issue with tree-sitter indent.scm file, but I'm not sure.

**Comment by Triton171** [comment]
I've seen this bug too but it doesn't have anything to do with the `indent.scm` queries since those are only used to determine the indentation of a new line. I guess there is a bug somewhere in the `indent`/`unindent` functions in `helix-term/src/commands.rs`. Both functions are pretty short so it might not be too difficult to find it.

**Comment by pascalkuthe** [comment]
Closed by  #5918, we forgot to link
