### ISSUE TITLE
Delete grammar source files after build (Homebrew)

### ISSUE THREAD

**Issue by ChrHorn** [helix-editor/helix#3437]
The runtime directory is getting pretty large, currently around 750MB. The vast majority is due to the tree-sitter source files (660MB). As far as I know these are only needed for the build process and could be deleted after.

**Comment by the-mikedavis** [comment]
We do this in the release CI: https://github.com/helix-editor/helix/blob/8a757954728b52ec92843388049dcaea60db8e3c/.github/workflows/release.yml#L183

Automatically removing grammar sources could be a little dicey: we currently use grammar sources themselves in order to know if a grammar source is out of date and needs to be updated. We could write a manifest with the current inputs/outputs to know what's up-to-date and what isn't. I'm not sure it's worth the effort though since you can already limit what grammars you fetch and build:

```toml
# ~/.config/helix/languages.toml
use-grammars = { only = [ "rust", "c", "toml" ] }
```

and if you're building a package, you can `rm -rf` the `runtime/grammar/sources` directory.

Grammar sources are also not strictly used in the build: you can fetch and build grammars after building with `hx -g fetch` and `hx -g build`, and you can build helix without fetching or building grammars by setting the `HELIX_DISABLE_AUTO_GRAMMAR_BUILD` env var. The compiled parsers aren't built into the `hx` binary.

**Comment by ChrHorn** [comment]
I had someone complain about the large install size who used brew on Mac. Can't really check, cause I don't have one, but I think the cleanup step is missing here: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/helix.rb

A manifest file would be nice. Another advantage would be that updating grammars would be much more straight forward. Currently you have to delete the files manually first before fetch, build. But you are right, it is not really first priority.

**Comment by the-mikedavis** [comment]
Ah yeah that source tarball (https://github.com/Homebrew/homebrew-core/blob/fe5a5667346b47e0ec7f99908b795185f6bd03f6/Formula/helix.rb?rgh-link-date=2022-08-15T14%3A46%3A47Z#L4) contains the grammar sources so it's quite large. Homebrew would be safe to remove `runtime/grammar/sources` and that should dramatically decrease the size of the package 👍

I'm not very familiar with how to do that with Homebrew builds. Maybe it would be best to propose the change upstream or to ping the author here?

We should probably remove grammar sources in our tap as well: https://github.com/helix-editor/homebrew-helix/blob/master/Formula/helix.rb. Although if helix made its way into Homebrew core, maybe we don't need to have an official tap?

> Currently you have to delete the files manually first before fetch, build

I don't think I've seen this behavior: if I update a revision in the languages.toml and `cargo build` or `hx -g fetch` I always see the new grammar source in place. Do you see helix failing to recognize an out-of-date grammar?

**Comment by ChrHorn** [comment]
The issue was mentioned in the PR https://github.com/Homebrew/homebrew-core/pull/105833, seems we have to do it ourselves.

> I don't think I've seen this behavior: if I update a revision in the languages.toml and `cargo build` or `hx -g fetch` I always see the new grammar source in place. Do you see helix failing to recognize an out-of-date grammar?

You are right, seems to works fine. I must have mixed something up.

**Comment by the-mikedavis** [comment]
Closed in https://github.com/helix-editor/homebrew-helix/commit/71863a904987915988c719fff6ff7943809c8082

**Comment by the-mikedavis** [comment]
Oh actually let's leave this open pending https://github.com/Homebrew/homebrew-core/pull/108657

**Comment by the-mikedavis** [comment]
Ok now that's merged in upstream 🎉
