### ISSUE TITLE
Archlinux bin conflicts with "hex"

### ISSUE THREAD

**Issue by olanod** [helix-editor/helix#344]
There's a package called `hex`(a Rust hexdump utility) that installs a binary with the same name `hx` creating a conflict, I'm personally renaming helix to just `h` as a workaround.

**Comment by pickfire** [comment]
I thought the rust hexdump utility is called hexyl? Oh https://github.com/sitkevij/hex, I use hexyl for that https://github.com/sharkdp/hexyl

**Comment by pickfire** [comment]
I don't know how can we even fix this so I will put won't do for now. I didn't know the about hex which binary named hx. Let's see what @archseer think.

**Comment by pickfire** [comment]
But helix have more stars. :P

**Comment by archseer** [comment]
In this day and age it's almost impossible not to conflict something. I expected this and I don't think there's anything to be done here. We can probably provide a symlink with another name (`helix`, but I'm betting that will conflict yet other things) but it's mainly up to the user to set up aliases for the binaries on their side.

I imagine nodejs was also not the first tool with a binary named `node` when it came out :P

**Comment by CBenoit** [comment]
I remember [ripgrep](https://github.com/BurntSushi/ripgrep) being packaged with something else than `rg` on Ubuntu a few years ago for the same reason IIRC but that's not the case anymore. I guess this is better handled by package maintainers. We should maybe close the issue?

**Comment by IceDragon200** [comment]
[I am the maintainer](https://aur.archlinux.org/account/IceDragon/) for the arch [helix-bin](https://aur.archlinux.org/packages/helix-bin/) AUR package.

`hx` is the original binary name, so I created the symlink with the same name.

For now since it's in the AUR, you can always edit the PKGBUILD before installation and change the name of the symlink to your liking.

If we do change the name, I would prefer if it's changed across the board so no one platform has a special case naming (i.e. the `node` vs `nodejs` issue on debian based systems)

We can leave the issue open to generate some more discussion, if everyone agrees, I'll change it, if everyone disagrees I won't change it.

**Comment by archseer** [comment]
I don't think there's anything actionable here for now, we did get included in the Arch community repo recently as well 🎉

**Comment by archseer** [comment]
Note: the Arch package maintainer did end up renaming the binary to `helix` and suggesting to alias it back via `hx=helix` if necessary.

**Comment by pickfire** [comment]
> suggesting to alias it back

I don't see the suggestion when installing it.

@IceDragon200 Is it possible to show suggestion as a hook. I think this behavior might be quite surprising for some users expecting it to be hx.

**Comment by archseer** [comment]
The AUR package retains the `hx` name, the one in the community repo was renamed. https://github.com/archlinux/svntogit-community/blob/packages/helix/trunk/helix.install

**Comment by archseer** [comment]
I don't think it's reasonable to expect `hex` to rename.
