### ISSUE TITLE
Rust's try operator doesn't highlight as operator

### ISSUE THREAD

**Issue by vlmutolo** [helix-editor/helix#3490]
The try operator (`?`) doesn't highlight as an operator. I tried to fix this myself by adding it to the end of the `@operator` list in `runtime/queries/rust/highlights.scm`, but it didn't work. I guess it's a little more complicated than that.

I also saw the `"?" @special` highlight near the end of that file, but I'm not sure what piece of syntax that refers to.

**Comment by the-mikedavis** [comment]
> I tried to fix this myself by adding it to the end of the `@operator` list in `runtime/queries/rust/highlights.scm`, but it didn't work

That patch should work. Are you sure you [linked your runtime directory](https://github.com/helix-editor/helix/blob/aef00a3ab640417f06dc9f59938283ffde5c451e/README.md?plain=1#L48-L55) instead of copying it?

`"?" @special` is the current capture but I think operator is more appropriate given that `?` is categorized by the [rust reference](https://doc.rust-lang.org/reference/expressions/operator-expr.html#the-question-mark-operator) as an operator. `@special` is a yet-undocumented theme key that is otherwise used for matched text in pickers/menus.

**Comment by vlmutolo** [comment]
> Are you sure you [linked your runtime directory](https://github.com/helix-editor/helix/blob/aef00a3ab640417f06dc9f59938283ffde5c451e/README.md?plain=1#L48-L55) instead of copying it?

Yeah I was directly editing the version in my local `helix` repo and then testing it over and over to no avail. I thought I was editing the one in my config directory. 🧠

I think it works now, though.

**Comment by pascalkuthe** [comment]
I can't link the exact pr that fixed this but the try operator is definitely highlighted these days
