### ISSUE TITLE
run-shell-command async / on another thread

### ISSUE THREAD

**Issue by Koshizo-dev** [helix-editor/helix#3506]
#### Describe your feature request

Hey!

When executing `sh cargo check` helix stops responding, it looks like sh is being executed on the main thread.
But I'd like to be able to continue editing my code while I use any `sh` command.
(I ran `sh cargo check` to import a dependency, but whilst its being downloaded I'd like to continue editing)

### Feature: Run sh asynchronously or on another thread

Best regards

**Comment by the-mikedavis** [comment]
There's a PR for this: https://github.com/helix-editor/helix/pull/3029. IMO it could be the default behavior for `:sh`.

I wouldn't recommend using `:sh` for running builds or tests like `cargo check` though: it's meant to make it possible to bind keys to shell commands rather than be a replacement for a full terminal emulator like #1976. For shell commands that take some time or have non-trivial output I would recommend running the command in a separate shell (a separate tmux or terminal emulator window/split)

**Comment by RqndomHax** [comment]
Oh didn't check if there was any PR regarding this issue,

Yeah normally I'm using another shell, but I tried to run it in helix directly because it seemed easier.

**Comment by pascalkuthe** [comment]
Closed by #6373
