### ISSUE TITLE
Helix editr gets stuck when `:sh sh`

### ISSUE THREAD

**Issue by marlonmp** [helix-editor/helix#3524]
### Summary

Helix editr get stuck when `:sh sh`

### Reproduction Steps

 

I tried this:

1. `hx`
2. `:sh sh`

 this happened:

helix editor get stuck forever like this

| ![image](https://user-images.githubusercontent.com/76027579/186255842-31b0c3eb-35a1-40ff-8cc5-cd865eeb5c84.png) |
| :--: |

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

Nothing in log file

```
```

</details>

### Platform

Linux

### Terminal Emulator

genome-terminal 3.44.1-1

### Helix Version

22.03-687-ge4c9d408

**Comment by A-Walrus** [comment]
This makes sense within how `:sh` currently works. It waits for the command to terminate, and since `sh` doesn't terminate (it waits for user input) helix will keep waiting.
#3029 will make the shell async and non blocking.
If what you were trying to achieve is having an interactive, integrated terminal within helix, then that might be addressed by #1976 in the future...

**Comment by SalahEddineGhamri** [comment]
The freeze happen too with `:sh nvim`

**Comment by dead10ck** [comment]
Is this actually a bug? I'm not sure what you expected to happen?

**Comment by GabrielDertoni** [comment]
Maybe for now it would be fine to just give EOF to these processes? It's a quick fix that sends a clear message that this sort of stuff is really not supported at the moment. #4156 implements that.

**Comment by Omnikar** [comment]
Interestingly, running `:sh xplr` with [xplr](https://github.com/sayanarijit/xplr) installed actually works and brings up the application.

**Comment by dead10ck** [comment]
> Interestingly, running `:sh xplr` with [xplr](https://github.com/sayanarijit/xplr) installed actually works and brings up the application.

Yeah, it was very surprising to me that that actually comes up at all. But it's also surprising that bash sits and waits for input, since I wouldn't expect it to be attached to a tty. Seems like if we figure out how to make it so subprocesses don't get the tty, it would probably fix this (and break xplr, but that shouldn't work anyway)
