### ISSUE TITLE
Sort diagnostics by gravity (error -> warning -> info)

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#3543]
#### Describe your feature request

When there are lots of warnings or infos in a project, the error diagnostics can be lost and hard to find in the diagnostic pickers.

They could be sorted by gravity to help go to the errors first.

**Comment by the-mikedavis** [comment]
We do this now for diagnostic icons in the gutter: https://github.com/helix-editor/helix/issues/2827

I think it would be useful to have a way to sort the diagnostics picker by severity but I'm not sure we should sorting by severity by default. Sorting by location also seems like a reasonable default, or leaving it to whatever order the Language Server gives.

**Comment by poliorcetics** [comment]
To avoid changing anything in the sort there could be a marker that can be searched for in the view, lik `[E]` `[W]` and `[I]` maybe ? Files with collisions in those names will be very rare, and diagnostic text too (though here maybe it will collide a little more but that should be manageable)

**Comment by MarijnS95** [comment]
Did #9647 close this because we can now select on severity via for example `%s(everity) error`?

Would it still be possible to consider a severity sorting _by default_ (i.e. reopening this issue)? In 99% of the cases I'd like to see errors over warnings, and having to type `%s e` each time after opening the (workspace) diagnostic picker seems tedious.

**Comment by MarijnS95** [comment]
It's now even more important because all of a sudden a `source` column was added (to distinguish `rustc` from `clippy`). Despite the `severity` column being first and `source` being second the aforementioned `%s` filter happens to search inside `source`, forcing my muscle memory to type `%se e` instead to search the `severity` column rather than the `source` column 😉
