### ISSUE TITLE
LSP contextual method help and completion dialogs overlap, former obscuring the latter

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#3545]
### Summary

![image](https://user-images.githubusercontent.com/41798/186733323-2823faf3-1351-46c4-9cda-6b30cfde3d3c.png)

Encountered in a JavaScript project: the LSP contextual method help and auto-completion dialogs overlap. The former covers the latter, making it impossible to see the full list of completions.

_(The method help is mostly getting in my way and keeps popping up again even after pressing ctrl-c sometimes as I continue to enter arguments into a method call.)_

### Reproduction Steps

Please see screenshot.

### Workaround

Press <kbd>ctrl</kbd><kbd>c</kbd> to hide the method help dialog.

### Platform

Linux (Fedora Silverblue 36)

### Terminal Emulator

Black Box

### Helix Version

helix 22.05 (e4c9d408)

**Comment by lesleyrs** [comment]
I'm having the same problem on windows 10, windows terminal, helix 22.08.1 (5b73c8c7).

This happens consistently every time a documentation message pops up, might have to do with hidpi screen?

Changing font size or window size does not change the position the doc message appears in, it's always just below the line that's being edited.

On my linux machine it correctly appears above the line.

https://i.imgur.com/sD2eiSQ.png

**Comment by lesleyrs** [comment]
z-z or z-b shortcut for changing view avoids this problem.

**Comment by Taywee** [comment]
Sometimes I can move the view around to get vision on the completion, but other times, I'm too close to the top of the buffer.  [In many cases, I can't even see whether there is a completion dialog until I hit Ctrl-n to start looking through them](https://user-images.githubusercontent.com/1069915/208151920-389e3edb-512c-4f7a-8e03-5866781a9192.png).

This is especially frustrating when passing a Rust closure into a function, because the outer function's help is always shown, [sometimes even covering the code that I am actively writing](https://user-images.githubusercontent.com/1069915/208152500-4d58802b-0d63-4130-8904-de59f63b2b01.png).

Ctrl-C can help by dropping the contextual help, though.  I wasn't aware of that.

**Comment by kirawi** [comment]
This was a duplicate issue which was solved by https://github.com/helix-editor/helix/pull/6488
