### ISSUE TITLE
panicked at 'Attempt to slice past end of RopeSlice`

### ISSUE THREAD

**Issue by AndyJado** [helix-editor/helix#3550]
0. changed my branch from another terminal window
1. I'm in a multi-window(3
2. `space + j` to jump list
3. panic!

---

```
thread 'main' panicked at 
'Attempt to slice past end of RopeSlice: slice end 2800,RopeSlice length 2179',
~/crate/src/ropey-1.5.0/src/slice.rs:645:9
```

**Comment by the-mikedavis** [comment]
I can't reproduce this. Can you create an asciinema recording of the panic or write out more concrete reproduction steps? Also, what version are you running?

**Comment by AceofSpades5757** [comment]
Using the latest version (86a8ea57bb3cb651cf9bee3fd1ae37f7e134c526), wasn't able to reproduce when changing the other file over switching branches.

**Comment by n0s4** [comment]
I can reproduce in `8deaebde`, just open a new buffer and enter the following:

<kbd>]</kbd><kbd>space</kbd>  <kbd>geggd</kbd>  <kbd>space</kbd><kbd>j</kbd>

I'm guessing it's something to do with a previous jumplist location being beyond the length of the file.

**Comment by the-mikedavis** [comment]
Thanks @n0s4! That's a really nice reproduction case 😀

That case itself is a rather small change to fix: https://github.com/the-mikedavis/helix/commit/7b691ab0d33b2992635e104247c6e67b2dba97da. The jumplist picker isn't checking the invariants of the selections in the jumplist which can lead to a panic when the selection rests on the EOF character.

Even with that fix though, we can cause further panics if we avoid the EOF character with a slightly more drastic edit: `2]<space>geggdd<space>j`. Crashes from that are also reproducible with `C-o`: `2]<space>geggdd<C-o>` which doesn't happen with your case. (The difference is that `C-o` checks selection invariants, like we do in the linked commit.)

The issue is that jumplist selections do not track document changes. You can try deleting some characters from a file and then use `C-o`: the jump point will move forward by the number of characters you deleted. I think I have a decent fix for this though, I'll make a PR.

**Comment by AndyJado** [comment]
Now I've developed a habbit of `C-s` after doing anything and do the picking in git. Next time I'll show up with a easy reproductable issued, go helix!
