### ISSUE TITLE
Strange corrupt screen when editing Rust - LSP position out of bounds error / cyclic deps: helix_view

### ISSUE THREAD

**Issue by David-Else** [helix-editor/helix#3617]
### Summary

[Screencast from 31-08-22 15:09:30.webm](https://user-images.githubusercontent.com/12832280/187699856-4d7f48e7-17a0-496e-8152-fba1506ed310.webm)

As I press enter and backspace in insert mode the ghostly `". screen...` appears, if I then go into normal mode it acts as if that line is not there and jumps over it when I navigate up and down.

Everything seems borked, but I can keep undoing until things return to how they were.

### Reproduction Steps

Not sure how to repeat it, but hopefully the video and log will be enough.

### Helix log

I included the whole log, what is in the screen shot should be covered by what is at the end of the log:

[helix.log](https://github.com/helix-editor/helix/files/9462516/helix.log)

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 22.05 (83f177d2)

**Comment by the-mikedavis** [comment]
I think this is https://github.com/helix-editor/helix/issues/2248 since it looks like it's the end of the file. The "lsp position out of bounds" looks like it may be the EOF character so it could be a off-by-one in rust-analyzer or we might not be handling it correctly. The cyclic deps message is expected - it's a false positive from the way that rust-analyzer analyzes the workspace

**Comment by the-mikedavis** [comment]
I reproduced this and it does end up being https://github.com/helix-editor/helix/issues/2248 so I'll close in favor of that. I'll have some notes to share about a fix there too
