### ISSUE TITLE
Editor becomes unresponsive editing large file

### ISSUE THREAD

**Issue by hazeycode** [helix-editor/helix#3755]
### Summary

With a large file open (8k lines in my test) and LSP running the editor can become unresponsive when making edits that invoke linting.

### Steps to reproduce
- Open a large file (I'm using https://github.com/hazeycode/brucelib/blob/987b97f3b2ce7917908b90a79609e4c8b9a3120f/modules/graphics/src/vendored/zig-opengl-exports/gl_4v4.zig) with hx
- Select and edit multiple occurrences of code and make a breaking change.
- Continue making edits. Observe editor slowdown. Can become totally unresponsive if making further batch edits.

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

0.5.0

**Comment by the-mikedavis** [comment]
I suspect this is tree-sitter and not the language server - the language server runs separately and asynchronously. Can you share the file?

**Comment by hazeycode** [comment]
@the-mikedavis that makes sense. Here is the file: https://github.com/hazeycode/brucelib/blob/987b97f3b2ce7917908b90a79609e4c8b9a3120f/modules/graphics/src/vendored/zig-opengl-exports/gl_4v4.zig

**Comment by kirawi** [comment]
By the way, Helix 0.5.0 is almost a year old. You might want to consider upgrading to 22.08.1 :)

**Comment by seongs1024** [comment]
[candles.zip](https://github.com/helix-editor/helix/files/10368453/candles.zip)

The above file's size is about 26 MB and cannot open by hx.

**Comment by pascalkuthe** [comment]
> @the-mikedavis that makes sense. Here is the file: [hazeycode/brucelib@`987b97f`/modules/graphics/src/vendored/zig-opengl-exports/gl_4v4.zig](https://github.com/hazeycode/brucelib/blob/987b97f3b2ce7917908b90a79609e4c8b9a3120f/modules/graphics/src/vendored/zig-opengl-exports/gl_4v4.zig)
> 
> edit: I have added repro steps with a link to this file above

The original issue is quite old for a very outdated version of helix. The file linked above has no performance problems in my testing.

The file linked by @seongs1024 does have some performance problems because it's very large and most all on the same line which hits some known worst cases in the rendering. Softwrap with line chunking will mitigate that in the future. However that problem is completely orthogonal to the original issue heres so will close this issue
