### ISSUE TITLE
Set-language doesn't work to provide completion

### ISSUE THREAD

**Issue by emsquid** [helix-editor/helix#3795]
When I have a new blank file and I set its language to cpp for example, it only gives me syntax highlighting, but no completion or diagnostics. In order for these to work I need to save my file as a cpp file.
I think it would be great if setting language on a new file could provide everything as a saved file.

**Comment by sudormrfbin** [comment]
Completion and diagnostics are provided by the corresponding language servers, and so the easiest way to do this would be to save the file in some temporary location like `/tmp/file.extension`.

**Comment by the-mikedavis** [comment]
If I remember correctly, we cannot use a language server for a scratch buffer (`:new` or opening helix without a path) because scratch buffers do not have URIs which LSP requires for some notifications. I'm not sure it would be safe to fake a URI since the language server may expect to be able to resolve it to a real file. I agree with saving to a temporary file as a workaround 👍
