### ISSUE TITLE
Pasted text added to next line when cursor at end of line

### ISSUE THREAD

**Issue by adrian5** [helix-editor/helix#3886]
I don't know if this is intentional, but it doesn't match my intuition about text editing. Let's say the cursor is at the very end of the line, the register contains `foo` and I pres `p` 3 times.

Expected behavior:

```
This is a line.█foofoofoo
```

Observed behavior:

```
This is a line.█
foofoofoo
```

If I move the cursor 1 char to the left onto the `.`, the behavior is as expected.

**Comment by n0s4** [comment]
This is expected because newlines are selectable in Helix. You can see this if you `whitespace.render.newline = "all"` in your config.toml. If you paste after the newline then the text is naturally pasted on the next line.

You can <kbd>gl</kbd> then <kbd>p</kbd> or just use <kbd>P</kbd> to paste before the newline.

**Comment by adrian5** [comment]
I see, so the cursor is kind of between the lines in that case, or on the char before the next line, so to speak. If this is by design, I reckon this issue can be closed. I'll leave this up to the mods (in case this relates to any open issue/debate).

**Comment by the-mikedavis** [comment]
Yeah this is expected behavior. When the cursor is on the end-of-line, pasting with `p` pastes after the end-of-line character which means that the text ends up on the next line. `P` would be the way to paste on the line here
