### ISSUE TITLE
Async job results only show up after the next keypress

### ISSUE THREAD

**Issue by archseer** [helix-editor/helix#402]
@jneem after https://github.com/helix-editor/helix/pull/285, pressing `gd` or `K` will appear as if nothing happened, then once the next input is entered `j`/`k` etc. the view will refresh and the popup appears. It seems like a rendering issue, but it might be `next_job` returning None too early.

**Comment by archseer** [comment]
Yeah I think it's an issue with `futures::select`. The callback only appears in the event loop after a second input.

**Comment by jneem** [comment]
Hm, sounds like this might be annoying to debug. Maybe I can check when the job's future is getting polled? Or maybe I should be spawning a task instead of just relying on the select macro? There is something in the select docs about that, but I have to admit that I don't fully understand the implications...

Unfortunately I can't play with this tonight, but I'll try to do it sometime this weekend.

**Comment by archseer** [comment]
I'm debugging it right now, the problem is that the stream future immediately returns `None`. `tokio::select` avoids this if you poll the stream directly, but it re-surfaced now that it's wrapped in a method.

`select_next_some` is what we want to use but I'm still trying to get it to work with `tokio::select`
https://docs.rs/futures/0.3.15/futures/prelude/stream/trait.StreamExt.html#method.select_next_some

**Comment by archseer** [comment]
I pushed a temporary fix: https://github.com/helix-editor/helix/commit/83e7dd860209ac3f0ccfa40ba98f7c314fa2b186

Need to document this behavior and make sure to audit the event loop if any changes are made.

**Comment by archseer** [comment]
I'll mark this as resolved for now.
