### ISSUE TITLE
Append cursor positioning is not consistent during editing

### ISSUE THREAD

**Issue by trink** [helix-editor/helix#4074]
### Summary

Append fails to position the cursor at the end of the selection

### Reproduction Steps

1. open hx
3. type `itest<esc>ba` # insert test, enter normal mode, back select the word, and append
4. the cursor will be properly positioned after the last 't'
5. `<esc>xditest<esc>ba` # delete the line and do it again
6. the cursor will now be positioned between the 's' and the 't'

### Helix log

nothing reported in the log

### Platform

Linux

### Terminal Emulator

st 0.8.5, gnome-terminal (GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### Helix Version

helix 22.08.1 (6caa7a7f)

**Comment by dead10ck** [comment]
Confirmed. It looks like this happens because there is no final line feed. When the cursor is on the last character, helix inserts a new line feed and positions the cursor correctly, but it seems that it does not do this if the head of the selection is not on the last character of the document.

**Comment by 4mishra** [comment]
This issue also seems to be present with my XFCE terminal emulator. I'm working on it to fix the issue

**Comment by ErdoganSeref** [comment]
The error doesn't occur when there is an empty line below. `extend_line_below` causes the issue because after the selection `d` deletes the newline.

**Comment by Manosmer** [comment]
I would like to add some more findings on this. In Normal mode and with the final '\n' removed (`<Esc>xditest<Esc>`), when the cursor is at the right-most position (the space after the word "test") both append `(a)` and insert `i` work as _expected_, meaning they transition to Insertion mode right at the end of the file. However, when the cursor is on the last letter of "test", append seems to add a new line automatically. The same behaviour can be seen when selecting with `b` as opposed to `w`. By selecting with `w` and then appending, Helix adds a new line automatically to the end of the file. I think this could be classified as undesired behaviour in cases where the user simply did not wish to add the newline character at the end of the document. Moreover, it is also a matter of consistency since the new line is not added with the aforementioned way if there is already another line after the current.

Platform/Emulator: MacOS/iTerm2
