### ISSUE TITLE
Phantom Line

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#415]
### Reproduction steps

1. Open `helix/helix-view/src/graphics.rs`
2. Scroll to LN 3

### Environment

- Platform: Windows
- Helix version: d02bbb7baec13e4d3c7ae0094431f2a20526cf18

### Details

When trying to scroll down to LN 3, I noticed that a phantom new line would appear in its place, and then go away once you scroll off.

![Capture](https://user-images.githubusercontent.com/67773714/124404960-1c0e2580-dd0b-11eb-93fe-f305b96026db.PNG)

**Comment by archseer** [comment]
Note: `graphics.rs` has CRLF line endings

**Comment by archseer** [comment]
Moving the cursor over any line ending in the file causes this.

@cessen I'm guessing my selection rendering code needs to use that grapheme alignment function you recently added?

**Comment by cessen** [comment]
That sounds plausible.  If the cursor is one-wide, and it falls on either of the two crlf characters, and the cursor highlighting isn't being extended to the prev/next grapheme boundary, then the cursor highlighting would probably split it, yeah.

Incidentally, I just tested it out with my Great Cleanup branch, and it's apparently already fixed there.  Which makes the above explanation even more likely, since everything gets aligned to grapheme boundaries in my branch, even in the highlighting code.

I think that means the issue is here, with all of the `+ 1`'s instead of finding the next grapheme boundary:

https://github.com/helix-editor/helix/blob/fc34efea124c23285770f9bd2e23dbcb905a6965/helix-term/src/ui/editor.rs#L190-L203

I'll tackle this, if that's okay.

**Comment by cessen** [comment]
Incidentally, I think we're just slowly uncovering a bunch of grapheme handling bugs via CRLF, since it's the only common grapheme that comes up in code.  It might be faster to find these bugs by testing with some text designed to stress-test grapheme handling.  Maybe something like [Zalgo text](https://en.wikipedia.org/wiki/Zalgo_text).  I might take a crack at that at some point if no one else gets to it first.
