### ISSUE TITLE
Want lock files

### ISSUE THREAD

**Issue by gdamore** [helix-editor/helix#4257]
I frequently make a mistake when using hx that I don't make with vi.  That mistake is that I open a duplicate instance of hx on the same file.

This causes me all kinds of grief, because I can occasionally switch to a window running an instance editing an older version of the file.  If I then write out content, the resulting data overwwrites what was there.

What I'd like is one, or both, of two different behaviors (could be enabled via opt-in):

1. When starting hx on a file (or opening a file), create a lock or swap file, and complain if trying to open a file that is already being edited. 
2. Detect when a file was edited out band (stat the file before saving and make sure that the last modified time is not changed from when it was read, for example).  This should give a warning, and ask the user whether to write the file anyway, abandon the change and reload from on-disk, or possibly other actions (do nothing, make a backup, etc.)

Sometimes vi/vim are a pain in this regard, but really they are saving my bacon, and I miss this protection from helix.   This is a must have feature IMO.

**Comment by pathwave** [comment]
There was also some talk about having a helix daemon, in that case opening a file in another instance could instead give a view into the same file (in memory)

**Comment by Ordoviz** [comment]
I hate Vim's swap file messages when I just want to *view* a file. Kakoune doesn't use lock files, but this was never an issue for me, because it detects when a file was modified externally (#1125).

**Comment by kirawi** [comment]
#312 will resolve this as well.

**Comment by gdamore** [comment]
#312 *might* fix this, if you're using the client/server model. But my thoughts here are:

1. Do I *have* to use the client/server model?
2. What if someone starts another server?
3. Forcing the solution for this (which should be a small problem to solve) to rely on the client/server (which is almost certainly a much larger architectural piece of work) seems misguided.

So I'd rather see a fix for this sooner.

Btw, for bonus points, it would be kind of cool if helix could detect the presence of a vim swap file too.  I still go back and forth (which is kind of brain warping) and in an environment with multiple people (think an /etc/ file on a server) it would be a nice feature to detect when it's likely someone else is working on the same file.

**Comment by edrex** [comment]
My take:
- Lock files are more trouble than they're worth
- Go with option 2 in OP, reload on external change is coming ([File watcher implementation & LSP DidChangeWatchedFiles notification by kyrime · Pull Request #2653 · helix-editor/helix](https://github.com/helix-editor/helix/pull/2653), watch https://github.com/helix-editor/helix/issues/1125)
- Server will also help with sync across windows, but option 2 is important because sometimes other programs change files.
- Autosave option helps here too, already implemented.

Suggest closing this in preference to #1125.

**Comment by ardijanr** [comment]
I disagree with the server thing. swap and history recovery with reloading changed files would solve all of these issues.

**Comment by pr2502** [comment]
Adding a me2, I've just accidentally overwritten a good chunk of my work by saving a very old buffer from a forgotten window over the current one.

**Comment by pascalkuthe** [comment]
This was addressed by using mtime based detection to prevent overwrites and also by making sure writes are atomic so there are no partial write races. An even better solution will be eventually #1125 so closing favor of that.

**Comment by videoMonkey** [comment]
I decided to learn vim because it was installed by default on every server I'm supposed to manage, then I go excited about plugins and tried neovim and well, I got overwhelmed with plugins and customizations. I had heard about helix and decided to give it a serious test drive. I want to have just one text editor that I can do all my writing (code and otherwise) in. Helix feels just right. 

Two days ago I spent a few hours writing a blog post when the kids needed attention. I put my laptop down and the battery died. I lost an hour of unsaved editing. Color me disappointed, vim never lost my work like that. 

That said, I see an auto-save setting. I am going try and figure out how to turn it on for just markdown and text files. I don't necessarily need lock files, but I would like to be able to recover buffers in the event life happens.
