### ISSUE TITLE
Failed to build grammars on Windows 11

### ISSUE THREAD

**Issue by milssky** [helix-editor/helix#4263]
Hey!

I'm trying to build tree-sitter grammars on Windows 11. In PATH has gcc, g++, clang. But after running `hx --grammar build` I get errors:

```log
Failure 0/107: Failed to execute C/C++ compiler
Failure 1/107: Failed to execute C/C++ compiler
Failure 2/107: Failed to execute C/C++ compiler
Failure 3/107: Failed to execute C/C++ compiler
...
```

What is wrong?

**Comment by CptPotato** [comment]
Maybe it tries to invoke the MSVC compiler instead of cc.

Did you download a pre-built binary or build helix from source?

**Comment by milssky** [comment]
I installed helix via chocolatey

`helix 22.08 (ee94031f)`

**Comment by CptPotato** [comment]
I'm not very familiar with how grammars are built, but it looks like they invoke the same compiler (MSVC or cc) that helix was built with:

https://github.com/helix-editor/helix/blob/01ee42bb149adee2fe17561806d9525370c84ef4/helix-loader/src/grammar.rs#L431-L439

Since the helix binaries on Github are built with MSVC it seems like it tries to invoke MSVC which it can't find.

**Comment by milssky** [comment]
Heh. You are right ;) For building grammar sources need MSVC

**Comment by CptPotato** [comment]
If you *really* want to sidestep MSVC completely you can try building helix from source using the gnu toolchain (targeting `x86_64-pc-windows-gnu`). However I have never tried that, so you might run into some issues.
