### ISSUE TITLE
Rename buffers

### ISSUE THREAD

**Issue by cor** [helix-editor/helix#4393]
It would be very nice if you could rename buffers from Helix.

For example, I'm editting `a.txt` within a project, and i need to rename it to `b.txt`. 
Currently, you would:

- `<space>f` -> `a.txt` 
- `:w b.txt`
- quit helix
- `rm a.txt`
- open helix
- `<space>f` -> `b.txt`

It would be much nicer if we had a rename command from within helix, so that you could simply:
- `<space>f` -> `a.txt` 
- `:buffer-rename b.txt`

*the buffer is now renamed to b.txt, while it is still open in your editor*

**Comment by cor** [comment]
I don't have sufficient permissions in order to add labels, but this seems like a good first issue to me :)

**Comment by geometryolife** [comment]
There is also a slightly more complicated way what run shell commands in Helix:
```
:run-shell-command mv old_file_name new_file_name
```
I also agree with adding a build-in command or shortcut for Helix to change the file name.

**Comment by Elias-Graf** [comment]
Does this also rename references to the given file in code? I think https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles is relevant.

That is also why @geometryolife suggestion does technically achieve renaming the file, but wouldn't accomplish what I would be expecting it to do.

**Comment by austinletson** [comment]
@cor @Elias-Graf there seems to be some discussion in the above linked issues as to what operations involving file management should be included in the editor as opposed to externally. What if instead of creating a new file/buffer and deleting the old file, there was a command that started a new buffer and saved the old buffers content to the new buffer but didn't delete the source file for the old buffer.

This is similar to the way `:saveas` works in vim: https://vimdoc.sourceforge.net/htmldoc/editing.html#:saveas

It seems like `:write <file-name>` already achieves this though. If I open a file and write to a different file, the buffer is renamed.

**Comment by cor** [comment]
@austinletson in my opinion this really should be included in the editor. People primarily use Helix for creating code, and this process almost always involves renaming, deleting, and moving files. `:saveas` and `:write` are inferior solutions since they require the user to still manually delete the old file.

Also, like @Elias-Graf mentioned, this does not rename references to the file, which it should do.

**Comment by ontley** [comment]
Well I implemented the command, now to wait for it to hopefully get merged
