### ISSUE TITLE
Allow "" to act as a pair for mim

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4475]
If you have the text `("yoo█oo")` with your cursor placed in the middle and use `mim`, it will select inside the parens instead of inside the quotes. Expected result is to act inside the quotes 

helix 22.08.1 (66276ce6)

**Comment by matoous** [comment]
Would require `"` to be added as a pair here: https://github.com/helix-editor/helix/blob/master/helix-core/src/surround.rs#L6, nothing more is needed afaik.

**Comment by dgmulf** [comment]
Perhaps `mim` should automatically work with all pairs defined in the `[editor.auto-pairs]` config key?

**Comment by lukepighetti** [comment]
> Would require `"` to be added as a pair here: https://github.com/helix-editor/helix/blob/master/helix-core/src/surround.rs#L6, nothing more is needed afaik. While at it, ` and `'` might also be good candidates.

Interestingly, I did try that, but after compile it wasn't working. I noticed that we have no cases where open and close characters are identical, and I wonder if the existing code is not setup to handle this case.

**Comment by matoous** [comment]
@lukepighetti your are right. I will try to take a look over the weekend 👀

**Comment by lukepighetti** [comment]
Looks like @sudormrfbin was the last to touch this part of the codebase. Maybe he has some tips for us.

**Comment by asvln** [comment]
> Interestingly, I did try that, but after compile it wasn't working. I noticed that we have no cases where open and close characters are identical, and I wonder if the existing code is not setup to handle this case.

Note for future implementors, adding any character pair (same or not) to the `PAIRS` const in `surround.rs` does not make them work with `mim`.

**Comment by phlawlessDevelopment** [comment]
I've been having a look at this, the issue seems to be that the proposed "pairs" (",',`) are all identical pairs (as opposed to [ + ] etc). I'm slowly log::warn!ing through the code to try and wrap my head around how the parsing works.. Whatt would be valuable is if someone could point me towards the part of the source that deals with mi" (because I presume that has a solution to the searching for matching pairs problem (and it's hard to search for without any clues)

**Comment by thomasaarholt** [comment]
This doesn't seem completely fixed yet. Here I show examples in python and rust on the latest master.

https://asciinema.org/a/WrbzIbd6kgpuGrjLbLWCNrIaZ

I have working LSPs for both languages.
```
❯ hx --health python
Configured language servers:
  ✓ pyright-langserver: /opt/homebrew/bin/pyright-langserver
  ✓ ruff-lsp: /opt/homebrew/bin/ruff-lsp
Configured debug adapter: None
Configured formatter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

```
❯ hx --health rust
Configured language servers:
  ✓ rust-analyzer: /opt/homebrew/bin/rust-analyzer
Configured debug adapter: lldb-dap
Binary for debug adapter: 'lldb-dap' not found in $PATH
Configured formatter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

**Comment by woojiq** [comment]
@thomasaarholt hey, thanks for the reproduction steps.
I agree with @pascalkuthe. But anyway thanks for detailed asciinema, I see some inconsistency in the new behavior. I will look at the weekend.

**Comment by thomasaarholt** [comment]
@pascalkuthe, the main reason I didn't create a new issue was that this one was closed 48 hours ago. I was honestly worried about being told off for making a new issue, which is why I commented here. 🤷 
Thank you for identifying for me that `mm` is a problem with Python.

@woojiq, thank you! I really appreciate your contribution, it's one that makes helix feel even more intuitive to me!
