### ISSUE TITLE
Grammers are not bundled with the embedded runtime

### ISSUE THREAD

**Issue by luctius** [helix-editor/helix#451]
Syntax highlighting stopped working for me at commit dd2903f.

I have tested v0.3.0-85-gdd5e808, v0.3.0-86-gdd2903f and v0.3.0-93-g0b1ed86, and only with the first did it still work.

**Comment by archseer** [comment]
You're likely missing the grammars under runtime/grammars. Make sure to do a clean rebuild of helix-syntax and check they're there. If you're using a custom HELIX_RUNTIME path you also need to make sure the grammars are copied/symlinked there.

**Comment by luctius** [comment]
You are correct; copying the grammers fixed it.

However, I compiled with the embedded runtime feature; shouldn't the grammers be included then?

**Comment by kirawi** [comment]
> You are correct; copying the grammers fixed it.
> 
> However, I compiled with the embedded runtime feature; shouldn't the grammers be included then?

Currently they're not bundled, I'm hoping to submit a PR soon to fix that.

**Comment by kirawi** [comment]
Current discussion has pivoted towards potentially removing the `embed_runtime` feature.

**Comment by kellytk** [comment]
@kirawi @archseer FWIW, as a potential user, removing the embedded runtime feature was a regression from a usability standpoint.

**Comment by archseer** [comment]
The embedded runtime wasn't practical enough to keep around. With the grammar split it would have required us to rearrange the build so that helix-syntax grammars are built before they get embedded into the binary. The grammar loader `libloading` isn't able to consume embedded dynamic libraries either.

I don't think it's that hard to set an environment variable pointing to a folder somewhere, it's what other editors do. If you're using a packaged release it should be handled for you out of the box.
