### ISSUE TITLE
Removing a bracket removes more than one bracket

### ISSUE THREAD

**Issue by Jomy10** [helix-editor/helix#4544]
### Summary

In this short video, I delete a closing bracket, but it also removes the closing bracket to the right of it.

https://user-images.githubusercontent.com/62475953/199091930-8ad682cc-40cd-42ee-b7e5-ed9df4ef140b.mov

### Reproduction Steps

type something like `(())` in helix. Remove the third bracket with backspace, the last one will disappear as well.

### Platform

macOS

### Terminal Emulator

iTerm2

### Helix Version

helix 22.08.1 (f41f28b6)

**Comment by David-Else** [comment]
This problem trips me up often too.

**Comment by ygabuev** [comment]
https://github.com/helix-editor/helix/pull/4558 is the change that fixes the issue.

However, there is still a problem with AutoPairs: they are annotated to be keyed by the opener: https://github.com/helix-editor/helix/blob/8ff92c749287fb3ac4a68661d0ee99cb56cc6295/helix-core/src/auto_pairs.rs#L19-L22
but the `new()` method also adds closers as keys: https://github.com/helix-editor/helix/blob/8ff92c749287fb3ac4a68661d0ee99cb56cc6295/helix-core/src/auto_pairs.rs#L90-L91

This might be the issue why the bug was introduced in the first place - the contributor assumed that there are no closers in the list of keys of an AutoPairs instance.
