### ISSUE TITLE
Alt-` keys on gnome linux 

### ISSUE THREAD

**Issue by kynrai** [helix-editor/helix#4850]
I have been having issues trying to use the Alt modifier for actions like Alt-`
In gnome, that is the key combo for switching window instances. This overrides all windows open in gnome. 

I understand this is not a helix issue but it affects the use of helix on arguably one of the most commonly distributed linux DE.

Is there any known workaround for this, ive tried various terminal emulators on a clean install of gnome 42, same issue.

**Comment by archseer** [comment]
Are you also using gnome terminal?

**Comment by archseer** [comment]
https://askubuntu.com/questions/30224/how-to-disable-the-alt-hotkey-behavior-on-gnome-terminal

**Comment by Ordoviz** [comment]
This issue isn't related to Gnome Terminal. The <kbd>alt</kbd>+<kbd>&grave;</kbd> key combination is bound in gnome-shell to switch windows; in Helix it is bound to `switch_to_uppercase`. A solution would to change Helix's default keymap to match Kakoune's:

```toml
[keys.normal]
"`" = "switch_to_lowercase"
"~" = "switch_to_uppercase"
"A-`" = "switch_case"
```

With this mapping, Gnome users don't have access to `switch_case`, but this isn't a big deal since `switch_to_lowercase` and `witch_to_uppercase` can be used to emulate it.

**Comment by kynrai** [comment]
> One of the first results on google for "alt key terminal gnome" https://askubuntu.com/questions/30224/how-to-disable-the-alt-hotkey-behavior-on-gnome-terminal

Saw that when i googled and as shown by the comments the info does not work, I ended up using @lesleyrs tip, turns out gnome has many hotkeys set for the same actions, notable Super+` as well as Alt+` so disabling all the alt bindings works

Thanks for the help everyone!

**Comment by jw013** [comment]
Tip: in many *nix terminals a single key chord using the Alt key can also be input as the 2-chord sequence `Esc` followed by the original key combo without Alt.
