### ISSUE TITLE
Cursor jumps on `:reload-all`

### ISSUE THREAD

**Issue by mchlstckl** [helix-editor/helix#4884]
### Summary

When I do `:reload-all`, the content of the window jump. Sometimes the cursor is positioned at the top of what looks like a blank buffer, but scrolling up reveals the contents of the file.

Note that the file I'm looking at has not changed.

### Reproduction Steps

 

I tried this:

1. `hx`
2. Open some file
3. Do `:reload-all`

I expected this to happen:

Contents to be reloaded from disk. Cursor remains in current position.

Instead, this happened:

Contents reloaded from disk. Cursor jumps to random(?) position.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

kitty

### Helix Version

helix 22.08.1 (e6dad960)

**Comment by David-Else** [comment]
@mangas  it seems like `reload-all` has problems as it is reported to panic too https://github.com/helix-editor/helix/issues/4878 , could you take a look?

**Comment by mangas** [comment]
I am not able to replicate this. Can you maybe create an example with a few files where this happens? Or maybe a repo that you were using?

**Comment by mchlstckl** [comment]
This happens when I edit Go files. 

I use `gopls`, and `golines` for formatting. 

I use Helix at work so I don’t currently have any example files or repos to share. I’ll try putting something together that triggers this that I can share.

**Comment by mangas** [comment]
awesome, thanks !

**Comment by mchlstckl** [comment]
I checked out https://github.com/GoogleCloudPlatform/cloud-sql-proxy repo in order to reproduce this bug.

1. `hx`
2. Open `cmd/root.go`
3. Split window into left / right
4. Open `internal/proxy/proxy.go` in right window
5. Move cursor in right window line 35
6. `:reload-all`
7. Contents of right window shift up so that line 35 is now 6 lines from the top of the window

Where to move the cursor in step 5. and what happens at step 7. seem a bit random to me.

I tested this in kitty and iTerm2 and I get the same behaviour in both.

Let me know if you need any more info.

*config.toml*
```
theme =  "onelight"

[editor]
rulers = [100]
cursorline = true
color-modes = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false

[keys.normal]
"esc" = ":wa"
C-r = ":reload-all"

[keys.insert]
C-p = "signature_help"
```

*languages.toml*
```
[[language]]
name = "python"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = ""
formatter = { command = "poetry", args = ["run", "black","-"]}
auto-format = true

[[language]]
name = "go"
formatter = { command = "golines"}
auto-format = true
```

**Comment by mangas** [comment]
@mchlstckl I'm unable to replicate this on linux :thinking: @the-mikedavis any ideas?

**Comment by gabydd** [comment]
I wonder if this stems from formatting?

**Comment by the-mikedavis** [comment]
I can reproduce: 
![bug](https://user-images.githubusercontent.com/21230295/204067083-d90c83f9-a0ce-47ee-bcd5-d495b68a098c.gif)

You need a short enough terminal size to see the jump.

The problem is calling `View::ensure_cursor_in_view` for all `view_id`s. `View::ensure_cursor_in_view` moves the viewport to ensure that the given document's cursor is visible. In the reproduction case, when reloading the right-hand side split, we first ensure that the cursor for `root.go` (on line 1) is in view, then ensure that the cursor for `proxy.go` (on line 35) is in view. This shifts the view so that the cursor is at the bottom of the visible viewport (minus scrolloff).

We should only call `View::ensure_cursor_in_view` if the view is currently looking at the document (`view.doc == doc_id`). We lazily ensure that the cursor is in view when we switch a view to look at another document in `Editor::replace_document_in_view` (called from `Editor::switch`) so it's only necessary to update the view if it's currently focused on the doc.

**Comment by mangas** [comment]
@mchlstckl @the-mikedavis can you please test https://github.com/helix-editor/helix/pull/4901 and let me know if you can still replicate the behavior? I wasn't able to replicate locally but I think this may fix it according to Mike's explanation

**Comment by mchlstckl** [comment]
I checked out your branch and installed `hx` from it. I went through the reproduction steps. The window no longer jumps. Looks good to me!
