### ISSUE TITLE
Un-flatten LSP symbol picker with a tree view.

### ISSUE THREAD

**Issue by weakphish** [helix-editor/helix#5048]
> LSP supports hierarchical symbols, but helix currently flattens then into a list and shows them with `space+s`. We could reuse the tree view that will soon be merged with the file tree (#2377) to display the symbol information in a tree interface.

> Another option is to use [tree sitter tags](https://github.com/tree-sitter/tree-sitter/tree/master/tags) instead of LSP (not sure if it can report hierarchical information).

> _Originally posted by @sudormrfbin in https://github.com/helix-editor/helix/issues/2425#issuecomment-1120257741_

Another idea that I would like to explore is adding NerdFont symbols _optionally_ to add a bit of visual flavor. This would be opt-in through an explicit TOML configuration.

**Comment by pascalkuthe** [comment]
Discussed with @the-mikedavis . A tree view doesn't work well with the picker because fuzzy matching always resortd the list (and isn't super useful when it doesn't). In general tree doesn't really fit in with the picker.

Thisbkind of feature would require a dedicated ui like discussed in #2425 . Closing in favor of that issue
