### ISSUE TITLE
Underline styles doesn't work on Konsole despite them being supported by the terminal

### ISSUE THREAD

**Issue by Kenneth-Mata** [helix-editor/helix#5227]
### Summary

I'm on arch linux, with the lastest release of Konsole ( 22.12 funnily enough) and it supports all underline styles that Kitty does 

### Reproduction Steps

 

I tried this:

1. `hx Program.cs` with lsp running and curl configured in underline with `'diagnostic.info' = { underline = { color = 'green-alt', style = 'curl' }}`

I expected this to happen:
![2022-12-19_21-48](https://user-images.githubusercontent.com/92641443/208555798-3aa71e59-c01f-488e-bb39-eda714afc6da.png)
(sample photo using a patched st build with undercurl support)

Instead, this happened:
![2022-12-19_21-50](https://user-images.githubusercontent.com/92641443/208555933-253e8696-d442-4eb9-9110-0c099c12b6bf.png)

Konsole does support all [kitty](https://sw.kovidgoyal.net/kitty/underlines/)  underline styles as of the most recent build 
![2022-12-19_21-53](https://user-images.githubusercontent.com/92641443/208556245-3a121e49-ff01-4076-8e2a-e18d85e36723.png)

### Platform

Linux (Arch)

### Terminal Emulator

Konsole 22.12.0-1

### Helix Version

Helix 22.12-1

**Comment by the-mikedavis** [comment]
This is probably from the extended underline capability detection: https://github.com/helix-editor/helix/blob/98c121c9fc9d9dbc058120ede9700c0e0bbc5551/helix-tui/src/backend/crossterm.rs#L18-L50

Do you have Konsole's terminfo installed? As a workaround to trigger detection you could set `$VTE_VERSION` to `5102`.

We have a workaround for WezTerm where we look at `$TERM_PROGRAM` but that might not be a good fix for Konsole since it has only had extended underline support since its 22.04 release https://bugs.kde.org/show_bug.cgi?id=387811 (so many Konsole users might be running an older version)

**Comment by Kenneth-Mata** [comment]
I'm looking around in my files and google but can't find a concrete terminfo for it, i tried setting `VTE_VERSION=5102` in a session and then doing `hx Program.cs` from there but didn't work

**Comment by Kenneth-Mata** [comment]
Hi, i'm having this issue again when trying to use Helix 23.03 from the .desktop file, i tried setting ```env VTE_VERSION=5102``` in the ``Exec`` and ``TryExec`` blocks to no avail (also exporting it in my .bashrc)

**Comment by Kenneth-Mata** [comment]
Fixed it by overriding the envvar in the konsole.desktop file, closing now
