### ISSUE TITLE
reopen issue, feature request :dq => Discard changes and Quit

### ISSUE THREAD

**Issue by 6lj6** [helix-editor/helix#5282]
Sorry, I'm having a hard time understanding you. Thanks for your suggestion, but I'm going to close this.

_Originally posted by @dead10ck in https://github.com/helix-editor/helix/issues/5271#issuecomment-1364541514_

**Comment by 6lj6** [comment]
If I don't have time understanding something, I won't throw it away, I may leave but won't destroy it.

Let someone who can understand it to handle this issue.

**Comment by 6lj6** [comment]
update:
1. I don't need thanks or sorrys.
2. I am not saying closing issue is not right.
3. I am saying reasonable reason. Just leave a reason to close this which is reasonable, like low priority, like may optimize these concepts in tutor, like no need learning new cmd, BUT CAN'T BE THAT "Having a hard time understanding me", you could choose to not understand instead closing it. If you waste the power and the rights that helix gave to you about closing Issue, then I will waste the rights on reopening the issue.

**Comment by 6lj6** [comment]
Come back to the main topic.
1. <kbd>:dq</kbd> is more consistent with <kbd>:wq</kbd> than <kbd>:q!</kbd> with. Consistency means less confusion, less memory burden , less operation err, less learning time, 
2. <kbd>:d</kbd> will became a single atom operation, like <kbd>:w</kbd> and <kbd>:q</kbd>, can't be more elegant. Let's compare it to ugly <kbd>:q!</kbd>
3. [dead10ck](https://github.com/dead10ck) said that "visual indicator". It is not true, reasons are as follows:
    1. Users hardly watch the bottom bar when they quit the helix, does't it?
    2. <kbd>:wq</kbd> is also a risky operation, cuz it broke the original text, but there is no ! in <kbd>:wq</kbd>. How can <kbd>:dq</kbd> need an exclamation while <kbd>:wq</kbd> need not?
4. Less is more.
    1. less press time on keyboards, it will protect our fingers. Though it is small, but we can improve similar key designs to make it better and better.
    2. less modals of learning, Discard changes or Write changes or with Quit. Like rust to C++. What existed is not the best, e.g. the ugly <kbd>:q!</kbd>
5. for more info about this design, more pros and cons, go check the issue that was closed by @dead10ck => #5271

**Comment by gabydd** [comment]
For number 2. :reload already exists for discarding changes, the benefit reload has over just discarding the changes to a document is you can undo the reload and still have your past undo states as well meaning you don't lose work if you :reload something and realize you want to go back. Moving on to the rest of the issue I think the best solution is either configurable aliases for commands or being able to create custom commands. Then you would be able to configure ``:dq`` to being ``:write-quit!``\``:wq!`` (I think there is an issue for custom commands, I'll edit this when I find it). It's valid to prefer a different command name for doing something, but we can't realistically provide everyones preference in core, that's why there is configurable keybindings and when someone gets the time to do it configurable commands.

**Comment by 6lj6** [comment]
The issue also reflects the fact that there is no serious designing process of helix, all concepts and patterns mixed up in a chaos logic. It drive us to face so many new issues to rethink and optimize the original code. 

Your practical explanation is admirable. It is you so that more and more people will be attracted to join helix. 

I'm going to offer my views and tutor materials with next movement on more reading about docs, tutor and rearrange about the concise models that helix uses. It may help people to find a beautiful way to learn, think and use helix. 

See you in next issues.

**Comment by 6lj6** [comment]
Good idea about "configurable commands".

Since helix support a color theme, it can also offer a cmd theme, kbd binding theme to customize in the settings.

**Comment by gabydd** [comment]
I think the most actionable part of this issue is explaining how ``:q`` and ``:q!`` work better in the tutor, I agree this can be a bit confusing to beginners. What I think could work well is an explanation of how buffers and views work, could probably be a whole chapter in the tutor. With an understanding of buffers and views quiting can be explained better, as well as close and quite all. And yes I think this issue can be closed and I or you can open a new issue about the tutor stuff.

**Comment by archseer** [comment]
> Good idea about "configurable commands".

We will probably support custom `:command` bindings in the future yeah. It should work similar to keybinding
