### ISSUE TITLE
ge jump to eof rather than last line in file

### ISSUE THREAD

**Issue by pickfire** [helix-editor/helix#529]
### Reproduction steps

 
`ge` jump to last line without line number (eof) rather than last line with line number. Behavior is different from kakoune, IIRC this wasn't an issue in the past. Probably happen after the great line ending refactor. cc @cessen 

I think the behavior of `j` changed as well maybe. It shouldn't be able to navigate to the last `~` line.

### Environment

- Platform: Linux mi 5.13.5-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 25 Jul 2021 18:03:00 +0000 x86_64 GNU/Linux
- Helix version: v0.3.0-199-ge6e0d31

**Comment by cessen** [comment]
This behavior was intentional, because it seems correct to me.  What's the reason for not going to the end of the text?

**Comment by kirawi** [comment]
This is what VSCode does as well.

**Comment by pickfire** [comment]
Both vim and kakoune doesn't do this. It is annoying to me such that I want to go to the last line I need to do `Gk`. I mean it should  behave like `gl` where it doesn't go to the last line. I am okay to use `Gj` to go to the eof part or disable the eof part. But I wish `G` can do `Gk` currently so I can do `Go`.

**Comment by cessen** [comment]
> I mean it should behave like `gl` where it doesn't go to the last line.

Thinking about it more, I think we should probably support both behaviors.

We already have two commands for "end of line", one of which goes to the character before the line ending (if there is a line ending), and one of which goes past that character.  Both are useful behaviors.  When I want to start typing at the end of a line, for example, I want it to go *past* that last character to the actual end of the line.  But if I'm making a selection, I probably want it to stop at that last character.

So we could do the same thing here.  Have a command that goes to the actual end of the text data (the current behavior), *and* one that goes to the end of the last non-empty line (what I think you're asking for).

I'm also okay with the latter being the default key binding.  I just want to make sure that a command for actually properly going to the end of the text data is also available, since that's also a fundamental command, I think.

Does that sound reasonable to you?

**Comment by pickfire** [comment]
As long as I can go to end of file (like vim and kakoune) within 2 keystrokes I am happy with it.

**Comment by archseer** [comment]
>  (like vim and kakoune)

Note: vim's `G` matches our `ge` behavior (it jumps to the last line)

**Comment by pickfire** [comment]
> So, in summary, the behavior would be to go the last non-~-labeled line, as Helix currently labels things.

That is exactly what I wanted to see. IIRC the previous behavior in helix wasn't like that or I am wrong.

**Comment by cessen** [comment]
@pickfire Awesome.  Just made a PR for it. :-)
