### ISSUE TITLE
Detect truecolor support with terminfo

### ISSUE THREAD

**Issue by pascalkuthe** [helix-editor/helix#5319]
Followup to #5312 which was closed before I could comment.

Detecting truecololor support is a complete mess and sadly non standardized. There are multiple semo stanard methods and we probably want to support them all to be on.the save side:

* [x]  `COLORTERM` based detection
* [ ] using the nonstandard  `setrgbf`/`setrgbb` terminfo capabilities (commonly used in practice like in nvim)
* [ ] using the standard terminfo `RGB` capability (support since ncurses 6.1 whixh is sadly rarely used as its mutually exclusive with 256 color support. (See kovidgoyal/kitty#1141 for some discussion)
* [x] a manual setting in case everything else fails (for example when using helix over ssh for some reason)

We handle undecurl support similarly (check both nonstandard capabilities and environment variables) and use termini for that. The same thing should be possible/easy to accomplish for this case (the setting could be implemented later)

**Comment by kirawi** [comment]
By the way, a setting already exists as `config.editor.true-color`.

**Comment by eliasp** [comment]
I'm using:
- Windows Terminal (1.17.11461.0)
- Win11 on the client
- CentOS 9 on the server, where I use Helix
- Helix 23.05

I launch `ssh.exe` directly within my Microsoft Terminal profile without going through `cmd` or `pwsh` first and connect straight to the target system running CentOS9.

By default, `$TERM` is `xterm-256color`.
My Helix config contains `config.editor.true-color = true`

Trying `:theme monokai` still claims `theme requires true color support`.
Explicitly setting `$COLORTERM` changes nothing.

Anything else I could try or any debug data I could provide?

**Comment by nkitsaini** [comment]
Hi @eliasp, if you have set `config.editor.true-color = true`, you should not see `theme requires true color support` error message.

I am guessing that your config might be on your windows machine instead of CentOS (where helix is being run).

Can you try running `:get true-color` in helix to see if the value is correctly set in config? If this is false you can use `:set true-color true` to override the value and check if that works.

Also you can try  `|env` (`<pipe>` followed by `env`), to check what environment variables are visible to `helix`.
