### ISSUE TITLE
Workspace Symbol picker does not work for Golang gopls

### ISSUE THREAD

**Issue by smit2909** [helix-editor/helix#5342]
The default keymap of <space> S does not open any picker for workspace symbols, it's not working. Can you guys help?

**Comment by the-mikedavis** [comment]
Which version are you running? Please use the bug report issue template in the future.

This is most likely https://github.com/helix-editor/helix/discussions/5056 which was fixed in https://github.com/helix-editor/helix/pull/5055. That was merged after the 22.12 release so you will need to build from master to use that change.

**Comment by smit2909** [comment]
Oh..okay, I am on version 22.12..that could be reason. I will build from
master then, thanks 🙇‍♂️
