### ISSUE TITLE
Workspace Symbols don't work with pyright lsp

### ISSUE THREAD

**Issue by smit2909** [helix-editor/helix#5382]
### Summary

I am using pyright language server with below configuration, the workspace symbol picker does not show anything.

[[language]]
name = "python"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
file-types = ["py", "pyi"]
config = { "analysis" = { "autoSearchPaths" = true, "diagnosticMode" = "workspace", "useLibraryCodeForTypes" = true } }
auto-format = true
formatter = { command = "black", args = ["-", "-q"] }

### Reproduction Steps

 

Open any python project and a python file, in my case its a Django project and just open workspace symbol picker.

Log file shows below 

2023-01-03T17:57:43.124 helix_term::application [ERROR] Language Server: Method not found client/registerCapability

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-01-03T17:57:43.124 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
```

</details>

### Platform

macOs

### Terminal Emulator

westerm

### Helix Version

22.12 (96ff64a8)

**Comment by the-mikedavis** [comment]
This was fixed in https://github.com/helix-editor/helix/pull/5055 (merged after the 22.12 release, so you'll need to build from master to use it)

Pyright bails out and sends the empty list when the query is empty: https://github.com/microsoft/pyright/blob/d48b124719f37135d9aae17634ef8c1a2b75afed/packages/pyright-internal/src/analyzer/program.ts#L1659-L1663. #5055 sends new requests when you update the search in the workspace symbol picker so if you're running on master after #5055 was merged, you will still see an empty picker when you hit `<space>S` but then if you type a query into the picker you should see results
