### ISSUE TITLE
Scrolling with mouse/touchpad doesn't work anymore

### ISSUE THREAD

**Issue by gbaranski** [helix-editor/helix#552]
### Environment

- Platform: Linux, (alacritty + tmux) / kitty
- Helix version: v0.3.0-226-gb20a5c4

**Comment by archseer** [comment]
Note: this never worked outside of tmux, but tmux emulates up/down events on scroll if mouse mode isn't enabled. https://github.com/helix-editor/helix/pull/509 changed this, we need to manually handle scroll wheel events now. Should be a simple change since we already have the `scroll` command implemented.

\cc @sh7dm

**Comment by sh7dm** [comment]
It worked in GNOME terminal as well. I can submit a patch for that in a couple days.
