### ISSUE TITLE
insert mode: context free popups - hover

### ISSUE THREAD

**Issue by kendfss** [helix-editor/helix#5549]
### Summary

I've not yet figured out how to intentionally trigger the 'hover' display from insert-mode without (assumption) using a keymap. I assume it occurs between parentheses (don't know if it's expected to appear elsewhere, I think struct/class/func-names should be possible) but it does not go away when it does come up, even after I've made changes in contexts that don't warrant its presence, like when completions are in view, or should spawn a new instance.

I can close it by `esc`, but that also exits insert mode.  

it also closes when:
- removing the opened parentheses (gopls)

I have some ideas for a solution, that could also help with #1381 and https://github.com/helix-editor/helix/pull/4144, but before I get to those its important to at least ask the following question:
- Should completion and hover displays be simultaneously visible or is this a non-bug?
  + I think it is a bug because the hover display doesn't seem to close when it becomes obsolete unless the user exits insert mode. Then there's the issue of too much auxilliary information on the screen
  + If it is not a bug/this behaviour is intended, I do not want to impose; please feel free to say so and close the issue

A solution should, if even necessary, address or circumvent two things:
- Failure to auto-close the display
- Departure from insert-mode to close the screen

The following solutions lean on circumvention, the difficulties are estimates by someone who is admittedly not very familiar with the code base:
1. change the behaviour of `esc` handler such that it first looks for sub-displays (command menus, pickers, command palette, /dev/stdout, ..., completions, hovers) and closes the top one before returning. Go to normal mode if, and only if, none are found. 
  a) could be easy if all of those sub-displays implement a common interface and those interfaces already have a syntactic access point
1. when opening a completion display, find and close any hover display(s), before returning
1. figure out how to automatically close a hover display when its no longer needed

### Reproduction Steps

 

na

### Helix log

na

### Platform

Linux

### Terminal Emulator

Tmux in gnome-terminal

### Helix Version

helix 22.12 (051cd786)

**Comment by the-mikedavis** [comment]
That is signature-help (https://github.com/helix-editor/helix/pull/1755) rather than hover. It should possible to have signature-help open at the same time as completion. For the overlapping bug, see https://github.com/helix-editor/helix/issues/3821. For dismissing signature help, you can use Ctrl+c in insert mode or exit to normal mode as you say. There is also this issue discussing when the signature-help pane should be open - https://github.com/helix-editor/helix/issues/3385 - but that behavior is up to the language server rather than helix: we send trigger events when you type a trigger character like `(` or `,` and the language server sends back signatures.

**Comment by kendfss** [comment]
Sorry for the late reply, but yeah, this solves my problem. Cheers!
