### ISSUE TITLE
"C" + "," keeps only the last selection

### ISSUE THREAD

**Issue by tcoratger** [helix-editor/helix#5760]
### Summary

3"C" (Copy selection onto the next line (Add cursor below)) + "," (Keep only the primary selection) results in keeping only the last selection.

### Platform

macOS

### Terminal Emulator

Warp

### Helix Version

hx -V

**Comment by tcoratger** [comment]
But horizontally, it behaves differently:
- `x` to select the whole line
- `s` to search an item inside (`test` in my case)
- I obtain different cursors (2 in my case)
- If I press `,` only the first persists
![Capture d’écran 2023-02-01 à 10 45 46](https://user-images.githubusercontent.com/60488569/216008240-f28f60b3-5d68-4cb2-8311-1eb9cb95426c.png)

- Following this, I was expecting the same behaviour vertically
![Capture d’écran 2023-02-01 à 10 48 34](https://user-images.githubusercontent.com/60488569/216009011-d93d9fe8-cff4-42a1-92d2-008f0fef15a8.png)

**Comment by CptPotato** [comment]
Right, the tutor makes it sound like it should work the other way around.

I'm not sure if this is the intended behavior of `C`, I personally don't have a strong preference here. Maybe somebody else can chime in?

**Comment by the-mikedavis** [comment]
Yep this behavior of `C` is intentional and it matches Kakoune. `C` adds a new selection based on the location of the primary selection. If `C` didn't make the new selection the primary selection then `C` would only work once.

The tutor should be updated to say that the first cursor will be removed, here: https://github.com/helix-editor/helix/blob/0f562dfeabc7b4abd643de0e1846a612a42145b0/runtime/tutor#L542

`C` and `s` are not really related and they behave very differently already when you have multiple selections: `C` adds a new selection and keeps the current selections unchanged while `s` subsplits all existing selections.
