### ISSUE TITLE
Line is soft-wrapped even if within `max-line-length` limit

### ISSUE THREAD

**Issue by jlebon** [helix-editor/helix#5810]
### Summary

With `soft-wrap.enable = true`, when editing files with a `max-line-length`, lines may be soft-wrapped even if it would've fit within the `max-line-length` limit. This is most easily seen when writing git commits:

![image](https://user-images.githubusercontent.com/11934099/216684903-00518903-c39e-43a2-9325-49e1e3c33f2c.png)

The singular `A` (preceded by a space) would've fit within column 72. `:reflow` calculates it correctly and does not break line, so the soft-wrap persists.

### Platform

Linux

### Terminal Emulator

tmux inside GNOME Terminal

### Helix Version

22.12-218-gf7bd7b5e

**Comment by pascalkuthe** [comment]
The reason for this is that newlines are always a selectable character in helix that takesup horizontal space. The line needs to be wrapped here because otherwise the newline character exceeds the 72 column width limit. I could change the `max-line-length` option to be interpreted as `max-line-length + 1` for softwrap purposes to remedy that but that would not work correctly on the last line (which doesn't have a newline character).

**Comment by jlebon** [comment]
> The reason for this is that newlines are always a selectable character in helix that takesup horizontal space. The line needs to be wrapped here because otherwise the newline character exceeds the 72 column width limit.

Though note `:reflow` does not count the newline character towards the `max-line-length` limit. I expected the softwrap logic to also match this. If they don't agree, the rendering will not converge. To put this another way, I would expect a freshly `:reflow`ed paragraph to not display any softwrapped lines.

**Comment by pascalkuthe** [comment]
Yeah I suppose that is the lesser of two evils here. submitted #5813 with a fix

**Comment by gabydd** [comment]
I believe this was fixed by https://github.com/helix-editor/helix/pull/5893
