### ISSUE TITLE
xc combo is not intuitive

### ISSUE THREAD

**Issue by d-mceneaney** [helix-editor/helix#585]
#### Describe your feature request

When the cursor is on the line below, one can enter the combo "xc" from normal mode to:

1) Select current line
2) Change selection (delete and enter insert mode)

Intuitively, one would expect the "contents" of the line below (with the number 10) to be wiped but the line to remain intact with the cursor in insert mode, ready to repopulate with new text. Instead the line is deleted and the cursor is placed in insert mode on the line below. This action appears to be working more like a "delete selection" instead of a "change selection".

Scenario as below. User enters "xc" in normal mode.
```
fn get_num() -> i32 {
    10                  <-cursor on this line in **normal** mode
}
```

Expected Result
```
fn get_num() -> i32 {
                     <-cursor on this line in **_insert_** mode
}
```

Actual Result
```
fn get_num() -> i32 {
}<-cursor on this line in **_insert_** mode
```

**Comment by Cons-Cat** [comment]
``x`` selects the entire line, including the ``/n``. Kakoune does this too. I agree that this behavior is generally less useful than ``cc`` in Vim, though.

**Comment by d-mceneaney** [comment]
Thanks Cons-Cat, it just seemed a bit strange that `xc` combined means "change line", but ends up deleting the entire line (due to also selecting the `\n` as you pointed out). This means the user would then require an additional action such as "`<Esc>O`" to get a fresh empty line back, ready for editing.

I am a total novice with Helix, so I'll see if I am overlooking a more idiomatic way to change a line. Failing that, I can always look at using a key binding. 

Thanks

**Comment by pickfire** [comment]
Or you can do `glc`.

**Comment by dead10ck** [comment]
There was some chatter in Matrix, so I'll just relay it here: I'm proposing that we make a new command. This command will behave somewhat like `[ "trim_selections", "change_selections" ]` (i.e. always trim whitespace before changing) so that when whole lines are selected, we only want to change the *content* of the lines, not the entire line itself. The problem with doing this in general is that if the user has any blank lines at the start or end of their selection, trimming would deselect them, which would make it hard to change entire blank lines. So what we can do is check if there are any blank lines at the start or end, and if there are, do not trim that side. So to summarize, the command is:

1. For each range in the selection, if there are any completely blank lines at the beginning of the range, leave it alone; otherwise, trim the whitespace from the left end of the range.
2. Same for the right.
3. `change_selection`

I think this behavior will be more intuitive for what people expect the change command to do, especially if they're coming from vim. If @archseer agrees, if this command works out well, we could even make this command the default for `c`, but still keep the `change_selections` command for those who prefer the current behavior.
