### ISSUE TITLE
Append then <del> behaves unpredictably

### ISSUE THREAD

**Issue by Awesomerly** [helix-editor/helix#6029]
Open a new buffer using either `hx` or `kak`.

Replay these keystrokes.

`ifoo<space>bar<esc>ghea<del><del><del><del><esc>`

In Kakoune, the buffer reads "foo". in Helix, the buffer reads "bar".

AFAIK, when appending to a selection in Helix, pressing the delete key moves the selection back. This does not happen in Kakoune.

**Comment by pascalkuthe** [comment]
I can reproduce this. The reason this is happening is that due to gap indexing we are essentially deleting part of the selection (the cursor) which causes it to shrink. To solve this we need to do some kind of tricks for commands that delete forward.

The solutution I am leaning towards is extending the selection before apllying the transaction if  `head >= anchor`. I might try to solve this in #6024 as I am touching the relevant code there anyway.

**Comment by pascalkuthe** [comment]
I I cluded a fix in #6024

**Comment by Awesomerly** [comment]
ty :D
