### ISSUE TITLE
`eb` selected an incorrect range on one character

### ISSUE THREAD

**Issue by lisiur** [helix-editor/helix#6063]
### Summary

`eb` selected an incorrect range on one character

### Reproduction Steps

 

I often use `eb` to select a word when moving forward. For example, in the sentence `<cursor>This is a sentence`, using `eeb` selects `is`, but when using `eeeb` to select `a`, it actually selects `is `.

To be more specific, I would like the `b` key to only select `\w` when the selection range is `\s+\w` and the cursor is under `\w`. Similarly, when the selection range is `\w\s+` and the cursor is under `\w`, I would like the `e` key to only select `\w`.

### Platform

macOS

### Terminal Emulator

iterm2

### Helix Version

helix 22.12 (44729fba)

**Comment by dead10ck** [comment]
This looks like expected behavior. `b` moves to the previous word start. When your selection is

`This is[ |a|] sentence`, the previous word start is indeed `is`. `a` is a whole word, so looking backwards, it has to go to the previous word.

Also, whitespace doesn't really have anything to do with this. You get the same result starting with

`This is [a] sentence`

**Comment by clo4** [comment]
Yeah, this doesn't seem like a bug to me. `miw` seem like what you want, if the goal is to select a word regardless of its length. You can even make a single keybinding to do this too :)

**Comment by lisiur** [comment]
I found the pattern using `eb` is the fastest way to move the selection forward and select a word precisely, but it doesn't work for words with only one character. But I realize now that this is expected. Maybe I should use @clo4 's suggestion.

If there is another better way, please let me know :)

Closed as it's not a bug.
