### ISSUE TITLE
Autocomplete/ Grammar not working on NixOS

### ISSUE THREAD

**Issue by dankeyy** [helix-editor/helix#6099]
I get no autocomplete at all, as I gather what i needed to do is `hx --grammar fetch`, but
```console
[nix-shell:~/testing]$ hx --grammar fetch
Fetching 107 grammars
107 grammars failed to fetch
        Failure 0/107: Could not create grammar directory "/nix/store/fj5a20w0sadd9d52y0z6d692nqjl955s-helix-22.08.1/lib/runtime/grammars/sources/elixir"
...
```
Because of course in NixOS the store is read-only.
Any suggestions?
Spinning up a FHSUserEnv for this seems a little silly

Ideally I'd like helix to rely on local files only

**Comment by archseer** [comment]
To get autocomplete you need to install language servers specific to your language. The grammar fetching is something you don't need to do on a packaged build.

**Comment by dankeyy** [comment]
Of course I have the language server installed (say rust-analyzer, hx --health confirms it), autocomplete still doesn't show up

**Comment by the-mikedavis** [comment]
For grammars not building because of the immutable store: https://github.com/helix-editor/helix/issues/3346

Autocomplete doesn't involve the tree-sitter grammars though.

What does the log file say when you are editing a project in a language like rust where you have the language server installed? https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file (`hx -v`)

**Comment by dankeyy** [comment]
Ok I believe it was my wrongdoing with a cargo.toml
Anyway all works now so I'm closing this
Thanks guys
