### ISSUE TITLE
Prevent cursor jump with `auto-save = true`

### ISSUE THREAD

**Issue by Brixy** [helix-editor/helix#6158]
### Summary

The combination of being in insert mode,

```
[editor]
auto-save = true
```

and

```
[[language]]
auto-format = true
```

can cause a cursor jump when Helix gets unfocused.

### Reproduction Steps

**Example:** If you write a single-line markdown file

```
Helix
```

and then unfocus Helix (staying in insert mode), the language server inserts a new line and places the cursor on line two.

**Expected behaviour:** I would expect Helix/the language server to insert the new line without moving the cursor while staying in insert mode.

**Reason:** That is because markdown and other languages require an empty line at the end of the document.

**Temporary Solution (without changing configs):** Manually inserting an empty line at the end of the document and writing on the line before the last kind of solves the problem; but this is not user friendly.

Thanks a lot, folks!

### Platform

Void Linux

### Terminal Emulator

foot version: 1.13.1 

### Helix Version

helix 22.12 (052ee6f4)

**Comment by dead10ck** [comment]
Helix is actually not doing this edit itself; formatting comes from the language server or formatter. And generally speaking, you want the cursor to move with the code when it is auto formatted; otherwise, it ends up in some random position as the code moves around underneath it, which would be even more annoying.

With this combination of auto saving and auto formatting, the document is going to move around when you shift focus.
