### ISSUE TITLE
Unable to remap control and shift on MacOS (Kitty terminal emulator)

### ISSUE THREAD

**Issue by rkshthrmsh** [helix-editor/helix#6181]
Remapping the control and shift keys on MacOS is not working (Kitty terminal). I understand that the option key requires remapping to alt on MacOS as mentioned in #2280. But I could not find anything similar for the control and shift keys. Here is a part of the config.toml:

```toml
[keys.select]
"C-esc" = "remove_primary_selection"
```

**Comment by the-mikedavis** [comment]
What version of Helix and Kitty terminal are you running? It is possible to bind commands to this key-combination now after #4939 has been merged if you are using a terminal emulator that supports the enhanced keyboard protocol (Kitty does).

I'm not sure if this is a typo in the post but that key combination in the `config.toml` example is holding Ctrl and hitting Escape rather than Shift. We can't bind keys to presses of modifier keys like Ctrl, Shift or Alt - the key combination also needs any other non-modifier key.

With an example config of:

```toml
[keys.normal]
C-esc = "toggle_comments"
```

and pressing Ctrl+Escape, I see toggle_comments being run when running Helix from master.

**Comment by rkshthrmsh** [comment]
I am on Helix 22.12 and Kitty 0.27.1.
With the config.toml, I was just giving an example of a key combination that I could not bind. Have tried both `C-` and `S-` without success.

**Comment by the-mikedavis** [comment]
Are you building Helix from source? #4939 is the change that allows remapping C-esc and S-esc. Also see https://github.com/helix-editor/helix/wiki/Terminal-Support#enhanced-keyboard-protocol

**Comment by rkshthrmsh** [comment]
I am not. Will try it out soon. Any idea when this might be bundled into a release?

I will close this issue now. Thanks for the help, @the-mikedavis.

**Comment by the-mikedavis** [comment]
We try to cut a release every few months (see https://github.com/helix-editor/helix/wiki/FAQ#when-will-the-next-release-be). We're tentatively thinking of mid/late March for the next release if we can find the time to review and merge everything we want to.
