### ISSUE TITLE
LSP (clangd) actions open duplicate buffers

### ISSUE THREAD

**Issue by jazzfool** [helix-editor/helix#6182]
When I perform navigational code actions through the LSP (clangd), e.g., gd (goto definition), it opens a duplicate buffer with the absolute path rather than the path relative to pwd. This buffer is separate from the original buffer even though they refer to same file, so I can unknowingly write changes to this duplicate buffer, then overwrite those changes in the original buffer, which is frustrating since I end up losing my work.

For example, within buffer "src/code.cpp" -> gd -> opens buffer "C:/full/path/to/src/code.cpp" (cursor at the definition).

I expect the correct behavior to be for it to resolve the LSP's requested file path relative to pwd such that
a) It doesn't open the buffer with an absolute path if it's under pwd and
b) subsequently, doesn't open a duplicate buffer

**Comment by stabor705** [comment]
Is it possible that this is windows only issue? Have no problem like that on linux.

**Comment by jazzfool** [comment]
I tried this with Linux and yes, it does seem to be on Windows only, and specific to clangd

**Comment by pascalkuthe** [comment]
We do automatically canonicalize paths so I suspect that this is a windows issue. This looks a bit like https://github.com/helix-editor/helix/issues/6182 but in this case it shouldn't apply because we are converting the URLs to paths (which ignore prefix casing). Another issue with windows is that it's a case insensitive file system. Is it possible that your path contains something uppercase but  clangd sends it back lowercase? We might need to automatically lowercase all paths on windows (which is a real pandoras box once you consider non-ascii paths, we night need to call the windows API for that)

**Comment by jazzfool** [comment]
I did some testing and can confirm it seems to be associated with path casing.

`mkdir Test` then in helix `cd Q:\test`, `o file.cpp`, `gd`, opens `Q:\Test\file.cpp` (notice the casing difference!)

However, if I instead in helix cd into `cd Q:\Test`, this issue does not occur.

So essentially you are correct, if the casing of pwd in helix differs from the filesystem, path canonicalization fails.

**Comment by pascalkuthe** [comment]
Thanks for confirming. The right way to fix this is to implement a better canonicalization strategy. The  way to correctly normalize a path is to obtain a file descriptor and to turn that file descriptor back into a path. Path equality is fundamentally file system dependent so even on windows different drives might have different canonicalization strategy.

Luckilty this is exactly what the std `Path::cannonicalize` function does. We don't use it because:
* It returns weird looking (but technically more correct) paths
* it doesn't work for paths that don't exist.

The first problem.can be resolved by usinf https://docs.rs/dunce/latest/dunce/fn.canonicalize.html instead of std cannonicalize (it would be great if the standard library adopted but not holding my  reath for that). Under the hood (with std) and (on windows) it then simplifies the result back to a traditional path if possible.

For the second problem I think the right way to fix this is to: Walk up the ancestors with `Path::ancestors` and try to cannonicalization and it succeeds return the result of canonicalization with the rest of the path (so the part that doesn't exist yet) normalized with our existing implementation joined om top. This implementation also has the added bonus of properly handeling softlinks.

Should.not be hard to send a PR to implement what I described

**Comment by jazzfool** [comment]
I had a look through the relevant code and I don't think canonicalization is actually the issue here. The issue is just that `strip_prefix` (in `get_relative_path`) is case-sensitive and therefore fails if `std::env::current_dir` is cased differently to what the LSP returns. See my fix here: #6290
