### ISSUE TITLE
Error on :change-current-directory to subdirectory of hidden directory

### ISSUE THREAD

**Issue by heliostatic** [helix-editor/helix#629]
Trying to change directory to `~/.config/helix` when I found this error. Semi-related question: is it possible via config to automatically change the working directory to the directory opened with helix, instead of the current shell path when opening (e.g. `hx ~/code/some-directory` sets that to the `cwd` even when executed in `~/some/other/directory)?

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/70898/130169932-286c5191-1b37-47c4-b70c-f6a47b1a246c.png">

https://user-images.githubusercontent.com/70898/130169629-4113df75-d0bf-4633-91fc-69a83ceb3ab0.mp4

**Comment by archseer** [comment]
This looks like a missing tilde expansion, you likely need to provide the full directory path? `~` is a shell abstraction and the OS doesn't expand it for you.

**Comment by heliostatic** [comment]
> This looks like a missing tilde expansion, you likely need to provide the full directory path? `~` is a shell abstraction and the OS doesn't expand it for you.

I wondered if this was the case, but the subdirectory listing is working fine inside helix. You're right that providing the full path works, but now I'm curious why the behavior is different between the listing and changing.

**Comment by archseer** [comment]
That's because we expand the tilde there, as well as hide it on document names: https://github.com/helix-editor/helix/blob/16bf8e1e6b52546ba804dc7206317c4e368dcfb5/helix-view/src/document.rs#L320-L348

You should be able to call expand_tilde on the argument inside the command: https://github.com/helix-editor/helix/blob/16bf8e1e6b52546ba804dc7206317c4e368dcfb5/helix-term/src/commands.rs#L1830-L1847
