### ISSUE TITLE
:set soft-wrap.wrap-indicator does not work with empty string

### ISSUE THREAD

**Issue by sicher** [helix-editor/helix#6392]
### Summary

I'm trying to disable the soft wrap indicator from the command line.

### Reproduction Steps

 

I tried this:

1. `hx`
2. ':set soft-wrap.wrap-indicator ""'

I expected this to happen:

The soft wrap indicator should be disabled.

Instead, this happened:

Bad arguments. Usage: ':set key field'

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

kitty 0.26.5

### Helix Version

helix 22.12 (6d5fa204)

**Comment by pascalkuthe** [comment]
This is a result of the current `:set` parsing rules. `:set \"\"` works.

This will be fixed in #8853 or #10389. I haven't decided how exactly but I want to revamp the set syntax either to just use somekind of scheme evaluation or a custom syntax that doesn't rely on json parsing. 

Closing in favor of those two PRs
