### ISSUE TITLE
Missing build (aarch64-macos) for 22.03 release

### ISSUE THREAD

**Issue by rossjones** [helix-editor/helix#6495]
The new 23.03 release (https://github.com/helix-editor/helix/releases/tag/23.03) doesn't have an ARM version for OSX, whereas one exists for the previous releases.

Was expecting to find the release at https://github.com/helix-editor/helix/releases/download/23.03/helix-23.03-aarch64-macos.tar.xz

Edit: Looks like build issues mean it was disabled earlier
https://github.com/helix-editor/helix/commit/e59cb19892c7b3987d9e27ae8505a5a42bc4e07d

**Comment by the-mikedavis** [comment]
The aarch64 darwin build ran into a cross-compilation problem https://github.com/helix-editor/helix/actions/runs/4572207374/jobs/8071312127

Once that's fixed we should be able to push a darwin aarch64 artifact to the existing 23.03 release.

In the meantime you can building from source but please follow the full from-source build instructions. Installing using only `cargo` and the git URL will not properly install Helix and you will not have tree-sitter features or a tutor file. https://docs.helix-editor.com/install.html#building-from-source

**Comment by the-mikedavis** [comment]
It looks like this was caused by switching from the old rust-toolchain action to the new one (https://github.com/dtolnay/rust-toolchain). The old one would call `rustup target add` if the `target` option was passed (see [here](https://github.com/helix-editor/rust-toolchain/blob/6bbb331ffcc44b148bf62cd68a72bb0132181cdd/src/main.ts#L82-L84)) while the new one only calls `rustup toolchain install` (see [here](https://github.com/dtolnay/rust-toolchain/blob/b44cb146d03e8d870c57ab64b80f04586349ca5d/action.yml#L71-L73)).

We could call `rustup target add` ourselves (https://github.com/helix-editor/helix/commit/982574cf788aee550ac12e24cf0cb49ecbb808da, https://github.com/helix-editor/helix/actions/runs/4575803555/jobs/8079298943) but I think it's better to fix this upstream since the behavior is a little surprising. Once that build finishes I'll upload the artifact to the 23.03 release and then send a PR upstream

**Comment by the-mikedavis** [comment]
I just uploaded the aarch64-macos artifact to https://github.com/helix-editor/helix/releases/tag/23.03

#6504 should fix this in the long-run

**Comment by rossjones** [comment]
Thanks for the super-speedy turnaround!
