### ISSUE TITLE
[Haskell - HLS] Some LSP Hints are not applied. "Outdated workspace edit for ..."

### ISSUE THREAD

**Issue by 0rphee** [helix-editor/helix#6543]
### Summary

Some haskell LSP hints for refactoring, like removing unnecessary parentheses, redundant lambdas, etc. don't work, instead an error is shown in the status bar: `Outdated workspace edit for path/to/file.hs`

Other LSP code actions work correctly though, as far as I know only the suggestions marked as "hints" are affected. 

https://user-images.githubusercontent.com/79347623/229311308-152ad176-0968-432d-ac9b-454fad396647.mov

### Reproduction Steps

 

I tried this:

1. `hx file.hs`
2. add `func = \a -> a`
3. LSP hint will appear: "Redundant lambda (...)"
4. `space + a` to apply code action `Apply Redundant lambda`

I expected this to happen:

Code action is executed.

Instead, this happened:

Nothing happens and error is thrown: `Outdated workspace edit for path/to/file.hs`

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-01T16:01:07.494 helix_term::commands::lsp [ERROR] outdated workspace edit for "/Users/roger/Documents/Dev/haskell-proj/schedule-maker/src/Lib.hs", expected 3548 but got 0
2023-04-01T16:01:07.494 helix_view::editor [ERROR] editor error: outdated workspace edit for "/Users/roger/Documents/Dev/haskell-proj/schedule-maker/src/Lib.hs"
```

</details>

### Platform

macOS aarch64

### Terminal Emulator

Alacritty 0.12.0 (1)

### Helix Version

23.03-1-g406c5c38

**Comment by pascalkuthe** [comment]
I can reproduce this but this seems like an upstream issue.

The LS standard contains the notion of a document version. Whenever a document is edited a new unique version is created. Any change is associated with a unique id and if that version doesn't match the client version then the edit is invalid and ignored by the client (as happens here).

Looking at the logs it seems that the haskell language server sends the correct version for the most part but for some events the version is just set to `Number(0)`. Perhaphs they meant to send `null` (in which case the version is ignored)? Either way there is nothing we can do about this on our side.

It seems that this currently works in vscode because vscode isn't as strict as it could/should be about enforcing these versions currently. This is a known issue with the vscode language client. See for example https://github.com/microsoft/vscode-languageserver-node/issues/752#issuecomment-795566339.

**Comment by 0rphee** [comment]
Hmm, thats unfortunate. I'll go with the HLS folks then. Thanks!

(p.s. I updated the first comment with the logs, if there's any use to that, it seems to happen what you said)

**Comment by Deepaksinghmar** [comment]
Just take down RRP request and reboot the system.

**Comment by July541** [comment]
I through the logic about executing code action, finding the `helix` increased the version while executing. May I confirm that it's the client's duty to increase the version, and the server just needs to supply the doc version it received?

**Comment by pascalkuthe** [comment]
Yes only the client manages the document versions. Every time the client sends a document to the server (mostly with `textDocument/didChange`) it sends a version identifier. The server must either process events consequitively or use snapshots of the document so that it always knows what document version is the current one.  An edit sent to the client belongs to a single document version and can only be used when that version matches the version of the client. Otherwise the edit could be incorrect and messup the document (or cause a crash)

**Comment by 0rphee** [comment]
Fixed with https://github.com/haskell/haskell-language-server/pull/3643
