### ISSUE TITLE
Building from source installation update

### ISSUE THREAD

**Issue by linc01** [helix-editor/helix#6612]
Hello,

I installed the 22.12 by building from the source, so what is the best way to do an update to the latest release without changing the custom configurations(`~/.config/helix`)? 

Thanks!

**Comment by cd-a** [comment]
Updating helix by either recompiling from source or installing a new release will not overwrite your `~/.config/helix` files.

The only thing that will change is basically the binary. You can also have multiple versions on your machine at the same time.

To update to the latest release I recommend using your package manager of choice for your platform. Then you can check with `hx --version` if the latest release is used, otherwise remove your previously compiled binary or adjust your `PATH` that the release one is used first.

**Comment by linc01** [comment]
@cd-a Thanks, the `hx --version` is 23.03 now, it works fine as usual.
