### ISSUE TITLE
Panic when opening jump list

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#6628]
### Summary

This happened accidentally while editing, so there are no reproduction steps.

```
thread 'main' panicked at 'Attempt to slice past end of RopeSlice: slice end 213, RopeSlice length 182', /Users/kira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ropey-1.6.0/src/slice.rs:656:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: ropey::slice::RopeSlice::slice
   3: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   6: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
   7: alloc::vec::Vec<T,A>::extend_desugared
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
   9: helix_term::commands::jumplist_picker
  10: helix_term::ui::editor::EditorView::handle_keymap_event::{{closure}}
  11: helix_term::ui::editor::EditorView::handle_keymap_event
  12: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
  13: helix_term::compositor::Compositor::handle_event
  14: hx::main_impl::{{closure}}
  15: tokio::runtime::park::CachedParkThread::block_on
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  17: hx::main

```

### Helix log

N/a

### Platform

macOS

### Terminal Emulator

Kitty 0.27

### Helix Version

Helix 23.03 (531b745c54e5d316603601cc05ade50ab02066ab)

**Comment by kirawi** [comment]
\cc @pascalkuthe

**Comment by pascalkuthe** [comment]
The cause for this panic is that the jumplist is updated lazily:
```
    /// A mapping between documents and the last history revision the view was updated at.
    /// Changes between documents and views are synced lazily when switching windows. This
    /// mapping keeps track of the last applied history revision so that only new changes
    /// are applied.
    doc_revisions: HashMap<DocumentId, size>,
```

When we open the jumplist picker we however we collect the jumplist from all open views. Theser are not necessarily up to date and can therefore cause out-of-bounds access. To fix the panic there are two options:
* only display the jumplist for the current view (behavioral change)
* sync all views before opening the jumplist picker

the second variant is probably what we want since the other "fix" is a behavioural change. We already have the code that does this too in `Editor::focus`:
``` rust
            // Update jumplist selections with new document changes.
            for (view, _focused) in self.tree.views_mut() {
                let doc = doc_mut!(self, &view.doc);
                view.sync_changes(doc);
            }
```

probably just need to move this to a shared function and call it

**Comment by pascalkuthe** [comment]
Ah actually one more detail I missed: we only call `view.apply` (updating the jumplist) in `append_changes_to_history` so this bug could also be caused from calling the picker in insert mode so we might also have to call `append_changes_to_history` for every document. Probably can be left to future work tough since the mantra is kind of "don't bind commands in insert mode" right now anyway.
