### ISSUE TITLE
Turning off mouse mode leaves terminal in a broken state

### ISSUE THREAD

**Issue by m-c-g** [helix-editor/helix#6638]
### Summary

Setting `mouse = false` and reloading the config and then exiting breaks mouse handling in the terminal.  

Clicking or moving the mouse after quitting sends codes to the command line. Removing the line from config and reloading will stop this behaviour but doesn't seem to fully restore the terminals mouse handling; text selection no longer works the way it should.

This is happening with Ubuntu running in VMFusion on a M1 mac using the Tilix terminal.
I also checked this using the byobu terminal and saw the same behavior

This doesn't happen in MacOS running in the Warp terminal.

Could this be a problem with Helix or is it something with VMWare? 

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux on VMWare Fusion

### Terminal Emulator

Tilix. Byobu 

### Helix Version

helix 23.03

**Comment by the-mikedavis** [comment]
Currently we look at the `editor.mouse` setting when claiming and restoring the terminal only (which happens when we start and exit Helix respectively). So I think what's happening here is that we start Helix with mouse support enabled, we [tell the terminal emulator that we want to capture mouse inputs](https://github.com/helix-editor/helix/blob/58e457a4e1037caf43c17dea93c5321c1ae74103/helix-tui/src/backend/crossterm.rs#L124-L126). Then if you reconfigure `editor.mouse` to `false`, we don't tell the terminal to [disable mouse event capture](https://github.com/helix-editor/helix/blob/58e457a4e1037caf43c17dea93c5321c1ae74103/helix-tui/src/backend/crossterm.rs#L142-L144). I can't reproduce this in Kitty or WezTerm so I think it may be Tilix specific. I'm guessing that most terminals disable mouse events when the running application exits raw mode. I think it should be possible to fix this by sending DisableMouseCapture or EnableMouseCapture when the config changes.

**Comment by m-c-g** [comment]
I did a pull and recompiled, It seems ok now.
