### ISSUE TITLE
YAML indentation

### ISSUE THREAD

**Issue by antoyo** [helix-editor/helix#6661]
### Summary

It seems the auto-indent doesn't work for YAML.

I would expect helix to indent when a line containing `:` and keep the same indent as the previous line otherwise.

### Reproduction Steps

I tried this:

1. `hx file.yml`
2. Open a new line.

I expected this to happen:
the new line should be indented.

Instead, this happened:
the new line starts at character 0.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-08T15:51:30.050 helix_view::editor [ERROR] Failed to initialize the LSP for `source.yaml` { cannot find binary path }
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty 0.12.0 (5a728195)

### Helix Version

helix 23.03

**Comment by dead10ck** [comment]
I'll take this one on; I've been meaning to fix this anyway, since it bugs me regularly. I actually am not sure there are many, if any, situations where we don't just want to carry the current indentation level to the next line. Maybe for less common cases like `|` and `>` strings, or for multi line maps/lists explicitly denoted with `{}` / `[]`.
