### ISSUE TITLE
file picker ignore option not working propely

### ISSUE THREAD

**Issue by antoyo** [helix-editor/helix#6698]
### Summary

Hi.
It seems that the file picker can show files ignored by a `.ignore` file.
One weird thing is that searching for the ignored pattern in the file picker won't show the file, i.e. it will only be shown by scrolling to it.

Here's my config:
```
[editor.file-picker]
hidden = false
git-ignore = false
```

### Reproduction Steps

(I didn't find a way for you to reproduce this issue locally, but here are the instructions I used locally.)

I tried this:

1. git clone https://github.com/rust-lang/rustc_codegen_gcc && cd rustc_codegen_gcc
2. Create a file `.ignore` containing `target`.
3. hx src/lib
4. <Space>f to open the file picker
5. Scroll down and see files in `build_sysroot/target`.

I expected this to happen:
Files in `build_sysroot/target` should not be shown.

Instead, this happened:
Files in `build_sysroot/target` were shown, while files in `target` were correctly not shown.

### Helix log

Nothing in the log.

### Platform

Linux

### Terminal Emulator

alacritty 0.12.0 (5a728195)

### Helix Version

helix 23.03

**Comment by pascalkuthe** [comment]
Closing this out as stale.

* The entire picker has been replaced with nucleo since this was created. 

* I suspect this would be an issue with `ignore` not interpreting your glob correctly or you using the wrong ignore syntax
* The whole it's thee when you scroll down but not on filter sounds super odd and I can not conceive or reproduce how that would happen. But then again all code that would have been involved when this issue was created is long gone

**Comment by Rudxain** [comment]
I have a similar problem with `.gitignore`. It seems like it only works if `.git/` exists
