### ISSUE TITLE
Extra indentation in Go switches

### ISSUE THREAD

**Issue by mvdan** [helix-editor/helix#6772]
### Summary

Go switches by themselves should not indent their contents; it's only the bodies of each `case` which are indented. It seems like Helix wants to indent both, meaning that the body of each `case` ends up with one extra level.

### Reproduction Steps

Use `o` to insert a new line right after a `switch` or `case` line in Go. The new line is indented one level more than desired.

https://asciinema.org/a/xklzt1tRNliVp4SM02BmuR11Z

I believe the problem is that [we indent switches like other languages](https://github.com/helix-editor/helix/blob/4cdba7cccdd6a9fe5fbb3d15c9db3edc147b7a90/runtime/queries/go/indents.scm#L18-L19), when in fact Go doesn't indent the entire switch block like other languages.

I suspect that the fix in https://github.com/helix-editor/helix/pull/5713 should be made to work for `switch` as well as `select`, and I'm happy to try to send a PR if that works.

Is there a way for me to edit and test a change to that `indents.scm` file without having to build all of Helix from source? Can I copy the file into `~/.config/helix` somewhere, make the change, and test it to send a PR?

### Platform

Linux

### Terminal Emulator

foot 1.14.0

### Helix Version

helix 23.03

**Comment by mvdan** [comment]
Ah, from `hx --health` I see:

> Runtime directory does not exist: /home/mvdan/.config/helix/runtime

**Comment by kirawi** [comment]
You don't have to recompile Helix to change the queries. The queries are loaded at runtime. You can check: https://docs.helix-editor.com/guides/indent.html

**Comment by Triton171** [comment]
That sounds reasonable. You'll probably need both `@indent` and `@extend` captures for the `expression_case` node. And you'll also need to exclude the `expression_switch_statement` from the `@outdent` query for `}` (but you probably know that already).

**Comment by mhmdanas** [comment]
I'm using Helix 23.05 on Void Linux, and it doesn't seem like this issue has been resolved for me, even though I confirmed that the contents of /usr/lib/helix/runtime/queries/go/indents.scm match with the changes made in #6817:

![image](https://github.com/helix-editor/helix/assets/32234660/9e1064a3-4dfb-4940-82e5-483c102210d2)

Am I missing something here?

**Comment by pascalkuthe** [comment]
Yeah the autopairs inserting a hard-coded ident always felt hacky to me but I am not sure if we can make indentation for partial syntax trees reliable enough to remove it?

**Comment by Triton171** [comment]
I think right now the main issue is that the position for which we want to compute the indentation doesn't exist yet. If we have curly braces `{}` and the user presses enter between them, we want to compute the indentation for the space _between_ the curly braces (which at this point still has width 0). Using either of the curly braces will usually yield a different result, e.g. because of `@outdent` queries. The easiest implementation might be to add a parameter to the `treesitter_indentation_for_pos` function which tells it to exclude nodes that start exactly at the query position. That way, one could set this parameter to `true` and use the position of the closing curly brace in the auto-pairs code.

I think reliability of the indent heuristic would not be a much bigger issue with this change than it already is. We _already_ use the indent heuristic to compute the indentation for the closing brace (and the inner new line is simply indented one unit more than whatever we compute there). This means that almost every issue of this new version is already an issue in the current master, since the indent query for the new line in the middle would just consider a subset of the tree-sitter nodes that the indent query for the closing brace considers.

**Comment by mhmdanas** [comment]
@Triton171 yes, that's it, thank you for clearing this up.
