### ISSUE TITLE
Subtle bug in soft wrapping?

### ISSUE THREAD

**Issue by sicher** [helix-editor/helix#6829]
Hi, I have no insight into how soft wrapping works technically, but I wonder if this is intended behavior. And if it is, if it would make more sense to have helix wrap on whole WORD objects rather than words?

To illustrate, I have the following wrap settings:

    text-width = 80
    soft-wrap = { enable = true, wrap-at-text-width = true, max-wrap = 25, wrap-indicator = "" }

Now, if I enter the following:

    This is a piece of text that will fill more than eighty characters and then wrap,
      expectedly, to the next line.

Here the comma ends up at column 81 (hence why I wonder if this may be a bug?). But moreover, the following space is pushed to the next line. Here I believe it would be nicer if the wrapping would push the WORD "wrap," to the next line:

    This is a piece of text that will fill more than eighty characters and then
    wrap, expectedly, to the next line.

**Comment by pascalkuthe** [comment]
I am aware of this. The current width limit was increased by one because people we complaining that lines wrapped one character to early thanks to the EOL character taking a width of 1. I have a more correct fix in #6417 but that will take some time to finish

**Comment by sicher** [comment]
Ok. Just to clarify: If you change the "wrap," to "wrapx", the "wrapx" will be pushed to the second line.

**Comment by pascalkuthe** [comment]
Ah sorry I only scanned the issue those are two seperste issues. I was talking about the "wraps at column 81" which is a bug and fixed by the PR I mentioned. Wrapping at WOR doesn't work well for programming languages. There was a tom of discussion about netter wrap strategies in the orgiknal softwrap PR #5420 (but everyone agreed that it should be left to future work). The conclusions was pretty much:
* we probably want language specific wrapling strategies (for prose a streaming version of unicode line breaks)
* improving the wrapping as descrived here https://github.com/helix-editor/helix/pull/5420#issuecomment-1400751633

**Comment by sicher** [comment]
Ok, thanks for the clarification!

**Comment by kj** [comment]
@archseer Is this fixed? I just tried this in master with the same settings and the following text (sorry for the silly example):

```
foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, 
```

For me that ends up looking like this:

![helix_soft_wrap](https://github.com/user-attachments/assets/91a2e1c0-100b-4ee0-ac4b-e8a24d476162)

I understood that the idea was to wrap the words onto the next line and not the space?
