### ISSUE TITLE
Add yank_joined command

### ISSUE THREAD

**Issue by rcorre** [helix-editor/helix#6888]
We have `yank_joined_to_clipboard` and `yank_joined_to_primary_clipboard`.
I'd like to have `yank_joined` so I can yank/paste multiple separated selections inside helix, without going through the system clipboard. This is especially relevant if you're working over SSH and using OSC52 for clipboard support, which makes copy/paste via the clipboard less efficient than copy/paste within helix.

**Comment by ghc0** [comment]
Don't you think this should be implemented by a script instead of built-in function?

Giving 3 tools e.g. a b c, you can combine them to create new 6 functions: abc, acb, bac, bca, cab, cba. You can pick what you need instead add them all into helix wasting default key mapping and ruin the complexity of doc.

This is called **product**.  Offering basic elements only, let the users combine them to create millions new functions as they wish.

**Comment by kirawi** [comment]
@ghc0 This issue is not related to keymapping nor will it meaningfully impact the complexity of learning Helix. Helix aims to be batteries-included, and it is within the rights of the maintainers to determine what fits within that scope.

**Comment by rcorre** [comment]
FWIW, yanking with multiple cursors maintains a separate buffer for each cursor, which is _usually_ what you want, but here was a case where I wanted to join selections:

```
## Header1
... lots of text ...
## Header2
... lots of text ...
## Header3
... lots of text ...
```

I wanted to insert this at the bottom:

```
- Header1
- Header2
- Header3
```

I tried `%s##<cr>xy`, which created a cursor on each header and yanked the line. Then I hit `ge` to go to the end of the document where I wanted to paste, but that collapsed my cursors. So maybe if there was a way to move all my cursors to the end without collapsing them, that would have worked too?

**Comment by Randalix** [comment]
I'm having the same issue. Would be great to see it fixed.

**Comment by gabydd** [comment]
Closed by https://github.com/helix-editor/helix/pull/7195
