### ISSUE TITLE
'insert_register' support for clipboard

### ISSUE THREAD

**Issue by bcspragu** [helix-editor/helix#6897]
Helix has support for `C-r`  and then a register to insert the contents of that register without leaving insert mode. But since the clipboard isn't mapped to a register in Helix (AFAIK), there's no way to do a `C-r <paste from clipboard>`. In Vim/NeoVim, the clipboard is mapped to `*` or `+`, depending on what selection we're talking about.

The workaround in Helix is to type `<ESC><Space>pa`, to exit insert mode, paste from the clipboard, and pick up after the insertion. This works fine, but it'd be more ergonomic to not leave insert mode. I'd make a custom mapping (something like `C-r <space>`), but I don't think the remapping system currently supports something like that.

**Comment by bcspragu** [comment]
I just realized `paste_clipboard_after` is a thing, which would get me closer to what I'm looking for, but adding a mapping like:

```toml
[keys.insert]
C-r = { 'space' = 'paste_clipboard_after' }
```

Breaks the behavior of `C-r` for normal registers

**Comment by the-mikedavis** [comment]
You should also be able to use whatever key combination your OS/terminal uses for pasting from the system clipboard in insert mode. Now that we implement bracketed paste, that should be very fast (i.e. not https://github.com/helix-editor/helix/issues/2239).

The clipboard doesn't show up in `insert_register` (`C-r`) because it isn't a register

**Comment by bcspragu** [comment]
You know, that never occurred to me. Sure enough, it works as advertised in alacritty with `Ctrl+Shift+v`, thanks!
