### ISSUE TITLE
Typing text offsets diagnostics that are after text typed

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#701]
https://asciinema.org/a/8zyizvoNTUMkDhhzeaS10qw0W

I presume this is probably because of char indexing for the diagnostics.

**Comment by archseer** [comment]
I did initially map diagnostics through edits to prevent this (updating the positions), but I noticed that rust-analyzer would unhelpfully re-send the wrong offsets immediately, undoing the work.

**Comment by archseer** [comment]
(It'll fix the positions after you save and it re-runs the checks)

**Comment by archseer** [comment]
Commented out code:

https://github.com/helix-editor/helix/blob/7e1123680f474bff5113db189f63ca7f948781a5/helix-view/src/document.rs#L638-L646

**Comment by kirawi** [comment]
Is there anything that can be done about it?

**Comment by archseer** [comment]
Turns out this is a known rust-analyzer issue: https://github.com/rust-analyzer/rust-analyzer/issues/8836

**Comment by gabydd** [comment]
correct me if I am wrong but I think this is fixed on master

**Comment by the-mikedavis** [comment]
I think this still happens unless it was fixed in a recent rust-analyzer version. From what I understand this is caused by rust-analyzer sending out-of-date/cached ranges in publishDiagnostic which undoes the work we do within helix for updating ranges https://github.com/rust-lang/rust-analyzer/issues/10628#issuecomment-950904152
