### ISSUE TITLE
Configurable placeholder for snippets

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#7045]
Currently, placeholders aren't included when a completion is confirmed. It feels a little awkward, at least In Rust, since you can't use `]a` or `[a` to write out the arguments.

**Comment by pascalkuthe** [comment]
snippet placeholders are never meant to be inserted into the document.  In fact the plan is to replace them with virtual text in the future. Snippet placeholders are intended as text that gives you a hint what text should be inserted there, not a form of autocompletion.

Placeholders are act as jump points that you can reach while pressing `tab`(and `s-tab`) so that will cover the jump between usecase once implemented. At that point having this option doesn't make sense IMO and I don't think we should add a new config option that would be useless once we have better snippet support

**Comment by kirawi** [comment]
That's interesting. But at least locally, VSCode does keep the placeholders. Would you have any idea why?
