### ISSUE TITLE
Add not zero check on tab-width.

### ISSUE THREAD

**Issue by So1aric** [helix-editor/helix#7094]
If set tab-width to zero, helix will crash (divided by zero). The error might occured from the helix-core/grapheme.rs.
Although it's a bit weird to set tab-width to zero (or even negative numbers), presenting the tab-width as 1 and alerting instead of panic would be better, IMO.

**Comment by Niketin** [comment]
Hi!

I am trying to get to a point where I could replicate the crash and debug the editor, but I am facing a problem. I am unable to change the tab-width. I am new to Helix, so I might do something wrong.

I configured tab-width to 2 in the `~/.config/helix/languages.toml`.
```toml
[[language]]
name = "rust'
indent = { tab-width = 2, unit = "  " }
```
Then I reopened the editor (built in debug mode, if it matters), then I opened some Rust source file. The problem is that when I try to indent some selection using the `<` or `>`, it still uses 4 spaces. What am I doing wrong here?

**Comment by ravsii** [comment]
> ```toml
> [[language]]
> name = "rust'
> indent = { tab-width = 2, unit = "  " }
> ```

@Niketin  If this is your EXACT config, then your `rust` string is opened with a double quotation, but closed with a single one, making the config invalid

**Comment by Niketin** [comment]
I am sorry @ravsii, it is not the exact config because something weird happened to the text when I copy&pasted it from terminal.

The config should be this, with correct double quotations and without that weird brown highlighted text (if you can see it).
```toml
[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  " }
```

**Comment by ravsii** [comment]
@Niketin This is probably a rust-only bug, probably because of the `cargo fmt`, as it uses its own settings and should probably be changed inside the `formatter` option.

I'd suggest trying js,ts or some other web-related stuff. Working fine in svelte for example. (reproduced the crash as well)
![image](https://github.com/helix-editor/helix/assets/5007271/ed491d68-be1c-41e6-9f0e-2783142001e6)

**Comment by gabydd** [comment]
it might be picking it up and the auto-indentation detection is just overriding the setting cause the document uses spaces to indent, see src: https://github.com/helix-editor/helix/blob/92380540b858b66f247789e5270d61c9d1305033/helix-view/src/document.rs#L888-L891

**Comment by apanloco** [comment]
you can reproduce this by:
`echo "\t" > file.rs`
then putting the above languages.toml configuration:
```
[[language]]
name = "rust"
indent = { tab-width = 0, unit = " " }
```
followed by
`cargo run -- file.rs`
```

 16:        0x103c1c408 - helix_core::graphemes::tab_width_at::hb5c054a65728acf8
                               at /Users/da/code/helix/helix-core/src/graphemes.rs:20:26
```

<img width="457" alt="image" src="https://github.com/helix-editor/helix/assets/155063/a0d7c2d5-2c73-489a-a30e-b22babd6b04d">

if the alerting is not important we could do a max(1, tab_width).

**Comment by apanloco** [comment]
we could nip it at the bud here in document.rs:
<img width="555" alt="image" src="https://github.com/helix-editor/helix/assets/155063/f7c73f4d-fb4d-4d06-9a46-bf1b8cebb476">

**Comment by gabydd** [comment]
The linked pr (https://github.com/helix-editor/helix/pull/7178) makes it an error to have a non zero tab-width in your config which solves this issue without needing any custom logic

**Comment by Niketin** [comment]
I think it is in the right place, @kirawi. It's located in `~/.config/helix/languages.toml`. I have the config file in the same directory and it works fine.

> it might be picking it up and the auto-indentation detection is just overriding the setting cause the document uses spaces to indent, see src:
> 
> https://github.com/helix-editor/helix/blob/92380540b858b66f247789e5270d61c9d1305033/helix-view/src/document.rs#L888-L891

I believe @gabydd this is why I couldn't reproduce the problem.

> you can reproduce this by: `echo "\t" > file.rs` then putting the above languages.toml configuration:
> 
> ```
> [[language]]
> name = "rust"
> indent = { tab-width = 0, unit = " " }
> ```
> 
> followed by `cargo run -- file.rs`
> 
> ```
> 
>  16:        0x103c1c408 - helix_core::graphemes::tab_width_at::hb5c054a65728acf8
>                                at /Users/da/code/helix/helix-core/src/graphemes.rs:20:26
> ```


@apanloco's instructions worked!
