### ISSUE TITLE
match in (or around) should favour selecting something on the current line

### ISSUE THREAD

**Issue by wheelsandmetal** [helix-editor/helix#7191]
Suppose you have your cursor where the | is
```
    "foo bar" some other text
    dont select me please
  | "select me"
```

I think I would expect `mi"` to select `select me` but instead it selects as shown

```
    "foo bar"< some other text
    dont select me please
  |>"select me"
```

The way neovim handles this with `vi"` works better, but there are some inconsistencies with it too. `vi"` anywhere on the 3rd line selects `select me`, but pressing it on the 2nd line selects between last `"` on the 1st line and the end of the 2nd line. Only if I add non-whitespace chars before the `"` on the 3rd line will neovim select them.

There are also cases where helix behaves better. For example
```
"""
foo
bar"""
```

`vi"` anywhere on the last line doesn't select anything, whereas `mi"` on bar will select foo and bar (however putting the cursor on a `"` causes helix to select nothing)

I'm not sure on the ideal solution, but having a bias to make a selection on the current line, and having a bias to select _something_ would be good.

**Comment by pascalkuthe** [comment]
Helix has the deliberate design choice to only select text that actually contains the cursors. Selecting the next pair if there is none around the cursor was proposed (and rejected) before. 

Without treesitter (so for plain text Giles) it's also impossible to recognize for identical pairs whether we are between two quotes or not without transversing the entire files and counting pairs (which is way too slow for large files). We might oneday augement the matching with tree sitter which would prevent helix from matching in this case.

To solve your usecase you simply need to move your cursor onto `select me so that doesn't really matter for you

**Comment by wheelsandmetal** [comment]
> We might oneday augement the matching with tree sitter which would prevent helix from matching in this case.

is there an issue for this?
