### ISSUE TITLE
C++ indentation is wrong for access specifiers

### ISSUE THREAD

**Issue by MostlyMax** [helix-editor/helix#7206]
### Summary

Closing bracket of class methods in access specifiers is not indented properly.

```
class Foo {
  public:
    Foo() {
    
  } // missing an indent
}
```

### Reproduction Steps

Create a method after an access specifier and let helix auto indent the closing bracket. 

Expected closing bracket to be in-line with the method name.

### Platform

Linux

### Terminal Emulator

foot 1.14.0

### Helix Version

helix 23.05 (3a8592ab)

**Comment by emadkhan713** [comment]
Wanted to say this is also the case on Windows 10 Pro v22H2 (build 19045.2965), running Helix from Command Prompt.

Also, it seems more like the editor is not indenting _anything_ following the access specifier. Will investigate further.

**Comment by pascalkuthe** [comment]
CC @Triton171 Is this a simple oversight in the query or some limitetion of tgenindent code. In know there was some weirdness around c++ and I am not sure if it relates to this

**Comment by Triton171** [comment]
This is a situation where people format their C++ code differently. The convention that helix supports (and that is also more common in my experience) is:
````cpp
class Foo {
public:
  Foo() {
    
  }
}
````
Since there are no official code formatting guidelines for C++, this sort of thing tends to be common there (see also #6235). The current indentation system cannot really handle this (since indent queries don't adapt to the style in the current file). I have [an idea](https://github.com/helix-editor/helix/issues/6939#issuecomment-1534604690) how this could be improved which I'd like to implement at some point. There are definitely some tricky details to it but if we think about it carefully, it should essentially be possible to keep the advantages of tree-sitter based indentation while also never being significantly worse than the relative regex-based logic that most other editors use.
