### ISSUE TITLE
Do not exit with an error code if language server fails to shut down

### ISSUE THREAD

**Issue by JustinLovinger** [helix-editor/helix#7211]
I use `ltex-ls` for commit messages. With the latest Helix, commits will sometimes fail because I close the commit editor before `ltex-ls` started up. Aside from this example, I see no good reason a process calling Helix will need to treat a language server failing to gracefully shut down as an error in the file edited by Helix.

**Comment by getreu** [comment]
I run into the same problem with the same use case. In general, I suppose the reason for the exit error code is, that when the language server has no time to shut down properly, the edited files can be left in an inconsistent state, e.g. when you rename a variable with LSP. In case of `ltex-ls` the problem is not the shut-down time, but it is the long start-up time. Nevertheless, while starting `ltex-ls`, it should be OK to kill the `ltex-ls` process and to exit `hx` without an exit error code.
