### ISSUE TITLE
Please add multi-cursor support using mouse

### ISSUE THREAD

**Issue by blueray453** [helix-editor/helix#757]
#### Describe your feature request

![output](https://user-images.githubusercontent.com/855297/133228447-51cf3093-f740-43c9-a7ef-3eee930289f5.gif)

If I press `shift+alt` and then drag using mouse, it adds multiple cursor in vscode.

If I press `alt` and then click on a places where there is **no cursor**, vscode add cursor to each place.

If I press `alt` and then click on a places where there is **a cursor**, vscode remove that cursor.

Please add these features to helix.

**Comment by pickfire** [comment]
There was an attempt on this.

> If I press shift+alt and then drag using mouse, it adds multiple cursor in vscode.

But not this probably. IIRC pressing alt or ctrl adds a cursor or if dragged it will be the selection.

**Comment by blueray453** [comment]
I noticed that if I press `alt+click`, it creates new cursors. wonderful!

However, `shift+alt` does not seem to work.

**Comment by pickfire** [comment]
Why `shift+alt`? It wasn't set to `shift+alt` so of course it won't work.

**Comment by archseer** [comment]
`alt+click` will add additional cursors to your selection (same with `alt+drag`). (I think we should probably make it `shift+click`, that's what seems to be more obvious to me).

Removing would be possible but I'd like to keep the mouse functionality simple, it should really be disabled by default. It's not the intended way to interact with helix but I've accepted it since it's useful to some.

**Comment by blueray453** [comment]
`alt+drag` does not create multiple cursors in my machine.

I know using mouse is a noob thing. However, i am a beginner user and trying to move to helix. So, I would need these functionality at the beginning  and may remove then when I no longer need them.
