### ISSUE TITLE
helix does not take the whole screen

### ISSUE THREAD

**Issue by blueray453** [helix-editor/helix#758]
### Reproduction steps

run `hx` on alacritty.

### Environment

- Platform: Linux
- Helix version: helix 0.4.1

<details><summary>helix 0.4.1</summary>

When I open helix in alacritty, it does not take the whole screen. I am attaching a screenshot bellow. You can see different color in all four corners.

![Screenshot-2021-09-15-09:41:27](https://user-images.githubusercontent.com/855297/133367872-7aaa4876-4f19-4d7a-9ee7-b9cd295f7e94.png)

</details>

**Comment by archseer** [comment]
It _does_ cover the whole screen. Are you talking about the command-line below?

**Comment by blueray453** [comment]
if look look at four sides you will see different colors. The editor is purple. Alacritty is using solarized dark theme. You can see the solarized dark color in all four sides.

**Comment by archseer** [comment]
There's usually some edge, but this is due to the terminal not being exactly sized so there's some margin that's too small to fit in text. Helix can't really do anything about that, we use all the available space the terminal provides to us. You'll see the same problem in Vim or any other terminal editor. FWIW this seems to go away for me if I fullscreen alacritty.

**Comment by blueray453** [comment]
Then please [add a solarized dark theme](https://github.com/helix-editor/helix/issues/759) so that it does not look odd.
