### ISSUE TITLE
C/C++: comment not highlighted after macro

### ISSUE THREAD

**Issue by Hpixpoke** [helix-editor/helix#7587]
After a #define macro, comments (block and line style) are not highlighted. This seems to apply to #pragma and #error too.

helix 23.05 (Windows)

**Comment by the-mikedavis** [comment]
Can you post an example snippet?

**Comment by Hpixpoke** [comment]
```cpp
#if !defined(__cplusplus)
#error C++ compiler required. // not highlighted
#endif
```

```c
#define SIZE 32 /* here as well */
```

**Comment by pascalkuthe** [comment]
I can reproduce but this is correct. C macros extend until the end of the line so the C TS grammar correctly mark any text until the end of the line as a single opaque macro. This is just a result of the C preporecsor being horrible. 

We could theoretically inject the C language into C preprocessor tokens the way nvim does but this also has issues and I always found it hacky

**Comment by pascalkuthe** [comment]
I am closing this since the highlighting is working as intended here

**Comment by zhaob1n** [comment]
> We could theoretically inject the C language into C preprocessor tokens the way nvim does but this also has issues and I always found it hacky

Hi @pascalkuthe . As a C developer, I really believe syntax highlighting for macro is of great help. It increases readability A LOT and helps people writing macro as well. it's difficult to get the syntax right in macro because lsp doesn't help you until you use that macro, and the diagnosis is not even inline.

So I think it's worth a hack, it makes life a lot easier for C macro developer.
