### ISSUE TITLE
Yank to system clipboard

### ISSUE THREAD

**Issue by kevinsjoberg** [helix-editor/helix#76]
It would be nice if you could yank the current selection to the system clipboard.

**Comment by archseer** [comment]
I'd like to see this added, I recommend using https://github.com/alacritty/copypasta since it also includes Wayland support.

Both yank and delete always use `register::set`: https://github.com/helix-editor/helix/blob/661dbdca57f76cbd22f3e62f8b87ee2146a50bab/helix-term/src/commands.rs#L1766

Which is a dumb hashmap with a lock right now: https://github.com/helix-editor/helix/blob/661dbdca57f76cbd22f3e62f8b87ee2146a50bab/helix-core/src/register.rs#L9

I think we should special case certain registers inside `set`/`get`, in this case `"` should interface with the clipboard instead of the map.

**Comment by archseer** [comment]
Some discussion on the implementation: https://github.com/helix-editor/helix/pull/119#issuecomment-855880649

**Comment by CBenoit** [comment]
We also discussed on matrix about not using registers, for example using commands (`clipboard-yank`, `clipboard-paste`), to handle pasting and yanking from system clipboard.
This approach is similar to emacs and kakoune.

> idk if this helps inform anything but in kakoune i set `user y` as yank to clipboard and `user p` as paste from clipboard and am reasonably happy with that. it doesn't let me do fancy things like idk, copying to the clipboard from somewhere else and executing that as a macro, but i don't really find myself needing more functionality often
since kakoune lacks a `+` register in the first place
especially since if you don't treat it as a register then you can make the semantics different from registers in the ways that they fundamentally differ

By _ash_ from matrix (I don't know your github ID)

**Comment by pickfire** [comment]
> We also discussed on matrix about not using registers, for example using commands (clipboard-yank, clipboard-paste), to handle pasting and yanking from system clipboard.

I still think using registers is a cleaner approach. Because we have quite some keys that work with clipboard, like `ctrl-r *` later if we want to paste from clipboard in insert mode.

**Comment by ThomasDuPlessis** [comment]
Could helix support OSC 52 as a simpler alternative? that is if we only care about yanking to the clipboard and not from it.

**Comment by CBenoit** [comment]
I guess it could easily be supported as a plugin. I'm not sure if this is useful enough to be part of the core (I personally never used it).

**Comment by pickfire** [comment]
> I guess it could easily be supported as a plugin. I'm not sure if this is useful enough to be part of the core (I personally never used it).

I wish it is in core, I always use this. I missed this in kakoune and I had to manually copy out the region with lots of spaces in kakoune, bad experience.

**Comment by n8himmel** [comment]
What's wrong here?

```

Bad config: TOML parse error at line 16, column 9
   |
16 | C-S-s = "clipboard-yank"
   |         ^^^^^^^^^^^^^^^^
No command named 'clipboard-yank'


Bad config: TOML parse error at line 16, column 9
   |
16 | C-S-s = "clipboard_yank"
   |         ^^^^^^^^^^^^^^^^
No command named 'clipboard_yank'
```
