### ISSUE TITLE
Neovim-like exact scrolling 

### ISSUE THREAD

**Issue by AlexanderDickie** [helix-editor/helix#7639]
I find helix's keyboard scrolling (using C-d/C-u for example) quite disorientating mainly because I often want to scroll up a bit, then scroll back down to the cursor's original position, helix's scrolling doesn't always do this depending on initial cursor position. This is the behaviour I want (exact same behaviour as neovim).

https://github.com/helix-editor/helix/assets/75994927/18f4562f-c9ea-4de0-8a16-ee4cc8ebcdf4

I dont really like this behaviour for mouse scrolling though. 

Would you support this as an option in the config? something like `keyboard-scroll-exact: true | false`, `mouse-scroll-exact: true | false`. Or maybe only have the keyboard option

I've implemented this behaviour locally and can make a pr for this

**Comment by pascalkuthe** [comment]
I think what you mean (and what nvim does) is a to have a separate command/key to move the cursor and view at the same time instead of making the scrolloff drag the  cursor along. That could be reasonable. Could you link your implementation?

**Comment by pascalkuthe** [comment]
If we add this this should be a separate command tough and not a config option (that means we won't be able to change mouse scroll until that is prebindable but I am fine with that)

**Comment by AlexanderDickie** [comment]
Yeh thats a good way to describe it- https://github.com/AlexanderDickie/helix/tree/scroll-cursor-and-page . I've made it so the position of the cursor relative to the view is always constant and you can always get back to a previous position, for any consecutive sequence of vertical scrolls.

I also like/(I've implemented) how when you do C-d and land on a new row, the column idx is not at 0, but at the min(row_len, old_visual_position_row)- same behavior as when pressing j for example. Maybe this behaviour could also go in the current scroll fn also?

**Comment by AlexanderDickie** [comment]
@pascalkuthe What do you think about implementing this feature as a component? 

I think I will need to hold some state in order always be able to get back to achieve  'always able to get back to a previous position for any consecutive sequence of cursor+view scrolls'. Without state I would need to always jump a fixed amount on every C-d/C-u, but this would break if after jumping the cursor lands on a row of virtual text- the cursor cant be on virtual text, so you wouldnt be doing an exact jump anymore and you could not C-.. back to the previous position.
I could get around this by not counting virtual lines when jumping but I dont really like this as you arent really doing half/full page scrolls anymore. 

Holding state would also making the behaviour nicer on some of the edge cases near the top of the page, for example if the cursor is on line 10, the top of the view is on line 5, what happens if you press C-u? I could either have nothing happen to keep my 2 behaviours, or (using state) I could allow the view and cursor to both move to line 0 and break my 2 behaviours somewhat, but then be able to scroll the cusor+view back to lines 5, 10. 
It would be a pretty simple component, just hold a stack that you push coords to when C-d and pop when you C-u/ vice versa.

**Comment by pascalkuthe** [comment]
I don't think holding state is really necessary. Nvim doesn't do that either and the cursors simply moves all the way down/up. While that does break being able to bo back I personally thing that's not too bad. In general  I think these commands would be useful. I would be personally inf favour of making these the default mabbing for pageup/c-u (which matches nvims default) but kakune doesn't have this default so changing the default might be controversial. That's just a oneline change so that can be discussed during review.


Respecting the horizontal offset during both scrolling and for these new commands makes a lot of sense to me and is also how both kakune and nvim behave so that would be a welcome change IMO. This should be pretty easy to add inside the scrolling function.

One thing you should be careful that helix always uses visual movement by default (so if the lines are soft-wrapped the cursor should not jump multiple lines at once).

**Comment by woojiq** [comment]
@AlexanderDickie sorry to bother you but I want to ask if you are going to finish it? If not, I'd like to take it 😉

**Comment by AlexanderDickie** [comment]
@woojiq yeh i'll make the pr this weekend :)
