### ISSUE TITLE
problem when go to append_mode in blank line

### ISSUE THREAD

**Issue by guazai22** [helix-editor/helix#7914]
### Summary

In a blank line, when press "a", the cursor will jump to the start of next line.
I feel that if the cursor stay at the same line, just like press "i", is more natural.

I just found this when I use macros,
for example, I want to add word like "xxx" at the end of every line, so I record like:
[ "go to the end of line"  "go to append mode" "insert xxx" "next line" ]
then it has problem on blank lines, it will add "xxx" at the start of next line.

I also found "A", which means "insert_at_line_end", do not have this problem.

### Platform

Linux

### Terminal Emulator

kitty

### Helix Version

helix 23.05

**Comment by woojiq** [comment]
Use `A` (Insert at end of line). For full list of commands press `<space>?`.
If you search there `a` you will find out it's called "append after selection" and basically cursor is selection of 1 symbol.

**Comment by pascalkuthe** [comment]
Yeah this is intended behavior

**Comment by donpdonp** [comment]
I came across this same problem - 'a'ppend at the end of a line should append to the current line, such as in vim, not move to the next line. Moving to the next line is what 'o' is for. I'm commenting here because there is a config key binding that makes 'a' work this way. See the comment in https://github.com/helix-editor/helix/issues/3744#issuecomment-1240726094
