### ISSUE TITLE
Language specific syntax highlighting/theming

### ISSUE THREAD

**Issue by chtenb** [helix-editor/helix#8050]
Generic syntax highlighting themes may not fit all languages perfectly. For example, a theme optimized for C# might not work well for Javascript, because C# has types while Javascript has not. Can we allow theme adjustments per language to accomodate dealing with this? If necessary I can work out a specific use case, but I think the reasoning is clear enough. Other text editors, like VSCode, TextMate, Sublime, etc support this by simply having a language moniker at the end of each highlighting scope, like `keyword.storage.cs`.

Tangentially related issues:
- https://github.com/helix-editor/helix/issues/4501
- https://github.com/helix-editor/helix/issues/836

**Comment by pascalkuthe** [comment]
I don't see a usecase here. We have seperate captures for seperate concepts so the fact that a theme has highlighting for types doesn't matter when dealing with JavaScript because those theme scopes are simpy ignored.

You are free to create theme variants for seperate languages but I don't see us adding that to core.
