### ISSUE TITLE
Completions done mid-item leave erroneous remainder appended (Rust)

### ISSUE THREAD

**Issue by NukeManDan** [helix-editor/helix#8263]
### Summary

Related to https://github.com/helix-editor/helix/discussions/8262 - the completion is given from the cursor _completing the rest of the struct name AND the fields_ so it leaves junk that it should not after the struct fields.

### Reproduction Steps

Example in rust file: 

```rust
pub fn example()
    let something = CompactMerkleMul/*<Cursor here>*/tiProof{};
}
```

Popup to select `CompactMerkleMultiProof{...}` that populates this:

 ```rust
pub fn example()
                                                                       /* 👇 😫 */
    let something = CompactMerkleMultiProof { leaf_indices: , hashes:  }tiProof{}
}
```

### Platform

Linux

### Terminal Emulator

wezterm 20230712-072601-f4abf8fd

### Helix Version

helix 23.05 (7f5940be)

**Comment by pascalkuthe** [comment]
This is the intendede behaviour and not a bug. You can set `completion-replace=true` in your config to change that.

**Comment by NukeManDan** [comment]
This is still a bug, with that enabled only the _name_ of the struct is not left appended incomplete - the braces are still around (and should not be) 

```rust
pub fn example()
                                                                     /* 👇 😫 */
    let something = CompactMerkleMultiProof { leaf_indices: , hashes:  }{}
}
```

**Comment by pascalkuthe** [comment]
Completions are provided by the language server not helix itself (like in every other non-jetbrains editor) you will need to raise that upstream with them.

**Comment by NukeManDan** [comment]
I am confused: the behavior of _helix_ can be configured with `completion-replace` that should understand the context of the item in question, not the LSP... no?

For example, in VScode:

![image](https://github.com/helix-editor/helix/assets/35669742/644fdb06-138a-43e0-8e8b-ffd4970b2836)
:point_down: 
![image](https://github.com/helix-editor/helix/assets/35669742/59a135b8-9fbe-4fd1-9842-61cc0252ba13)

VSCode places `todo!()` and no `{}` appended, where helix places nothing at all as placeholders for the items and `{}` appended... so seems like this is probably to do with the editor, not the LSP, in how the expansion/completion is handled.

**Comment by the-mikedavis** [comment]
Yeah, that VSCode screenshot is using a code action to fill in the fields. You can use `<space>a` to bring up code actions in Helix to do the same thing: https://asciinema.org/a/TdUQkf1J4WNrzA1IUfdFddIZn

The language server sends a range to use for insertion and a range to use for replacement with the completion's edit and `completion-replace` selects which of those ranges you use. So the `{}` at the end isn't trimmed because rust-analyzer is saying that the completion ends at the last character of the struct name rather than at the `}`. Including the `{}` in the range is a problem upstream for rust-analyzer.
