### ISSUE TITLE
go: all-CAPS struct fields are highlighted differently from non-all-CAPS

### ISSUE THREAD

**Issue by ygabuev** [helix-editor/helix#8390]
### Summary

Hi!

I have a following piece of Go code:
```go
package main

type Something struct {
	FIELD      int
	Another    int
	YetAnother int
}

func main() {
	var s = Something{
		FIELD:      0,
		Another:    0,
		YetAnother: 0,
	}
}
```

In helix, the string FIELD - which is all-CAPS - is highlighted differently from other field names when I instantiate a struct:

![image](https://github.com/helix-editor/helix/assets/12871516/d0928a0b-f154-4f91-b8e0-ce90b732733f)

Similar code in e.g. Rust doesn't have this problem:

![image](https://github.com/helix-editor/helix/assets/12871516/eeaae60b-f011-44ad-86ae-d25b16edda23)

Is this a bug? What may be causing this issue?

### Platform

Arch Linux 6.5.4 x86_64

### Terminal Emulator

alacritty 0.12.2

### Helix Version

helix 23.05

**Comment by the-mikedavis** [comment]
This line in the Go highlight queries gives constants (all caps identifiers) the special highlighting: https://github.com/helix-editor/helix/blob/f520b16fcaa2bc13d8d72c09694d88717055d0fd/runtime/queries/go/highlights.scm#L27. We should move that line down further in the file (probably next to `(comment) @comment`) so that it takes the least precedence.

That won't quite fix this case though. We can highlight the fields in the literal struct by adding a line to the Go highlights:

```scm
(keyed_element (literal_element (identifier) @variable.other.member))
```

Which would fit nicely next to https://github.com/helix-editor/helix/blob/f520b16fcaa2bc13d8d72c09694d88717055d0fd/runtime/queries/go/highlights.scm#L40 (the line that gives struct fields their highlight in the `type Something struct { .. }` block)
