### ISSUE TITLE
Performance stutter uncommenting code blocks

### ISSUE THREAD

**Issue by heliostatic** [helix-editor/helix#843]
While uncommenting an arbitrary code block in Rust, it looks like helix is trying to do some parsing/lsp business which causes a ~1 second stutter, along with the message:
`Failed to lower macro args to token tree` which is coming from rust-analyzer, not helix (https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/hir_expand/src/db.rs#L416)

https://user-images.githubusercontent.com/70898/137366620-e23e9e99-dec3-4b0d-b6dc-8f29de92e32e.mp4

**Comment by archseer** [comment]
I think this is because of two things: 

1) The code you're editing is a macro which has to have it's body parsed as a separate syntax "layer". We currently don't cache those so every edit is essentially a full reparse (https://github.com/helix-editor/helix/issues/434 this is something I want to do, but it's tricky to determine which old layers match which injections). We probably hit the worst case parse here since the syntax isn't even fully valid Rust. 

We might want to disable rust macro injections for everything but specific macros like `println!`, `panic!`, `unimplemented!` etc.

\cc @kirawi 

2) The message coming from rust-analyzer seems to be from the initial comment which left out a closing `},` thus yielding a bad syntax tree. Macro parsing is complex so it probably took `rust-analyzer` a second or two to find the error.

**Comment by archseer** [comment]
Incremental rendering has been merged! Additionally a performance issue with calculating diagnostics positions was also fixed https://github.com/helix-editor/helix/pull/1423

I think this should no longer be a problem
