### ISSUE TITLE
Situational LSP on same file extension

### ISSUE THREAD

**Issue by ngasull** [helix-editor/helix#8505]
## Intro
Some languages have multiple possible language servers, in my case the (in)famous Javascript/Typescript:
- `typescript-language-server`
- `deno lsp`
- even `eslint`, `tailwindcss` or any other situational language support, all for the same file types (`jsx?`/`tsx?`)

## Formal issue
Language support may depend on configured tooling in the workspace rather than just file extension. `roots` isn't requiring the existence of the files.

## Possible enhancements
1. Adding a `language.toml` flag key to actually require **one of** the `roots` files to be found to in order to enable the LSP
_Eg. `require-root = true`_
2. Adding a `language.toml` configuration key of **possible marker files** in found root that enables the LSP.
_Eg. `required-roots = ["deno.json", "deno.jsonc", "deno.lock"]`_

Option 1 seems relevant and sufficient to cover multiple LSP per file type while keeping things simple.

## Current workaround
Dropping an `.helix/languages.toml` situationally in workspaces.

**Comment by ontley** [comment]
I want to work on this, but I don't really know where this would check be performed? `Registry::get` maybe?

**Comment by pascalkuthe** [comment]
yeah registry::get is mostly the right place.

I don't think the option should be to only start if roots exists but a bit more general: to only start if the detected lsp root directory (there is always one even if none of the root markers are found) contains files matching any of a list of globs (use globset since we already depend on it).

That way you could also check for a different file here and copying the root markers isn't too hard.

The best way to implement this is probably to make `start_client` return an `Result<Option<T>>` (None corresponds to no marker found and you can simply use the `?` with filter_map to filter those kinds of servers

**Comment by ontley** [comment]
Makes sense, I'll see what I can do.

Unfortunately I'm away until next thursday.

**Comment by ontley** [comment]
> the detected lsp root directory (there is always one even if none of the root markers are found)

Does this refer to `Config.workspace_lsp_roots` / the `root_dirs` argument in `start_client`? They seem to be empty even after :lsp-restart

**Comment by ontley** [comment]
Nvm, I realized I need root_path from `Client::start`
