### ISSUE TITLE
`helix-git` AUR package reinstalls on update

### ISSUE THREAD

**Issue by ZetaNumbers** [helix-editor/helix#889]
This is bad because it also pulls lots of tree-sitter repos. Perhaps the issue can be avoided with weekly releases, but it's not a solution.

### Reproduction steps

`paru -Syu --needed`
and then
`paru -Su --needed`

### Environment

- Platform: Arch Linux
- Helix version: N/A

~/.cache/helix/helix.log: N/A

<details><summary>
If there are new commits
</summary>

```
> paru -Qu
helix-git r4.d60c278-1 -> latest-commit
```
</details>

<details><summary>
If there are not
</summary>

```
> paru -Qu
helix-git r4.d60c278-1 -> 0-2
```
</details>

**Comment by pickfire** [comment]
`-git` is supposed to follow the latest git release, I think the only case when the releases are rare is when helix development slows down, having frequent release is a good sign I believe. Or maybe helix should have more patch release so people can use the original helix rather than `-git`, maybe not a good idea as well since there could be lots of breakage. I wonder if there are such things as `-nightly-git` and `-weekly-git`?

**Comment by vv9k** [comment]
Hey, sorry about that. I will try to update the package every week or two with a new git revision. I uploaded an updated PKGBUILD so it shouldn't reinstall every time.

**Comment by ZetaNumbers** [comment]
Cannot prove since i switched distros but i believe you. Thank you
