### ISSUE TITLE
Nix build error due to missing sources

### ISSUE THREAD

**Issue by SrEstegosaurio** [helix-editor/helix#9319]
### Summary

When trying to build Helix using nix I encounter the following error:

```
fatal: unable to access 'https://git.sr.ht/~nbsp/tree-sitter-gemini/': Failed to connect to git.sr.ht port 443 after 132677 ms: Couldn't connect to server
error:
       … while calling the 'head' builtin

         at /nix/store/0g53xyh39z3y90p4d8r341wbqyjy1zhl-source/lib/attrsets.nix:960:11:

          959|         || pred here (elemAt values 1) (head values) then
          960|           head values
             |           ^
          961|         else

       … while evaluating the attribute 'value'

         at /nix/store/0g53xyh39z3y90p4d8r341wbqyjy1zhl-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: program 'git' failed with exit code 128
```

The problem appears to be the very first line of the log:
```
fatal: unable to access 'https://git.sr.ht/~nbsp/tree-sitter-gemini/': Failed to connect to git.sr.ht port 443 after 132677 ms: Couldn't connect to server
```

### Reproduction Steps

nix build github:helix-editor/helix

### Platform

Linux _(NixOS)_

### Terminal Emulator

foot version: 1.15.1 +pgo +ime +graphemes +fractional-scaling +cursor-shape -assertions

### Installation Method

flake

### Helix Version

helix 23.10

**Comment by SrEstegosaurio** [comment]
I saw this was already discussed and apparently temporally fixed. Or at least that's what I can gather from skimming trough other issues and discussions.

But trying to build it with nix _(using the upstream flake on its last commit)_ outputs the aforementioned error.

**Comment by jesusmgg** [comment]
This was fixed for now with https://github.com/helix-editor/helix/commit/17dd102e5cccbb2a9a0f0224af63e52f3dab846b

**Comment by the-mikedavis** [comment]
There's an ongoing outage with SourceHut that's causing this: https://status.sr.ht/ (even the statuspage appears to be down)

https://github.com/helix-editor/helix/commit/17dd102e5cccbb2a9a0f0224af63e52f3dab846b mostly fixed this but the Nix flake fetches and builds grammars itself. It would be a nice improvement to have `grammars.nix` respect the value of `use-grammars.only` and `use-grammars.except` so it wouldn't fetch these based on the new config in that commit.

Otherwise the flake should work again after SourceHut restores service. I believe they're migrating all of the services to a new datacenter (or something similar) so it may be a while.

**Comment by SrEstegosaurio** [comment]
Yeah, apparently Codeberg is also being targeted according the their official Fediverse account.

I'll temporally patch it myself to remove the dependency since I need it working in order to rebuilding my system but yeah, improving the package is always a good thing.

Thanks for the quick response btw. :heart:
