### ISSUE TITLE
Helix is no longer compatible with Sveltekit page and layout naming conventions

### ISSUE THREAD

**Issue by DaveTJones** [helix-editor/helix#9331]
### Summary

Attempting to create a new page or layout file for Sveltekit by passing the desired name of the file to Helix as an argument now results in an error:
```
> hx +layout.svelte

Error: could not parse arguments

Caused by:
    bad line number after +
```

This can be worked around, but is annoying. Could this be avoided by providing fallback behaviour or parsing arguments which have a file extension differently to other arguments? If so I'm happy to try implementing a fix.

### Reproduction Steps

 

I tried this:

1. `hx +layout.svelte` 

I expected this to happen:
A buffer to open that would later be saved as '+layout.svelte'

Instead, this happened:
Helix attempted to parse the file name as a line number

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Alacritty

### Installation Method

source

### Helix Version

23.10-190-g17dd102e

**Comment by the-mikedavis** [comment]
I think it's reasonable to interpret the argument as a file if we can't parse the number instead of returning an error like we do now. In this block: https://github.com/helix-editor/helix/blob/17dd102e5cccbb2a9a0f0224af63e52f3dab846b/helix-term/src/args.rs#L92-L97

let's set `line_number` when the `arg.parse::<usize>()` is ok and push the arg to the `args.files` vec otherwise.
