### ISSUE TITLE
RPC-based Plugin System

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#998]
In addition to #122, it would be nice to make it possible to implement plugins through an RPC interface like in [Neovim](https://neovim.io/doc/user/api.html). One major benefit from this is that it would make it easier to use scripting languages like Python as the compiler wouldn't need to be compiled down to WebAssembly. Another potential use is that external programs or plugins (not sandboxed) can directly work with Helix. If we accept this as a feature we'd like for Helix to have, I think that it would be best for it to be implemented as a WebAssembly plugin.

See #387 for a real-world use case.

**Comment by kirawi** [comment]
Ideally, I would like it if we could reuse the `.witx` schemas.

**Comment by wingyplus** [comment]
It looks like LSP architecture but for interacting with editor instead of per language. :)

**Comment by jesse-c** [comment]
If it's okay, I'll add my real-world use case that I have in Neovim.

I switch from light/dark appearance in macOS depending on a few factors [1]. I've written a little binary [2] that runs and listens for appearance change events and then tells Neovim [3] to change the theme to the appropriate light/dark one.

[1] macOS default change based on sunrise/sunset, but also just depending on the weather and lighting where ever I currently am.
[2] https://github.com/jesse-c/AppearanceNotifier
[2] https://github.com/mhinz/neovim-remote

**Comment by gcoakes** [comment]
Can we just implement a dead simple pipe based interface which will be trivial to maintain over the long term even when a more complex plugin system gets implemented? I'm thinking something like a pipe file which is read line-wise as a command. It would go through the same code flow as manually entering a command, but the actual command would just be sourced from the pipe. helix is already dependent upon [`tokio`](https://docs.rs/tokio/latest/tokio/io/struct.Lines.html) already has an API for this, and it could just be tacted onto the application event loop.

Something like this seems like it would be easy to maintain. It could be kept in even after a more robust plugin system has been implemented because it's low cost. For some tasks, this might even be preferable to writing a full plugin as it is easily automated by end users. You wouldn't have to understand the inner working of helix's plugin system to automate a simple task. You just have to understand the commands available.

Something like this would reload the theme when it is written to which will improve designer experience:

``` sh
while :; do
  inotifywait -e modify ~/.config/helix/themes/mytheme.toml
  find "${XDG_RUNTIME_DIR-/tmp}/helix/pipes" -mindepth 1 \
  | while read hxpipe; do
    echo 'theme mytheme' > "$hxpipe"
  done
done
```

**Comment by silvergasp** [comment]
Just to chime in gRPC might be a good option. It can be run over various transports e.g. pipes/sockets or http. It also has client-server generators for multiple languages including rust.

**Comment by Xaeroxe** [comment]
Shameless plug, but my crate [`ipc-rpc`](https://docs.rs/ipc-rpc/latest/ipc_rpc/) seems like it might actually be a pretty good fit here. Built in `serde` support, and helix already uses `tokio`. Plus `ipc-rpc` is multiplatform.

**Comment by pascalkuthe** [comment]
Closing, see https://github.com/helix-editor/helix/discussions/3806#discussioncomment-4723781
